#!/usr/bin/env python3
"""PicopixelCyr: Cyrillic for the panel's small font, from one ASCII-art source.

Writes the generated block of src/fonts/picopixel_fb.h between its BEGIN/END
markers. tools/luasim/gen_font.py reads the simulator's copy from that header,
as it already does for the Latin, so the panel and the simulator cannot draw
different letters.

    python3 tools/fonts/mkcyr.py           # rewrite the block
    python3 tools/fonts/mkcyr.py --check   # exit 1 if the header is stale
    python3 tools/fonts/mkcyr.py --show    # every letter as text, for review

Design, from the ledmatrix agent's plan (knowledge base,
docs/drafts/cyrillic-from-openclaw/) and its review of 2026-09-23:

- A second range, U+0400..U+045F, beside PicopixelFB's 0x20..0x7E. One GFXfont
  cannot hold both without 897 empty slots, and Adafruit's print() cannot carry
  a code above 255 anyway, so the drawing goes through src/fonts/pxfb_text.h.
- Geometry as the Latin capitals: 5 rows, yOffset -4, xOffset 0, advance =
  width + 1.
- Lowercase of its own since 2026-09-23 (the owner: the system font has both
  cases, as the Latin does): from X11 misc-fixed 4x6 (tools/fonts/x11/
  4x6-cyrillic.bdf, public domain), whose capitals are 3 x 5 and lowercase 4
  rows over one descender row, Picopixel's own proportions. Its rows are placed
  on Picopixel's baseline and trimmed to their ink. px.text still folds case
  (pxfb_text.h), so scripts that always drew capitals still do.
- Letters that look the same as Latin ones are taken from the Latin font
  itself, so А and A are the same pixels and cannot drift apart.
- Every slot of the block with no letter of its own, and every code point the
  panel cannot draw, shows the MISSING box: a visible sign of a missing glyph
  rather than a silent space.
- 4- and 5-wide letters where 3 pixels cannot tell them apart. И mirrors the
  Latin N, which is 4 wide in Picopixel; Ц has a tail so it is not our flat
  U. The shapes are a first cut: the wall decides, and they change here.
"""
import glob, pathlib, re, sys

ROOT   = pathlib.Path(__file__).resolve().parents[2]
HEADER = ROOT / "src/fonts/picopixel_fb.h"
BEGIN  = "// ---- BEGIN GENERATED by tools/fonts/mkcyr.py - do not edit by hand ----"
END    = "// ---- END GENERATED ----"
FIRST, LAST = 0x0400, 0x045F

# Same as a Latin capital: taken from PicopixelFB, never drawn twice.
SAME_AS_LATIN = {0x0410: "A", 0x0412: "B", 0x0415: "E", 0x041A: "K", 0x041C: "M",
                 0x041D: "H", 0x041E: "O", 0x0420: "P", 0x0421: "C", 0x0422: "T",
                 0x0425: "X"}

# The rest. '#' ink, '.' off; five rows, every row the same width.
ART = {
    0x0411: ["###", "#..", "##.", "#.#", "##."],                 # Б
    0x0413: ["###", "#..", "#..", "#..", "#.."],                 # Г
    0x0414: [".##.", ".#.#", ".#.#", "####", "#..#"],            # Д
    0x0416: ["#.#.#", "#.#.#", ".###.", "#.#.#", "#.#.#"],       # Ж
    0x0417: ["##.", "..#", ".#.", "..#", "##."],                 # З
    0x0418: ["#..#", "#.##", "##.#", "#..#", "#..#"],            # И, the Latin N mirrored
    0x0419: [".##.", "#..#", "#.##", "##.#", "#..#"],            # Й
    0x041B: [".###", ".#.#", ".#.#", ".#.#", "##.#"],            # Л
    0x041F: ["###", "#.#", "#.#", "#.#", "#.#"],                 # П
    0x0423: ["#.#", "#.#", ".##", "..#", "##."],                 # У
    0x0424: ["..#..", ".###.", "#.#.#", ".###.", "..#.."],       # Ф
    0x0426: ["#.#.", "#.#.", "#.#.", "####", "...#"],            # Ц
    0x0427: ["#.#", "#.#", "###", "..#", "..#"],                 # Ч
    0x0428: ["#.#.#", "#.#.#", "#.#.#", "#.#.#", "#####"],       # Ш
    0x0429: ["#.#.#.", "#.#.#.", "#.#.#.", "######", ".....#"],  # Щ
    0x042A: ["##..", ".#..", ".###", ".#.#", ".###"],            # Ъ
    0x042B: ["#...#", "#...#", "###.#", "#.#.#", "###.#"],       # Ы
    0x042C: ["#..", "#..", "###", "#.#", "###"],                 # Ь
    0x042D: ["##.", "..#", ".##", "..#", "##."],                 # Э
    0x042E: ["#..#.", "#.#.#", "###.#", "#.#.#", "#..#."],       # Ю
    0x042F: [".##", "#.#", ".##", "#.#", "#.#"],                 # Я
    0x0401: ["#.#", "###", "##.", "#..", "###"],                 # Ё
}

# Not a letter: what the panel draws for anything it has no glyph for. Solid,
# because no letter or digit is: a hollow box was tried first and read as a
# zero on the test card ("21°C" came out "210C").
MISSING = ["###", "###", "###", "###", "###"]

# Lowercase that looks Latin: Picopixel's own lowercase glyph.
SAME_AS_LATIN_LOWER = {0x0430: "a", 0x0435: "e", 0x043E: "o", 0x0440: "p", 0x0441: "c",
                       0x0443: "y", 0x0445: "x", 0x0455: "s", 0x0456: "i", 0x0458: "j"}
LOWER_BDF = ROOT / "tools/fonts/x11/4x6-cyrillic.bdf"
LOWER = [cp for cp in range(0x0430, 0x0460)]


def x11_lower():
    """4x6's lowercase, on Picopixel's baseline: rows (top first) and yOffset."""
    s = LOWER_BDF.read_text(encoding="latin-1")
    asc = int(re.search(r"FONT_ASCENT (\d+)", s).group(1))
    out = {}
    for m in re.finditer(r"ENCODING (\d+)\n.*?BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)\nBITMAP\n(.*?)ENDCHAR", s, re.S):
        cp = int(m.group(1))
        if cp not in LOWER:
            continue
        w, h, xo, yo = map(int, m.group(2, 3, 4, 5))
        grid = {}
        for r, hx in enumerate(m.group(6).split()):
            v, nb = int(hx, 16), len(hx) * 4
            for x in range(w):
                if (v >> (nb - 1 - x)) & 1:
                    grid[(xo + x, (asc - (yo + h)) + r - (asc - 1))] = 1   # y relative to the baseline row
        if not grid:
            continue
        xs = [x for x, _ in grid]; ys = [y for _, y in grid]
        x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
        rows = ["".join("#" if (x, y) in grid else "." for x in range(x0, x1 + 1)) for y in range(y0, y1 + 1)]
        out[cp] = (rows, y0)
    return out


def latin_art():
    """The Latin capitals as PicopixelFB draws them: its own bitmap, the stock
    glyph table (picopixel_fb.h reuses it), drawChar's bit order."""
    t = HEADER.read_text()
    bm = re.search(r"PicopixelFBBitmaps\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", t, re.S).group(1)
    BM = [int(x, 16) for x in re.findall(r"0[xX]([0-9a-fA-F]{2})", re.sub(r"//.*", "", bm))]
    cand = glob.glob(str(ROOT / ".pio/libdeps/*/Adafruit GFX Library/Fonts/Picopixel.h"))
    if not cand:
        raise SystemExit("mkcyr: build once so Adafruit GFX is downloaded")
    gt = re.search(r"PicopixelGlyphs\[\]\s*PROGMEM\s*=\s*\{(.*?)\};",
                   pathlib.Path(cand[0]).read_text(), re.S).group(1)
    G = [tuple(int(v) for v in m) for m in re.findall(
        r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}",
        re.sub(r"//.*", "", gt))]
    out = {}
    for ch in set(SAME_AS_LATIN.values()) | set(SAME_AS_LATIN_LOWER.values()):
        o, w, h, a, xo, yo = G[ord(ch) - 0x20]
        assert (a, xo) == (w + 1, 0), ch
        if ch.isupper():
            assert (h, yo) == (5, -4), ch
        rows, bit, bo = [], 0, o
        for _ in range(h):
            r = ""
            for _ in range(w):
                if not bit & 7:
                    bo += 1
                r += "#" if (BM[bo - 1] >> (7 - (bit & 7))) & 1 else "."
                bit += 1
            rows.append(r)
        out[ch] = (rows, yo)
    return out


def pack(rows):
    bits = "".join("1" if c == "#" else "0" for r in rows for c in r)
    return [int(bits[i:i + 8].ljust(8, "0"), 2) for i in range(0, len(bits), 8)]


def shapes():
    """Every glyph as (rows, yOffset): capitals 5 rows at -4, lowercase as drawn."""
    lat = latin_art()
    s = {cp: lat[ch] for cp, ch in SAME_AS_LATIN.items()}
    s.update({cp: (rows, -4) for cp, rows in ART.items()})
    low = x11_lower()
    for cp in LOWER:
        if cp in SAME_AS_LATIN_LOWER:
            s[cp] = lat[SAME_AS_LATIN_LOWER[cp]]
        elif cp in low:
            s[cp] = low[cp]
    for cp, (rows, yo) in s.items():
        assert len({len(r) for r in rows}) == 1, hex(cp)
    return s


def build():
    s = shapes()
    bitmap, glyph = [], {}
    def add(rows, yo=-4):
        off = len(bitmap)
        bitmap.extend(pack(rows))
        w = len(rows[0])
        return (off, w, len(rows), w + 1, 0, yo)
    missing = add(MISSING)
    for cp in sorted(s):
        rows, yo = s[cp]
        glyph[cp] = add(rows, yo)
    table = []
    for cp in range(FIRST, LAST + 1):
        g = glyph.get(cp) or missing
        table.append((cp, g))
    return bitmap, table, missing


def block():
    bitmap, table, missing = build()
    rows = "\n".join("    " + " ".join(f"0x{b:02X}," for b in bitmap[i:i + 12])
                     for i in range(0, len(bitmap), 12))
    def g(t): return "{%d, %d, %d, %d, %d, %d}" % t
    gl = "\n".join(f"    {g(t)},  // U+{cp:04X}{' ' + chr(cp) if t != missing else ' missing'}"
                   for cp, t in table)
    return f"""{BEGIN}
// Cyrillic, U+{FIRST:04X}..U+{LAST:04X}: {len(bitmap)} bitmap bytes, {len(table)} glyphs.
// Source: tools/fonts/mkcyr.py. Drawn through src/fonts/pxfb_text.h only.
const uint8_t PicopixelCyrBitmaps[] PROGMEM = {{
{rows}
}};

const GFXglyph PicopixelCyrGlyphs[] PROGMEM = {{
{gl}
}};

const GFXfont PicopixelCyr PROGMEM = {{(uint8_t *)PicopixelCyrBitmaps,
                                      (GFXglyph *)PicopixelCyrGlyphs, 0x{FIRST:04X}, 0x{LAST:04X}, 7}};

// Drawn for any code point the panel has no glyph for.
const GFXglyph PicopixelMissingGlyph PROGMEM = {g(missing)};
{END}"""


def apply(text):
    b = block()
    if BEGIN in text:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: b, text, flags=re.S)
    return text.rstrip("\n") + "\n\n" + b + "\n"


def show():
    s = shapes()
    for cp in sorted(s):
        rows, yo = s[cp]
        print(f"U+{cp:04X} {chr(cp)}  yOffset {yo}")
        for r in rows:
            print("   " + r.replace("#", "█").replace(".", "·"))
    print("missing")
    for r in MISSING:
        print("   " + r.replace("#", "█").replace(".", "·"))


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    if mode == "--show":
        show()
        sys.exit(0)
    old = HEADER.read_text()
    new = apply(old)
    if mode == "--check":
        if new != old:
            print("mkcyr: src/fonts/picopixel_fb.h is stale - run python3 tools/fonts/mkcyr.py")
            sys.exit(1)
        print("mkcyr: header up to date")
        sys.exit(0)
    HEADER.write_text(new)
    bitmap, table, _ = build()
    print(f"picopixel_fb.h: Cyrillic block {len(bitmap)} bitmap bytes + {len(table)} glyphs")
