-- @upload-only
-- GOLF_OLD_COURSE - GOLF CLOCK on Old Course (КАНН-МАНДЕЛЬЕ), eighteen real holes in two minutes.
-- Generated by tools/luasim/golf_courses.py build from golf_clock.lua; edit that, not this.
COURSE = "old_course"
--
-- Two players, ГЕНА and НИКОША, play a full round on a real course: the
-- introduction, eighteen holes of about six seconds each, then the result. The
-- score is always at the top; the real time sits at the bottom right.
--
-- The courses (the owner, 2026-09-24: real ones, and a choice between them):
-- - OLD COURSE, Cannes-Mandelieu. Every tee, dogleg, green, bunker, pond, the
--   Siagne and the woods are where OpenStreetMap has them; par, length and
--   stroke index from the club's 2026 scorecard. Map data (c) OpenStreetMap
--   contributors, ODbL 1.0 - https://www.openstreetmap.org/copyright
-- - ПЕСТОВО, Moscow region. Par, length and stroke index from the club's hole
--   guide (pestovo.golf/club); the shape of each hole, its water and sand
--   placed from the club's hole plans.
-- COURSE picks one ("old_course", "pestovo"); without it the courses take
-- turns, a new one every round. golf_old_course.lua and golf_pestovo.lua are
-- this script with COURSE set, so the portal's gallery and the knob choose.
-- Lengths are metres, as on both scorecards. A new course: see
-- tools/luasim/golf_courses.py.
--
-- A round is made at the start of each two-minute period from the clock, so
-- every run plays a different game. Realistic, not random: each player gets a
-- handicap (6 to 16), and each hole's score against par comes from an amateur's
-- spread for that handicap - mostly pars and bogeys, some birdies, the odd
-- double, an eagle or a hole-in-one rarely. The shots are then laid out to add
-- up to that score: tee shot, approach, a chip or a bunker, one to three putts,
-- sometimes a ball in the water with its penalty stroke. The player farther
-- from the hole plays next, and the player with the lower score on the last
-- hole has the honour on the tee, as in the Rules of Golf.
--
-- Each hole is a small broadcast (the owner, 2026-09-24): the hole card; a
-- close-up of one shot, the player face-on with a real swing - a drive, a chip
-- or a bunker splash; the plan with every other shot; the last putt full
-- screen and the stand applauding whoever took fewer strokes. About one round
-- in ten has a hole-in-one on a par 3, with fireworks.
--
-- Everything on screen is a function of px.t(): nothing accumulates between
-- frames, so a slow frame never puts the game behind the clock. On the panel:
-- 15 fps, about 10 ms a frame.
--
-- PHOTOS: a private copy for the owner's panel sets PHOTOS before this line
-- (portraits in the introduction and the result); the public one draws the two
-- players as pixel golfers instead. See tools/luasim/scripts/private/.

PERIOD = 120
FPS = 15

local W, H = px.size()
local floor, sqrt, min, max, abs = math.floor, math.sqrt, math.min, math.max, math.abs

local INTRO, HOLE_S, HOLES = 6.0, 5.8, 18
-- Inside a hole: the card over the plan, the close-up of one shot full screen,
-- the plan with every other shot, then the last putt full screen and the
-- applause (the owner, 2026-09-24).
local CARD_END, SCENE_END, MAP_END, ROLL_END = 0.5, 1.8, 3.8, 5.0
local RESULT_AT = INTRO + HOLE_S * HOLES          -- 110.4 s; the result to 120

local NAMES = {"ГЕНА", "НИКОША"}
local COL = { {110, 170, 255}, {110, 235, 110} }    -- Гена blue, Никоша green

-- ---------------------------------------------------------------- the courses
-- Made by tools/luasim/golf_courses.py build; do not edit by hand. Each hole:
-- "par,metres,stroke index,fairway half-width,fairway from %,to %,water at
-- %,its offset in tenths of a pixel|the line
-- from the tee to the cup|the green|bunkers|water|trees", points two
-- characters (x/2, y), circles three (x/2, y, r).
COURSES = {}
-- COURSES BEGIN (tools/luasim/golf_courses.py build)
COURSES[#COURSES + 1] = {id = "old_course", name = "OLD COURSE", sub = "КАНН-МАНДЕЛЬЕ", holes = {
  "4,343,9,6,29,100,0,0|4aZSva|va3|ra2sS2vh2ab4||6R25Y2AQ2GK3KJ3NB3UC2YB2bD3eC3fJ3iB3iI3mD2mK2pC2qJ2uP2#C3#J3",
  "3,155,5,7,65,100,0,0|4WvW|uX7|kV4wM4||2B32I33P36D26K29C29e2Al2Cd2Gf3Gm3Ke3Kl3NB3Ok3QD2Qf2Rm2Ue2Ul2Yk2cm3fl3gs3ik3jr3",
  "5,421,11,2,24,100,0,0|4RKbvR|uS3|uR2sN24e28B32l2||2W33r36t2AQ2Al2EP2Dk2Er2HR3Gf3KC3KQ3OP3SR2UC2YP2bD3eC3fJ3iB3jP3mK2pC2sB2tI2wK3",
  "4,399,1,3,25,100,0,0|4ZgTvZ|uZ3|sa2uS20i2vn22n2tt2||3r36t2As2Er2Ht3Ks3fl3id3jr3mK2mf2mm2mt2qJ2qQ2ql2uP2xR3wf3xt3zX3#l3",
  "3,104,17,7,51,100,0,0|4WvW|wX9|eP4tJ4||2B32I32k33r36K26m26t2AJ2Al2As2DI2Dk2Er2GK3Gf3Gm3KC3NB3OI3QD2Rm2St2UC2Vs2Yr2ct3",
  "3,187,3,6,72,100,0,0|4WvW|uW6|tP3ad4wi4aG3Cr4||9e2Cd2GY3Gf3Ke3Kl3Nd3Ok3Qf2Ue2Ul2Vs2Yk2Yr2cm3ct3gs3mf2mt2ql2qs2ur2xt3#Q3#e3#l3",
  "4,349,13,4,28,100,0,0|4XcVvX|vY3|rW2wT2sc2cf28L3Ms24C2||3P32W32d36R26f2AJ2AQ2Al2CB2EP2Dk2GD3GK3Gm3KJ3Kl3OI3Nd3Qf2Ue2gs3jr3qs2wf3zX3#e3",
  "4,248,15,5,42,100,0,0|4YeUvY|vY5|ua2SS4sQ3||2d32k36R26m26t29e2Cd2Gf3Gm3Ke3Ks3Ok3Or3Qf2St2UJ2Vs2Yk2bf3cm3fl3jr3ql2qs2ur2#e3",
  "5,450,7,4,32,100,0,0|4MSgkVvM|vM3|oR2uJ2kP2ch2Qo25C2#I2St26g2mB2||2I36K26m2AJ2DI2CW2Cd2HR3Gm3KJ3Ks3SR2VQ2YP2fJ3gs3iI3mD2mK2mt2sW2ur2xR3wm3xt3#l3",
  "4,386,2,3,71,100,0,0|4WiWvW|vW3|eW3Na2mR2KQ22d24N27j21i2Hj2uJ2|$s2|2B36R26t29e2EP2GK3KC3Ke3OI3RK2UC2Ue2YI2Yk2bf3fJ3fl3iI3ik3mf2qQ2qs2sd2xR3wm3#Q3",
  "5,420,16,3,28,100,0,0|4eSOve|ve3|oa2sf2ua2eR2oV2eb2$l2Yl2Iq3iA2|1P34P36P38P3EK3GK3IK3LF3OA3CM2|2W32k35Y2AQ28X2EP2Gf3Ke3OI3QY2UJ2Ue2YI2cK3eC3fJ3iB3mD2mf2mt2qQ2tI2ur2wD3xR3#J3",
  "4,272,14,5,38,100,0,0|4ScavS|wS4|sV4Md4Al3||2I33P33r36f26m2AQ2DI2Cd2GK3Gf3KJ3Ks3OI3RK2UJ2VQ2YB2Yr2ct3eC3gs3jr3pC2ql2tk2wf3",
  "5,476,6,4,22,100,95,38|4dSPkRvd|ud3|wf2vZ2UV3Mi3Ik2Io2Kp2Um2Nr2|1A31F31K34A34F36A36F38A3BA3EA3YU3aU3cU3cZ3fZ3iZ3ie3kZ3ke3me3pe3se3sj3uj3wj3$o3|2k36m2As2Yd2bf3ee3mt2",
  "4,326,12,5,23,100,0,0|4ZmTvZ|vZ4|sT3xU2uf4ib3oM3zc2zW25l2|1A34U36P36e38K38P38U38j3Bj3Bo3Ej3Eo3Gj3Go3Ij3Io3Lj3Lo3Oj3Oo3Qo3So3|DI2GD3GK3KJ3NB3OI3QD2Qf2UC2UJ2Ue2YI2Yk2bf3cm3ct3ee3",
  "5,477,4,4,0,100,0,0|4RXbvR|uR3|uW2PR3EM2GN2xb4KM3uf4EH2yh2wk2|zA3$o3#s3|2W32k33r36m29e2Cd2Gm3Ht3Kl3Ok3Rm2Vs2Yk2Yr2cR3cm3gQ3fl3gs3jr3mK2mt2qJ2pe2sB2tI2",
  "3,134,18,7,72,100,0,0|4WvW|uV9|aY4oQ4iO4kh4wK4Ys4||",
  "3,157,8,7,63,100,0,0|4WvW|uW8|mh4yJ4||2k33r36f26m26t2Al2As2Dk2Er2Gm3Ht3Kl3Ks3Or3St2Vs2Yr2ct3gs3jr3mt2qs2",
  "4,351,10,6,27,100,95,30|4WXWvW|vV4|7Q28j22F2|sZ3ue3wZ3|",
}}
COURSES[#COURSES + 1] = {id = "pestovo", name = "ПЕСТОВО", sub = "ГОЛЬФ-КЛУБ", holes = {
  "4,373,5,7,19,85,35,-3|4QFcQXaTkYvQ|vQ6|ob2uX3oh2iJ4|LU3LZ3Oj3|6j3MW3wH2",
  "4,272,13,7,19,82,25,-9|4aFdOUYPjPva|va6|sV3mV2uh2sN2uP3iC2mj2qE2mB2|IK3IP3IU3IZ3Ie3Ij3Io3LK3LP3LU3LZ3Le3Lj3Lo3OK3OP3OU3OZ3Oe3Oj3Oo3QK3QP3QU3QZ3Qe3Qj3Qo3SP3SU3SZ3Se3Sj3So3VU3VZ3Ve3Vj3Ye3|1r3",
  "5,486,9,7,25,78,0,0|4IEOMaUjfkvI|vI6|uK2sR2qK3cd3||5V36c3CB2Mr3",
  "3,192,11,0,0,0,35,64|4qEeOPXCkZvq|vq7|no4|OZ3Oe3Oj3Oo3QU3QZ3Qe3Qj3Qo3SU3SZ3Se3Sj3So3VZ3Ve3Vj3Vo3Yj3Yo3aj3ao3ce3cj3co3fo3|wV2",
  "4,411,1,7,17,79,0,0|4kEeNUXMhIvk|vk6|kH2sV2us3rQ2|ke3|1r3Yd2",
  "4,377,15,7,18,85,0,0|4QETPQaWkcvQ|vQ6|uN4mp4|4A36A38A3BA3BF3BK3BP3BU3EF3|",
  "4,406,3,7,19,83,0,0|4QETPUZWjcvQ|vQ6|sX3lS2jM3||2I32W36c39e2Cd2",
  "3,181,7,0,0,0,70,-1|4dEcPkallHvd|vd7|vS2ul2sH3pA3|LU3OK3OP3OU3OZ3QU3QZ3Qe3SZ3Se3Sj3So3VZ3Ve3Vj3Vo3YZ3Ye3Yj3Yo3aU3aZ3ae3aj3ao3cP3cU3cZ3ce3cj3co3fP3fU3fZ3fe3fj3fo3iP3iU3iZ3ie3ij3io3|1P3AJ28X2",
  "5,507,17,7,18,84,0,0|4dEYOVZPkTvd|vd6|uf2qd2sQ4hH3||8Q2Ke3",
  "5,491,12,7,19,85,0,0|4WEOPXabkevW|vW6|ua2sT2ir3||4O3Gj2",
  "4,382,16,7,26,84,50,-2|4dEVPcZPkQvd|vd6|sV4li4|IZ3LP3LU3LZ3OP3OU3OZ3QP3QU3QZ3SU3SZ3Se3Sj3VU3VZ3Ve3Vj3Ye3Yj3aj3|4O34q3XW2",
  "4,383,2,7,18,85,0,0|4WEVPWaRkbvW|vW6|qY4gL3||2I32d36H34O36j3AJ2CP2Dk2",
  "3,185,18,0,0,0,55,48|4bEcPiablKvb|vb7||Yo3aj3ao3ce3cj3co3fZ3fe3fj3fo3ie3ij3io3|2W32d32k34O34q3AJ28s2",
  "4,374,4,7,21,85,0,0|4iEQPQaKkYvi|vi6|cl4|Gj3Go3IZ3Ie3Ij3Io3LZ3Le3Lj3Lo3OZ3Oe3Oj3Oo3QZ3Qe3Qj3Qo3Se3Sj3So3Vj3Vo3|6H34O3UX2Ue2",
  "5,533,8,7,19,76,0,0|4LDQKaShefvL|vL6|uM2oY2dZ3Uq2||6H3AJ2DI2CW2IQ3WP2",
  "4,423,14,7,18,85,40,0|4dEWQPackbvd|vd6|uj2kn2|8o3Bo3Eo3Ij3LK3LP3LU3LZ3Le3Lj3OK3OP3OU3OZ3Oe3Oj3QP3QU3QZ3Qe3Qj3|2W34O34q3KC3",
  "3,199,10,0,0,0,0,0|4cEZOUZQkZvc|vc7|wm3sm4qK2sI4||1P3QA3UC2",
  "4,375,6,7,30,84,0,0|4SETPUZZkavS|vS6|wK2oi4tG2uF2||2I3",
}}
-- COURSES END

-- ---------------------------------------------------------------- drawing
local function R(x, y, w, h, r, g, b) px.rect(floor(x), floor(y), floor(w), floor(h), floor(r), floor(g), floor(b), true) end
local function C(x, y, rad, r, g, b) px.circle(floor(x), floor(y), floor(rad), floor(r), floor(g), floor(b), true) end
local function P(x, y, r, g, b) px.pixel(floor(x), floor(y), floor(r), floor(g), floor(b)) end
local function T(x, y, s, c, font) px.text(floor(x), floor(y), s, c[1], c[2], c[3], font or "small") end
local function TW(s, font) return px.width(s, font or "small") end

-- ---------------------------------------------------------------- random
-- xorshift32 on Lua's integers; math.random is seeded differently in the
-- simulator and on the panel.
local seed = 1
local function rnd()
  seed = seed ~ (seed << 13)
  seed = seed ~ (seed >> 17)
  seed = seed ~ (seed << 5)
  return (seed & 0x7fffffff) / 2147483648.0
end
local function pick(weights)
  local total = 0
  for _, w in ipairs(weights) do total = total + w end
  local x, acc = rnd() * total, 0
  for i, w in ipairs(weights) do acc = acc + w; if x < acc then return i end end
  return #weights
end

-- ---------------------------------------------------------------- the course
-- One hole on screen: tee on the left at x 8, the cup on the right at x 114,
-- play between y 9 and 55 (the score above, the time and messages below).
local B64 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz#$"
local DEC = {}
for i = 1, #B64 do DEC[B64:byte(i)] = i - 1 end

local function circles(s)
  local t = {}
  for i = 1, #s - 2, 3 do
    t[#t + 1] = {DEC[s:byte(i)] * 2, DEC[s:byte(i + 1)], DEC[s:byte(i + 2)]}
  end
  return t
end

-- a hole's fixed shape, decoded once per course
local function decode_hole(row)
  local f = {}
  for part in (row .. "|"):gmatch("([^|]*)|") do f[#f + 1] = part end
  local nums = {}
  for v in f[1]:gmatch("[^,]+") do nums[#nums + 1] = tonumber(v) end
  local h = {par = nums[1], len = nums[2], si = nums[3], fw = nums[4], fw0 = nums[5] / 100, fw1 = nums[6] / 100}
  -- the water that can catch a ball, worked out by golf_courses.py
  h.water_near = (nums[7] or 0) > 0
  if h.water_near then h.wf, h.woff = nums[7] / 100, nums[8] / 10 end
  local pts, cum = {}, {0}
  for i = 1, #f[2] - 1, 2 do pts[#pts + 1] = {DEC[f[2]:byte(i)] * 2, DEC[f[2]:byte(i + 1)]} end
  for i = 2, #pts do
    local dx, dy = pts[i][1] - pts[i - 1][1], pts[i][2] - pts[i - 1][2]
    cum[i] = cum[i - 1] + sqrt(dx * dx + dy * dy)
  end
  h.pts, h.cum, h.total = pts, cum, cum[#cum]
  h.tx, h.ty = pts[1][1], pts[1][2]
  h.gx, h.gy = pts[#pts][1], pts[#pts][2]
  h.green = circles(f[3])[1]
  h.bunkers, h.water, h.trees = circles(f[4]), circles(f[5]), circles(f[6])
  return h
end

local decoded = {}
local function course_of(i)
  if not decoded[i] then
    local c = COURSES[i]
    local holes, par = {}, 0
    for n, row in ipairs(c.holes) do holes[n] = decode_hole(row); par = par + holes[n].par end
    decoded[i] = {id = c.id, name = c.name, sub = c.sub, holes = holes, par = par}
  end
  return decoded[i]
end

-- the point at fraction f of the way from tee to cup, along the line, and
-- the lateral offset off (positive to the player's right)
local function along(h, f, off)
  f = max(0, min(1, f))
  local d, pts, cum = f * h.total, h.pts, h.cum
  local i = 1
  while i < #pts - 1 and cum[i + 1] < d do i = i + 1 end
  local a, b = pts[i], pts[i + 1]
  local seg = cum[i + 1] - cum[i]
  local k = (seg > 0) and (d - cum[i]) / seg or 0
  local dx, dy = b[1] - a[1], b[2] - a[2]
  local n = sqrt(dx * dx + dy * dy); if n < 1e-6 then n = 1 end
  return a[1] + dx * k - dy / n * (off or 0), a[2] + dy * k + dx / n * (off or 0)
end

-- A round's copy of a hole: the fixed shape plus this round's play. Which
-- water can catch a ball comes with the course data (golf_courses.py works
-- it out once; on the panel it was half a second at the start of a round).
local function make_hole(base)
  local h = {}
  for k, v in pairs(base) do h[k] = v end
  return h
end

-- ---------------------------------------------------------------- a score
-- A hole's score against par for an amateur of handicap hcp: weights for
-- eagle, birdie, par, bogey, double, triple. Our model of club golf, not a
-- published table: about hcp/18 + 0.1 over par a hole on average.
-- The stroke index (1 the hardest hole, 18 the easiest) moves a few pars to
-- bogeys and back: our choice of size, not a published figure.
local function hole_diff(hcp, par, si)
  local k = (9.5 - (si or 9.5)) * 0.006
  local w = {
    (par == 5) and 0.012 or 0.002,
    max(0.03, 0.17 - 0.008 * hcp),
    max(0.25, 0.56 - 0.017 * hcp - k),
    0.27 + 0.006 * hcp + k,
    0.04 + 0.009 * hcp,
    0.008 + 0.003 * hcp,
  }
  return pick(w) - 3        -- -2 eagle .. +3 triple
end

-- The shots that add up to a score: a list of {f, off, kind} positions after
-- each stroke, f the fraction of the hole covered, off the miss sideways.
local function lay_shots(h, strokes)
  local shots, pen = {}, false
  if strokes == 1 then                                   -- a hole-in-one
    shots[1] = {f = 1, off = 0, kind = "ace"}
    return shots, false
  end
  local putts = (strokes == 2) and 1 or pick({0.25, 0.62, 0.13})
  local full = strokes - putts
  if full < 1 then full, putts = 1, strokes - 1 end
  -- a ball in the water costs a stroke: only on a hole with water, and only
  -- when the score has strokes to spare
  if h.water_near and full >= h.par and rnd() < 0.5 then pen = true end
  local pos = 0
  for i = 1, full do
    local kind, off
    if i == full then
      -- the last full shot finds the green, or a bunker beside it on a bad hole
      pos = 0.93 + rnd() * 0.05
      off = (rnd() - 0.5) * 6
      kind = "green"
    elseif i == full - 1 and full >= 3 then
      -- a green missed in regulation: this one stops short or beside it, and
      -- the next is a chip (or a splash out of a bunker)
      pos = 0.82 + rnd() * 0.07
      off = (rnd() - 0.5) * 10
      kind = "rough"
    else
      local left = full - i + 1
      local prev = pos
      if i == 1 and h.par >= 4 and h.len then
        -- the drive: 190-250 m for club players, one in ten a mishit of 120-170
        local d = (rnd() < 0.1) and (120 + rnd() * 50) or (190 + rnd() * 60)
        pos = min(0.8, d / h.len)
      else
        pos = pos + (0.93 - pos) / left * (0.8 + rnd() * 0.4)
        if h.len then pos = min(pos, prev + (170 + rnd() * 50) / h.len) end   -- a fairway wood at most
      end
      off = (rnd() - 0.5) * 12
      kind = (abs(off) > 4) and "rough" or "fairway"
      if pen and i == 1 then kind = "water"; pos = h.wf or pos; off = h.woff or 0 end
    end
    shots[#shots + 1] = {f = pos, off = off, kind = kind}
  end
  if pen then
    -- the drop after the water is the same place, played again: the penalty
    -- stroke is the extra count, not a shot
    table.insert(shots, 2, {f = shots[1].f - 0.04, off = 4, kind = "drop"})
    table.remove(shots, #shots)                            -- keep the total
    shots[#shots].kind = "green"; shots[#shots].f = 0.95
  end
  for i = 1, putts do
    local left = 1 - pos
    if i == putts then pos = 1 else pos = pos + left * (0.6 + rnd() * 0.3) end
    shots[#shots + 1] = {f = pos, off = (i == putts) and 0 or (rnd() - 0.5) * 2, kind = "putt"}
  end
  return shots, pen
end

local WORD = {[-3] = "АЛЬБАТРОС!", [-2] = "ИГЛ!", [-1] = "БЕРДИ!", [0] = "ПАР",
              [1] = "БОГИ", [2] = "ДАБЛ-БОГИ", [3] = "ТРИПЛ"}

-- ---------------------------------------------------------------- a round
local round, round_id = nil, -1

local function make_round(id)
  seed = id * 69069 + 12345              -- wraps in Lua's 32-bit integers, as it should
  if seed == 0 then seed = 1 end
  for _ = 1, 8 do rnd() end
  -- the course: the one COURSE names, or each in turn, one a round
  local ci = id % #COURSES + 1
  if COURSE then for i, c in ipairs(COURSES) do if c.id == COURSE then ci = i end end end
  local course = course_of(ci)
  local g = {hcp = {6 + floor(rnd() * 11), 6 + floor(rnd() * 11)}, holes = {},
             total = {0, 0}, topar = {0, 0}, birdies = {0, 0}, course = course}
  local honour = 1 + floor(rnd() * 2)
  -- A hole-in-one in about one round of ten (the owner's number): on one of
  -- the par 3s, by one of the two. No other way to an ace.
  local ace
  if rnd() < 0.1 or FORCE_ACE then       -- FORCE_ACE: a test hook, never set on the panel
    local threes = {}
    for n = 1, HOLES do if course.holes[n].par == 3 then threes[#threes + 1] = n end end
    ace = {hole = threes[1 + floor(rnd() * #threes)], pl = 1 + floor(rnd() * 2)}
  end
  g.ace = ace
  for n = 1, HOLES do
    local h = make_hole(course.holes[n])
    h.n = n
    h.course_id = course.id
    h.mpp = h.len / h.total              -- metres in one pixel of the plan
    h.p = {}
    for pl = 1, 2 do
      local d = hole_diff(g.hcp[pl], h.par, h.si)
      if h.par == 3 and d <= -2 then d = -1 end                         -- -2 on a par 3 is an ace: only as below
      if ace and ace.hole == n and ace.pl == pl then d = -2 end
      local strokes = h.par + d
      local shots, pen = lay_shots(h, strokes)
      h.p[pl] = {strokes = strokes, diff = d, shots = shots, pen = pen}
    end
    -- the order of play: the honour tees off first; then whoever is farther
    -- from the hole plays, until both are in
    local order, at, done = {}, {0, 0}, {false, false}
    local cur = {0, 0}           -- how far each ball has come (fraction)
    local first = honour
    while not (done[1] and done[2]) do
      local pl
      if at[1] == 0 and at[2] == 0 then pl = first
      elseif at[1] == 0 then pl = 1
      elseif at[2] == 0 then pl = 2
      elseif done[1] then pl = 2
      elseif done[2] then pl = 1
      else pl = (cur[1] <= cur[2]) and 1 or 2 end
      at[pl] = at[pl] + 1
      local s = h.p[pl].shots[at[pl]]
      order[#order + 1] = {pl = pl, i = at[pl], from = cur[pl], s = s}
      cur[pl] = s.f
      if at[pl] >= #h.p[pl].shots then done[pl] = true end
    end
    h.order = order
    -- The close-up of the hole (the owner: real insets, not only the plan):
    -- the ace when there is one; otherwise a drive on odd holes and, on even
    -- ones, a chip - out of a bunker four times in ten - when anyone plays one.
    h.bunker = rnd() < 0.4
    h.dist = 0
    if ace and ace.hole == n then
      h.scene = {kind = "ace", pl = ace.pl}
    else
      local chip
      if n % 2 == 0 then
        for _, ev in ipairs(order) do
          if not chip and ev.from >= 0.7 and ev.s.kind ~= "putt" and ev.from < 0.97 then chip = ev end
        end
      end
      if chip then
        h.scene = {kind = h.bunker and "bunker" or "chip", pl = chip.pl}
      else
        h.scene = {kind = "drive", pl = order[1].pl}
        h.dist = floor(h.len * min(1, order[1].s.f))
      end
    end
    h.final = order[#order]
    -- honour on the next tee: the lower score here; a tie keeps it
    if h.p[1].strokes < h.p[2].strokes then honour = 1
    elseif h.p[2].strokes < h.p[1].strokes then honour = 2 end
    g.holes[n] = h
    for pl = 1, 2 do
      g.total[pl] = g.total[pl] + h.p[pl].strokes
      g.topar[pl] = g.topar[pl] + h.p[pl].diff
      if h.p[pl].diff <= -1 then g.birdies[pl] = g.birdies[pl] + 1 end
    end
  end
  return g
end

local function topar_s(d)
  if d == 0 then return "E" elseif d > 0 then return "+" .. d else return "-" .. (-d) end
end

-- ---------------------------------------------------------------- players
-- A pixel golfer in the player's colours: cap, face, shirt; or the portrait
-- when a private copy supplied PHOTOS.
local function avatar(x, y, pl)
  if PHOTOS and PHOTOS[pl] then
    local p = PHOTOS[pl]
    if not p.rgb then                      -- decoded once, not every frame
      -- into a local first: a frame cut short by the time budget in the
      -- middle of this loop must not leave half a portrait behind for the
      -- next frame to draw from (it did: "bad argument #4 to 'pixel'")
      local rgb = {}
      for i = 1, #p.data, 2 do rgb[#rgb + 1] = tonumber(p.data:sub(i, i + 1), 16) end
      p.rgb = rgb
    end
    local rgb, w, k = p.rgb, p.w, 1
    for yy = 0, p.h - 1 do
      for xx = 0, w - 1 do
        px.pixel(x + xx, y + yy, rgb[k], rgb[k + 1], rgb[k + 2])
        k = k + 3
      end
    end
    return p.w, p.h
  end
  local c = COL[pl]
  local skin = {235, 180, 140}
  local cap = (pl == 1) and {40, 60, 150} or {40, 140, 90}
  R(x + 6, y + 16, 12, 12, c[1] // 2, c[2] // 2, c[3] // 2)        -- shirt
  R(x + 7, y + 17, 10, 11, c[1], c[2], c[3])
  C(x + 12, y + 10, 5, skin[1], skin[2], skin[3])                    -- face
  R(x + 7, y + 3, 11, 4, cap[1], cap[2], cap[3])                    -- cap
  R(x + (pl == 1 and 16 or 5), y + 6, 4, 1, cap[1], cap[2], cap[3])  -- peak
  P(x + 10, y + 10, 40, 30, 30); P(x + 14, y + 10, 40, 30, 30)       -- eyes
  R(x + 11, y + 13, 3, 1, 150, 70, 60)                               -- smile
  if pl == 2 then R(x + 8, y + 13, 9, 3, 90, 60, 40) end             -- Никоша's beard
  R(x + 19, y + 12, 1, 16, 200, 200, 200)                            -- the club
  R(x + 18, y + 27, 3, 1, 220, 220, 220)
  return 24, 30
end

-- ---------------------------------------------------------------- the clock
local function draw_clock()
  local n = px.now()
  local s = string.format("%02d:%02d", n.hour, n.min)
  local w = TW(s)
  R(W - w - 3, H - 8, w + 3, 8, 0, 0, 0)
  T(W - w - 1, H - 7, s, {230, 230, 230})
end

-- the score line: name and to-par for each, the hole in the middle
local function draw_score(g, upto, n, h)
  R(0, 0, W, 8, 0, 0, 0)
  local s1 = NAMES[1] .. " " .. topar_s(upto[1])
  local s2 = topar_s(upto[2]) .. " " .. NAMES[2]
  T(1, 1, s1, COL[1])
  T(W - TW(s2) - 1, 1, s2, COL[2])
  local mid = n and (n .. "/18 П" .. h.par) or ""
  T((W - TW(mid)) // 2, 1, mid, {255, 200, 60})
end

-- ---------------------------------------------------------------- the world
-- Each hole becomes ground you can stand on. The map above is in screen
-- pixels (the tee at x 8, the cup at x 114); the world is in metres with the
-- tee at the origin, X towards the green, Y to the player's right, Z up.
-- A pixel of the map is the hole's scorecard length over its drawn length.
local sin, cos, atan, exp = math.sin, math.cos, math.atan, math.exp
local function clamp(v, a, b) if v < a then return a elseif v > b then return b end return v end
local function mix(a, b, t) return a + (b - a) * t end

-- The look of each course: its grass, sand and water, its trees and what
-- stands on its horizon.
local STYLE = {
  old_course = {                         -- the Riviera in September: dry, bright, pines
    top = {38, 98, 196}, hor = {168, 204, 236}, haze = {178, 196, 212},
    rough = {86, 124, 50}, cut = {100, 148, 58}, fair = {108, 166, 62}, green = {104, 190, 74},
    fringe = {96, 172, 64}, sand = {236, 222, 182}, water = {38, 92, 128}, deep = {26, 64, 96},
    tee = {100, 172, 66}, far = {58, 84, 46}, ridge = {132, 92, 110}, ridge2 = {104, 76, 98},
    trees = "pine", crowd = true,
    ferry = {[3] = true, [13] = true},   -- the Siagne between 2 and 3, and back between 12 and 13
    river = "СИАНЬ",
    house = {wall = {236, 222, 196}, roof = {176, 78, 52}, win = {60, 70, 90}},   -- the 1891 clubhouse
  },
  pestovo = {                            -- the Moscow region: lush, spruce and birch
    top = {66, 124, 206}, hor = {192, 214, 234}, haze = {186, 204, 216},
    rough = {60, 120, 50}, cut = {76, 148, 60}, fair = {84, 168, 68}, green = {96, 198, 80},
    fringe = {86, 178, 70}, sand = {230, 210, 156}, water = {44, 84, 122}, deep = {30, 58, 90},
    tee = {90, 178, 72}, far = {32, 66, 44}, ridge = {40, 72, 64}, ridge2 = {30, 58, 52},
    trees = "spruce", crowd = true,
    house = {wall = {120, 84, 60}, roof = {60, 64, 72}, win = {150, 190, 220}},   -- timber and glass
  },
}

local frame_no = 0

-- ---------------------------------------------------------------- the ground
-- A grid of ground cells for one hole, as three strings of a byte a cell -
-- height, kind of ground, light - which px.terrain draws natively in a few
-- milliseconds. Lua builds it in slices, a few rows a frame, while the hole
-- before it plays: the whole grid is about a million instructions, and the
-- panel runs one in 410 ns.
local SUN = {-0.45, -0.35, 0.82}           -- from the front left, high
local HBASE, HSCALE = -2.0, 0.05           -- a height byte: -2 m .. +10.75 m
local K_ROUGH, K_CUT, K_FAIR, K_FRINGE, K_GREEN, K_SAND, K_WATER, K_TEE = 0, 1, 2, 3, 4, 5, 6, 7
local grid = nil                           -- the grid being drawn and read

local function to_world(h, x, y) return (x - h.tx) * h.mpp, (y - h.ty) * h.mpp end

local function world_of(h)
  if h.world then return h.world end
  local wp = {}
  for i, p in ipairs(h.pts) do local x, y = to_world(h, p[1], p[2]); wp[i] = {x, y} end
  local cum = {0}
  for i = 2, #wp do cum[i] = cum[i - 1] + sqrt((wp[i][1] - wp[i - 1][1]) ^ 2 + (wp[i][2] - wp[i - 1][2]) ^ 2) end
  local function circ(list, s)
    local out = {}
    for i, c in ipairs(list) do local x, y = to_world(h, c[1], c[2]); out[i] = {x, y, c[3] * h.mpp * (s or 1)} end
    return out
  end
  local gx, gy = to_world(h, h.green[1], h.green[2])
  local w = {
    line = wp, cum = cum, len = cum[#cum],
    green = {gx, gy, max(5, h.green[3]) * h.mpp * 0.9},
    cup = {wp[#wp][1], wp[#wp][2]},
    bunkers = circ(h.bunkers, 0.9), water = circ(h.water, 1.05), trees = circ(h.trees),
    fw = h.fw * h.mpp,
  }
  local seg = {}                           -- the segments, ready for every cell's distance test
  for i = 1, #wp - 1 do
    local ax, ay = wp[i][1], wp[i][2]
    local dx, dy = wp[i + 1][1] - ax, wp[i + 1][2] - ay
    seg[i] = {ax, ay, dx, dy, max(1e-6, dx * dx + dy * dy), cum[i], cum[i + 1] - cum[i]}
  end
  w.seg = seg
  local sf = {}
  for _, g in ipairs(seg) do for k = 1, 7 do sf[#sf + 1] = g[k] end end
  w.segf = sf
  h.world = w
  return w
end

-- the distance from the centre line and how far along it (0..1)
local function line_pos(w, x, y)
  local best, bf = 1e9, 0
  local sf = w.segf                         -- seven numbers a segment, flat: fewer lookups
  for i = 1, #sf, 7 do
    local ax, ay, dx, dy = sf[i], sf[i + 1], sf[i + 2], sf[i + 3]
    local t = ((x - ax) * dx + (y - ay) * dy) / sf[i + 4]
    if t < 0 then t = 0 elseif t > 1 then t = 1 end
    local ex, ey = x - ax - t * dx, y - ay - t * dy
    local d = ex * ex + ey * ey
    if d < best then best, bf = d, sf[i + 5] + t * sf[i + 6] end
  end
  return sqrt(best), bf / w.len
end

-- the course's grounds for px.terrain: colour, pattern, period, amount
local function kinds_of(st)
  if not st.kinds then
    local function k(c, pat, per, amt) return string.char(c[1], c[2], c[3], pat, per, amt) end
    st.kinds = k(st.rough, 3, 1, 8) .. k(st.cut, 0, 1, 0) .. k(st.fair, 1, 9, 7) .. k(st.fringe, 0, 1, 0)
            .. k(st.green, 2, 3, 5) .. k(st.sand, 3, 1, 4) .. k(st.water, 4, 1, 0) .. k(st.tee, 2, 3, 5)
  end
  return st.kinds
end

local function grid_new(h, st)
  local w = world_of(h)
  local L = w.len
  local cell = clamp(h.mpp * 1.0, 2.2, 4.0)
  local half = 0.2 * L + 40
  local gr = {h = h, st = st, x0 = -50, y0 = -half, cell = cell,
              nx = floor((L + 110) / cell) + 1, ny = floor(2 * half / cell) + 1,
              rows = {{}, {}, {}}, j = 0}
  -- every round thing the ground has, in the order a cell takes them: water,
  -- then the green and its collar over it, the tee, sand (never on the
  -- green), and the shade the trees throw away from the sun
  local g = w.green
  local c = {}
  for _, wa in ipairs(w.water) do c[#c + 1] = {wa[1], wa[2], wa[3], "water"} end
  c[#c + 1] = {g[1], g[2], g[3] + 2.5, "green", g[3]}
  c[#c + 1] = {0, 0, 6, "tee"}
  for _, bk in ipairs(w.bunkers) do c[#c + 1] = {bk[1], bk[2], bk[3], "sand"} end
  for _, t in ipairs(w.trees) do c[#c + 1] = {t[1] + 3, t[2] + 2.5, t[3] * 2.2 + 2, "shade"} end
  gr.circles = c
  -- the column sines of the swells, once a grid
  local ph = (h.n or 1) * 1.7
  local S1, SA, CA = {}, {}, {}
  for i = 0, gr.nx - 1 do
    local x = gr.x0 + i * gr.cell
    S1[i], SA[i], CA[i] = sin(x * 0.041 + ph), sin(x * 0.013), cos(x * 0.013)
  end
  gr.S1, gr.SA, gr.CA = S1, SA, CA
  gr.A, gr.B, gr.M = {j = -9, d = {}, f = {}}, {j = -9, d = {}, f = {}}, {d = {}, f = {}}
  return gr
end

-- a few rows of the grid, straight into the byte strings; true when finished
-- one row's distances into buf: every other column worked out, the rest halved
local function fill_row(gr, w, buf, j)
  local x0, cell, nx = gr.x0, gr.cell, gr.nx
  local y = gr.y0 + j * cell
  local d, f = buf.d, buf.f
  for i = 0, nx - 1, 2 do d[i], f[i] = line_pos(w, x0 + i * cell, y) end
  if (nx - 1) % 2 == 1 then d[nx - 1], f[nx - 1] = line_pos(w, x0 + (nx - 1) * cell, y) end
  for i = 1, nx - 2, 2 do d[i], f[i] = (d[i - 1] + d[i + 1]) * 0.5, (f[i - 1] + f[i + 1]) * 0.5 end
  buf.j = j
end

local function grid_step(gr, cells)
  local h = gr.h
  local w = world_of(h)
  local x0, y0, cell, nx, ny = gr.x0, gr.y0, gr.cell, gr.nx, gr.ny
  local rows = max(1, cells // nx)
  local ph = (h.n or 1) * 1.7
  local fw, fw0, fw1 = w.fw, h.fw0, h.fw1
  local hr, kr, lr = gr.rows[1], gr.rows[2], gr.rows[3]
  local hb, kb, lb = {}, {}, {}
  for j = gr.j, min(ny - 1, gr.j + rows - 1) do
    local y = y0 + j * cell
    local here = {}                          -- the round things this row crosses
    for _, ci in ipairs(gr.circles) do
      if abs(ci[2] - y) <= ci[3] then here[#here + 1] = ci end
    end
    -- The distance to the line, the dear part of a cell (a segment at a
    -- time), is worked out at every other cell of every other row and
    -- averaged between: a distance field is smooth, and a cell is 2-4 m. The
    -- swells come from sines laid out once a grid by column and once a row
    -- (sin(a + b) = sa cb + ca sb).
    local R
    if j % 2 == 0 or j == ny - 1 then
      if gr.B.j == j then gr.A, gr.B = gr.B, gr.A else fill_row(gr, w, gr.A, j) end
      R = gr.A
    else
      if gr.A.j ~= j - 1 then fill_row(gr, w, gr.A, j - 1) end
      fill_row(gr, w, gr.B, j + 1)
      local a, b, m = gr.A, gr.B, gr.M
      for i = 0, nx - 1 do
        m.d[i], m.f[i] = (a.d[i] + b.d[i]) * 0.5, (a.f[i] + b.f[i]) * 0.5
      end
      R = m
    end
    local dA, fA = R.d, R.f
    local cy = 0.9 * cos(y * 0.057 + ph * 0.7)
    local sb, cb = sin(y * 0.021 + ph), cos(y * 0.021 + ph)
    local S1, SA, CA = gr.S1, gr.SA, gr.CA
    for i = 0, nx - 1 do
      local x = x0 + i * cell
      local d, f = dA[i], fA[i]
      local k = K_ROUGH
      local hh = S1[i] * cy + 0.6 * (SA[i] * cb + CA[i] * sb)
      if d > fw + 14 then hh = hh + min(5, 0.03 * (d - fw - 14) ^ 1.1) end
      if fw > 0 and f >= fw0 - 0.02 and f <= fw1 + 0.02 then
        if d < fw and f >= fw0 and f <= fw1 then k = K_FAIR elseif d < fw + 3 then k = K_CUT end
      end
      local lit = 128
      for n = 1, #here do
        local ci = here[n]
        local dx = x - ci[1]
        if dx <= ci[3] and dx >= -ci[3] then
          local dd = sqrt(dx * dx + (y - ci[2]) ^ 2)
          if dd <= ci[3] then
            local q = dd / ci[3]
            local what = ci[4]
            if what == "water" then k, hh = K_WATER, -0.9
            elseif what == "green" then
              k = (dd > ci[5]) and K_FRINGE or K_GREEN
              hh = hh * 0.3 + 0.7 * (1 - q * q)
            elseif what == "tee" then k, hh = K_TEE, 0.6
            elseif what == "sand" then
              if k ~= K_GREEN then k, hh = K_SAND, hh - 0.7 * (1 - q * q) end
            elseif k ~= K_WATER then lit = 92 end
          end
        end
      end
      local hv = floor((hh - HBASE) / HSCALE + 0.5)
      hb[i + 1] = (hv < 0) and 0 or (hv > 255) and 255 or hv
      kb[i + 1], lb[i + 1] = k, lit
    end
    hr[j + 1] = string.char(table.unpack(hb, 1, nx))
    kr[j + 1] = string.char(table.unpack(kb, 1, nx))
    lr[j + 1] = string.char(table.unpack(lb, 1, nx))
  end
  gr.j = gr.j + rows
  if gr.j < ny then return false end
  gr.pt = {w = nx, h = ny, cell = cell, x0 = x0, y0 = y0, hbase = HBASE, hscale = HSCALE,
           height = table.concat(hr), kind = table.concat(kr), light = table.concat(lr)}
  gr.rows, gr.circles = nil, nil
  gr.done = true
  return true
end

local function ground_at(x, y)
  local g = grid
  if not (g and g.pt) then return 0 end
  local i, j = floor((x - g.x0) / g.cell), floor((y - g.y0) / g.cell)
  if i < 0 or j < 0 or i >= g.nx or j >= g.ny then return 0 end
  return HBASE + HSCALE * g.pt.height:byte(j * g.nx + i + 1)
end

local function wet_at(x, y)
  local g = grid
  if not (g and g.pt) then return false end
  local i, j = floor((x - g.x0) / g.cell), floor((y - g.y0) / g.cell)
  if i < 0 or j < 0 or i >= g.nx or j >= g.ny then return false end
  return g.pt.kind:byte(j * g.nx + i + 1) == K_WATER
end

-- ---------------------------------------------------------------- the camera
-- cam: x, y, z (metres), yaw (radians, 0 along X), hor (the horizon's screen
-- row: the tilt), f (focal length in pixels).
local ZFAR = 900

local function look_at(cam, tx, ty, tz, row)
  cam.yaw = atan(ty - cam.y, tx - cam.x)
  local d = sqrt((tx - cam.x) ^ 2 + (ty - cam.y) ^ 2)
  cam.hor = row - (cam.z - tz) * cam.f / max(1, d)
  return cam
end

local function project(cam, x, y, z)
  local rx, ry = x - cam.x, y - cam.y
  local c, s = cos(cam.yaw), sin(cam.yaw)
  local depth = rx * c + ry * s
  if depth < 0.4 then return nil end
  local lat = -rx * s + ry * c
  local k = cam.f / depth
  return 63.5 + lat * k, cam.hor + (cam.z - z) * k, k, depth
end

-- ---------------------------------------------------------------- the sky

local function draw_sky(cam, st)
  local hor = floor(cam.hor)
  if hor <= 0 then return end
  local top, hz = st.top, st.hor
  local function skyc(y)
    local t = clamp(y / max(1, cam.hor), 0, 1) ^ 1.6
    return mix(top[1], hz[1], t), mix(top[2], hz[2], t), mix(top[3], hz[3], t)
  end
  local y0, pr, pg, pb = 0, -1, -1, -1
  for y = 0, min(H, hor + 1) do                  -- the gradient, in bands of one colour
    local r, g, b = -2, -2, -2
    if y <= min(H - 1, hor) then
      r, g, b = skyc(y)
      r, g, b = floor(r / 3) * 3, floor(g / 3) * 3, floor(b / 3) * 3
    end
    if r ~= pr or g ~= pg or b ~= pb then
      if pr >= 0 and y > y0 then px.rect(0, y0, W, y - y0, pr, pg, pb, true) end
      y0, pr, pg, pb = y, r, g, b
    end
  end
  -- the sun, fixed in the world behind the player's left shoulder
  local rel = ((-2.2 - cam.yaw + math.pi) % (2 * math.pi)) - math.pi
  if abs(rel) < 1.2 then
    local sx, sy = 63.5 + math.tan(rel) * cam.f, cam.hor - 26
    C(sx, sy, 6, mix(hz[1], 255, 0.35), mix(hz[2], 245, 0.35), mix(hz[3], 210, 0.35))
    C(sx, sy, 4, mix(hz[1], 255, 0.7), mix(hz[2], 245, 0.7), mix(hz[3], 215, 0.7))
    C(sx, sy, 2, 255, 250, 225)
  end
  -- clouds drifting: pale rows over the blue
  local drift = frame_no * 0.0006
  for c = 0, 5 do
    local rel2 = ((c * 1.05 + drift - cam.yaw + math.pi) % (2 * math.pi)) - math.pi
    if abs(rel2) < 0.9 then
      local cx = 63.5 + math.tan(rel2) * cam.f
      local cy = cam.hor - 10 - (c * 7) % 17
      for k = 0, 3 do
        local ox, oy, rr = (k - 1.5) * 4, ((k * 3) % 4) - 2, 3 + (k * 5) % 3
        local r, g, b = skyc(cy)
        r, g, b = floor(mix(r, 255, 0.28)), floor(mix(g, 255, 0.28)), floor(mix(b, 255, 0.28))
        for yy = -rr, rr, 2 do
          local y = floor(cy + oy + yy)
          if y >= 0 and y < hor - 1 then
            local half = floor(sqrt(max(0, (rr * rr - yy * yy * 1.6) / 0.7)))
            px.rect(floor(cx + ox - half), y, 2 * half + 1, 2, r, g, b, true)
          end
        end
      end
    end
  end
  -- what stands on the horizon: the course's own skyline, in runs of one height
  local function skyline(heightf, c)
    local run0, runh = 0, nil
    for col = 0, W, 2 do
      local hh = nil
      if col < W then hh = floor(heightf(cam.yaw + atan((col - 63.5) / cam.f))) end
      if hh ~= runh then
        if runh and runh > 0 then px.rect(run0, floor(cam.hor) - runh, col - run0, runh + 1, c[1], c[2], c[3], true) end
        run0, runh = col, hh
      end
    end
  end
  if st.trees == "pine" then                   -- the Estérel's red rock behind the pines
    skyline(function(a) return 5 + 4 * sin(a * 3 + 1) + 2.5 * sin(a * 7.3) + 1.5 * sin(a * 17) end, st.ridge)
    skyline(function(a) return 2 + 1.5 * sin(a * 23) + ((floor(a * 40) % 3 == 0) and 2 or 0) end,
            {st.ridge2[1] // 2, st.ridge2[2] // 2 + 10, st.ridge2[3] // 2})
  else                                         -- a spruce wall, tip after tip
    skyline(function(a) local tip = (a * 60) % 1; return 5 + 2 * sin(a * 5) + 3 * (1 - abs(tip - 0.5) * 2) end, st.ridge)
  end
end

-- ---------------------------------------------------------------- the land
-- Drawn natively (src/lua/px_terrain.h): every column walks out from the
-- camera and fills the ground that rises above what it already has.
-- One argument table for every frame: garbage made each frame is what the
-- collector has to walk, in PSRAM, and on the panel that shows as a stall.
local TP = {fog0 = 140, fogr = 900, farh = 4, sun = SUN, colw = 1, step = 1.04, zfar = ZFAR, grass = 60, bilinear = 80}
local function draw_land(cam, st)
  TP.grid, TP.cam, TP.kinds, TP.frame = grid.pt, cam, kinds_of(st), frame_no
  TP.haze, TP.far, TP.sky, TP.deep = st.haze, st.far, st.top, st.deep
  px.terrain(TP)
end

-- ---------------------------------------------------------------- things standing
-- a colour pulled towards the haze: three numbers, no table, no closure
local function fogged(r, g, b, l, fogt, hz)
  return floor(mix(r * l, hz[1], fogt)), floor(mix(g * l, hz[2], fogt)), floor(mix(b * l, hz[3], fogt))
end

local function draw_tree(cam, st, t, seedk)
  local gz = ground_at(t[1], t[2])
  local sx, sy, k, depth = project(cam, t[1], t[2], gz)
  if not sx or sx < -40 or sx > W + 40 or depth > ZFAR then return end
  local fogt = clamp((depth - 140) / 900, 0, 1) ^ 2
  local hz = st.haze
  local rect = px.rect
  if k < 0.35 then                          -- far off: a dab of dark green, 2-5 px tall
    local pine = st.trees == "pine"
    local th = max(2, floor((pine and 11 or 15) * k))
    local r, g, b = fogged(pine and 44 or 26, pine and 84 or 70, 40, 1, fogt, hz)
    rect(floor(sx), floor(sy - th), (k > 0.2) and 2 or 1, th, r, g, b, true)
    return
  end
  if st.trees == "pine" then            -- the umbrella pine: a bare trunk, a flat dark crown
    local th = (9 + (seedk % 4)) * k
    local tw = max(1, floor(0.5 * k))
    local r, g, b = fogged(110, 72, 44, 1, fogt, hz)
    rect(floor(sx - tw / 2), floor(sy - th), tw, floor(th) + 1, r, g, b, true)
    local cw, ch = (5 + seedk % 3) * k, 2.4 * k
    local cy = sy - th
    local lr, lg, lb = fogged(44, 84, 40, 1.25, fogt, hz)     -- the lit top of the crown
    local dr, dg, db = fogged(44, 84, 40, 0.8, fogt, hz)      -- its shaded underside
    local band = max(1, floor(ch / 5))      -- a close crown in bands, not a rect a row
    for yy = floor(-ch), floor(ch * 0.6), band do
      local q = (yy + band * 0.5) / ch
      local half = cw * sqrt(max(0, 1 - q * q))
      if yy < 0 then rect(floor(sx - half), floor(cy + yy), floor(2 * half) + 1, band, lr, lg, lb, true)
      else rect(floor(sx - half), floor(cy + yy), floor(2 * half) + 1, band, dr, dg, db, true) end
    end
    if k > 1.2 then                      -- a lit edge on the sun's side
      local r3, g3, b3 = fogged(92, 138, 62, 1, fogt, hz)
      rect(floor(sx - cw * 0.7), floor(cy - ch * 0.8), floor(cw * 0.6), 1, r3, g3, b3, true)
    end
  else                                  -- spruce, and now and then a birch
    if seedk % 5 == 0 then
      local th = 8 * k
      local r, g, b = fogged(230, 230, 225, 1, fogt, hz)
      rect(floor(sx), floor(sy - th), max(1, floor(0.35 * k)), floor(th) + 1, r, g, b, true)
      local rr = max(1, floor(3 * k))
      r, g, b = fogged(110, 158, 66, 1, fogt, hz)
      px.circle(floor(sx), floor(sy - th - rr * 0.6), rr, r, g, b, true)
      if rr > 2 then
        r, g, b = fogged(140, 186, 84, 1, fogt, hz)
        px.circle(floor(sx - rr * 0.3), floor(sy - th - rr), max(1, rr // 2), r, g, b, true)
      end
    else
      local th = (14 + (seedk % 5)) * k
      local bw = 3.4 * k
      local rows = max(1, floor(th))
      local band = max(1, rows // 10)          -- a close spruce in bands, not a rect a row
      -- three tones down the tree, and the lit left edge: worked out once
      local t1r, t1g, t1b = fogged(26, 70, 40, 1.05, fogt, hz)
      local t2r, t2g, t2b = fogged(26, 70, 40, 0.92, fogt, hz)
      local t3r, t3g, t3b = fogged(26, 70, 40, 0.82, fogt, hz)
      local er, eg, eb = fogged(50, 104, 60, 1, fogt, hz)
      local kk = max(1, floor(k))
      for yy = 0, rows, band do
        local q = yy / rows
        local half = bw * q * (0.85 + 0.15 * (((yy // kk) % 3) / 2))
        local x0, w0, y = floor(sx - half), floor(2 * half) + 1, floor(sy - th + yy)
        if q < 0.33 then rect(x0, y, w0, band, t1r, t1g, t1b, true)
        elseif q < 0.66 then rect(x0, y, w0, band, t2r, t2g, t2b, true)
        else rect(x0, y, w0, band, t3r, t3g, t3b, true) end
        if half > 1.5 then rect(x0, y, max(1, floor(half * 0.4)), band, er, eg, eb, true) end
      end
    end
  end
end

local function draw_flag(cam, x, y)
  local gz = ground_at(x, y)
  local sx, sy, k = project(cam, x, y, gz)
  if not sx then return end
  local ph = 2.3 * k
  px.line(floor(sx), floor(sy), floor(sx), floor(sy - max(3, ph)), 235, 235, 235)
  local fw, fh = max(2, floor(0.8 * k)), max(1, floor(0.5 * k))
  local wave = floor(sin(frame_no * 0.4) * 0.5 + 0.5)
  px.rect(floor(sx) + 1, floor(sy - max(3, ph)), fw, fh + wave, 235, 40, 40, true)
  if k > 6 then                           -- the cup, close up
    px.rect(floor(sx - 0.06 * k), floor(sy), max(2, floor(0.12 * k)), max(1, floor(0.03 * k)), 10, 10, 10, true)
  end
end

local function draw_ball3d(cam, x, y, z, pl, big)
  local gz = ground_at(x, y)
  local gx_, gy_, k = project(cam, x, y, gz)
  local bx, by = project(cam, x, y, gz + max(0, z) + 0.05)
  if not bx then return end
  if z > 0.3 and gx_ then px.pixel(floor(gx_), floor(gy_), 20, 40, 20) end   -- the shadow
  local c = COL[pl]
  local rr = max(0, floor(0.03 * k))
  if big and rr < 1 then                    -- far off: a stem over the ball, as the broadcasts mark it
    px.line(floor(bx), floor(by) - 2, floor(bx), floor(by) - 5, c[1], c[2], c[3])
  end
  if rr >= 1 then
    px.circle(floor(bx), floor(by), rr, 250, 250, 250, true)
  else
    if big then
      px.pixel(floor(bx) - 1, floor(by), c[1], c[2], c[3]); px.pixel(floor(bx) + 1, floor(by), c[1], c[2], c[3])
      px.pixel(floor(bx), floor(by) - 1, c[1], c[2], c[3]); px.pixel(floor(bx), floor(by) + 1, c[1], c[2], c[3])
    end
    px.pixel(floor(bx), floor(by), 255, 255, 255)
    if not big then
      px.pixel(floor(bx) + 1, floor(by), 235, 235, 235)
      px.pixel(floor(bx), floor(by) + 1, 170, 170, 170); px.pixel(floor(bx) + 1, floor(by) + 1, 150, 150, 150)
    end
  end
end

-- the ball's flight as the broadcasts draw it: a line behind the ball
local function tracer(cam, ax, ay, bx, by, apex, u, pl, putt)
  local c = COL[pl]
  local px0, py0
  local steps = 24
  for s = 0, steps do
    local q = s / steps * u
    local x, y = mix(ax, bx, q), mix(ay, by, q)
    local z = putt and 0 or 4 * apex * q * (1 - q)
    local gz = ground_at(x, y)
    local sx, sy = project(cam, x, y, gz + z + 0.05)
    if sx and px0 then
      px.line(floor(px0), floor(py0), floor(sx), floor(sy), floor(c[1] * 0.9), floor(c[2] * 0.9), floor(c[3] * 0.9))
    end
    px0, py0 = sx, sy
  end
end

-- the spectators behind a green: a stand of little people
local function draw_crowd(cam, cx, cy, dirx, diry, clap)
  local nxp, nyp = -diry, dirx
  local people, hands = {}, {}
  for i = 0, 17 do
    local off = (i - 8.5) * 1.5
    local back = 21 + (i % 3) * 1.6
    people[#people + 1] = {cx + dirx * back + nxp * off, cy + diry * back + nyp * off, i}
  end
  table.sort(people, function(a, b)
    local da = (a[1] - cam.x) ^ 2 + (a[2] - cam.y) ^ 2
    local db = (b[1] - cam.x) ^ 2 + (b[2] - cam.y) ^ 2
    return da > db
  end)
  for _, p in ipairs(people) do
    local dry = not wet_at(p[1], p[2])
    local gz = ground_at(p[1], p[2])
    if dry then
    local sx, sy, k = project(cam, p[1], p[2], gz)
    if sx and sx > -4 and sx < W + 4 then
      local i = p[3]
      local shirt = {(i * 71) % 200 + 40, (i * 37) % 170 + 60, (i * 53) % 200 + 40}
      local bh, hw = 1.7 * k, max(1, floor(0.25 * k))
      px.rect(floor(sx - hw), floor(sy - bh * 0.5), hw * 2, floor(bh * 0.5) + 1, 50, 50, 70, true)       -- legs
      px.rect(floor(sx - hw), floor(sy - bh * 0.85), hw * 2, floor(bh * 0.38) + 1, shirt[1], shirt[2], shirt[3], true)
      px.circle(floor(sx), floor(sy - bh * 0.93), max(1, floor(0.13 * k)), 225, 180, 140, true)
      hands[#hands + 1] = {floor(sx), floor(sy - bh), hw, i}
      if clap > 0 and ((floor(clap * 10) + i) % 2 == 0) then
        px.pixel(floor(sx - hw - 1), floor(sy - bh), 255, 225, 190); px.pixel(floor(sx + hw), floor(sy - bh), 255, 225, 190)
      end
    end
    end
  end
  return hands
end

-- the stand's hands, drawn over a saved picture of it
local function claps(hands, clap)
  if not hands or clap <= 0 then return end
  for _, hd in ipairs(hands) do
    if (floor(clap * 10) + hd[4]) % 2 == 0 then
      px.pixel(hd[1] - hd[3] - 1, hd[2], 255, 225, 190); px.pixel(hd[1] + hd[3], hd[2], 255, 225, 190)
    end
  end
end

-- ---------------------------------------------------------------- the golfer
-- Seen from behind, down the line of the shot: feet at (x, fy), height hpx.
-- u is the swing: address, the backswing to the top, impact, the finish.
local SHIRT = { {40, 80, 190}, {60, 160, 70} }
local CAP = { {30, 40, 110}, {235, 235, 235} }
local SKIN = {232, 178, 138}

local function swing_angle(u)
  local e = function(x) return x * x * (3 - 2 * x) end
  if u < 0.1 then return 0 end
  if u < 0.5 then return -2.6 * e((u - 0.1) / 0.4) end          -- to the top
  if u < 0.62 then return -2.6 + 2.6 * e((u - 0.5) / 0.12) end  -- down to the ball
  if u < 0.85 then return 2.7 * e((u - 0.62) / 0.23) end         -- the finish
  return 2.7
end

local function golfer_back(x, fy, hpx, pl, u, club_len, fixed_a)
  local s = hpx / 40
  local sh, cp = SHIRT[pl], CAP[pl]
  local a = fixed_a or swing_angle(u)
  local turn = fixed_a and 0 or clamp(a / 2.6, -1, 1)
  -- legs, a little flexed
  local function thick(x0, y0, x1, y1, w, r, g, b)
    for k = 0, w - 1 do px.line(floor(x0 + k), floor(y0), floor(x1 + k), floor(y1), r, g, b) end
  end
  thick(x - 5 * s, fy - 16 * s, x - 6 * s, fy - 1, max(2, floor(3 * s)), 50, 56, 80)
  thick(x + 2 * s, fy - 16 * s, x + 3 * s, fy - 1, max(2, floor(3 * s)), 42, 48, 70)
  R(x - 8 * s, fy - 2 * s, 5 * s, 2 * s, 240, 240, 240); R(x + 2 * s, fy - 2 * s, 5 * s, 2 * s, 225, 225, 225)
  -- hips and back, turning with the swing
  local tw = 11 * s * (1 - 0.18 * abs(turn))
  local cx = x + turn * 1.5 * s
  R(cx - tw / 2, fy - 18 * s, tw, 3 * s, 40, 44, 60)                          -- belt line
  for yy = 0, floor(13 * s) do                                                -- the shirt, lit from the left
    local q = yy / (13 * s)
    local w2 = tw * (0.92 + 0.12 * q)
    for xx = 0, floor(w2) do
      local l = 0.75 + 0.4 * (1 - xx / max(1, w2))
      P(cx - w2 / 2 + xx, fy - 31 * s + yy, clamp(sh[1] * l, 0, 255), clamp(sh[2] * l, 0, 255), clamp(sh[3] * l, 0, 255))
    end
  end
  -- the head from behind, the cap
  local hx, hy = cx + turn * 1.2 * s, fy - 35 * s
  C(hx, hy, 4 * s, 78, 54, 36)                                                 -- the back of the head
  C(hx + 3.4 * s, hy + 0.5 * s, max(1, 1.1 * s), SKIN[1] * 0.9, SKIN[2] * 0.9, SKIN[3] * 0.9)   -- an ear
  R(hx - 2.5 * s, hy + 3 * s, 5 * s, 2 * s, SKIN[1] * 0.8, SKIN[2] * 0.8, SKIN[3] * 0.8)        -- the neck
  R(hx - 4.5 * s, hy - 4.5 * s, 9 * s, 3.5 * s, cp[1], cp[2], cp[3])
  -- arms and club: the hands on a circle round the left shoulder
  local shx, shy = cx - 2 * s, fy - 28 * s
  local arm = 11 * s
  local hxx, hyy = shx + sin(a + 0.25) * arm, shy + cos(a + 0.25) * arm
  local sk = SKIN
  px.line(floor(shx), floor(shy), floor(hxx), floor(hyy), sk[1], sk[2], sk[3])
  px.line(floor(shx + 4 * s), floor(shy), floor(hxx + 1), floor(hyy), floor(sk[1] * 0.85), floor(sk[2] * 0.85), floor(sk[3] * 0.85))
  local ca = a * 1.25 + 0.2
  local cl = (club_len or 20) * s
  local ex, ey = hxx + sin(ca) * cl, hyy + cos(ca) * cl
  px.line(floor(hxx), floor(hyy), floor(ex), floor(ey), 200, 200, 210)
  R(ex - 1, ey - 1, 3, 2, 150, 150, 160)
end

-- ---------------------------------------------------------------- on screen
local function label(s, pl)
  local w = TW(s, "5x7")
  R(0, H - 9, w + 3, 9, 0, 0, 0)
  T(1, H - 8, s, COL[pl], "5x7")
end

local function hole_card(g, h, a)
  local s1 = "ЛУНКА " .. h.n .. "  ПАР " .. h.par
  local s2 = h.len .. " М  ИНДЕКС " .. h.si
  local w = max(TW(s1, "5x7"), TW(s2)) + 6
  local x = 4
  R(x, 12, w, 20, 0, 0, 0)
  R(x, 12, 2, 20, 255, 200, 60)
  T(x + 4, 14, s1, {255, 215, 90}, "5x7")
  T(x + 4, 24, s2, {230, 230, 230})
end

local function world_trees(h)
  local w = world_of(h)
  if w.all_trees then return w.all_trees end
  -- the mapped trees, and a wood along both sides of the hole where the map
  -- has only rough: a hole is never played in an empty field
  local t = {}
  for i, tr in ipairs(w.trees) do t[#t + 1] = {tr[1], tr[2], i} end
  local step = 16
  local n = 0
  for d = -30, w.len + 50, step do
    for side = -1, 1, 2 do
      n = n + 1
      local f = clamp(d / w.len, 0, 1)
      local px_, py_ = along(h, f, 0)
      local cx, cy = to_world(h, px_, py_)
      local off = side * (max(w.fw, 12) + 26 + ((n * 37) % 17))
      local x, y = cx + (d - f * w.len), cy + off
      local ok = true
      for _, wa in ipairs(w.water) do if (x - wa[1]) ^ 2 + (y - wa[2]) ^ 2 < (wa[3] + 6) ^ 2 then ok = false end end
      local gd = (x - w.green[1]) ^ 2 + (y - w.green[2]) ^ 2
      if gd < (w.green[3] + 14) ^ 2 then ok = false end
      if ok then t[#t + 1] = {x, y, n * 3 + 1} end
    end
  end
  w.all_trees = t
  return t
end

local function draw_house(cam, st, x, y)
  local c = st.house
  if not c then return end
  local gz = ground_at(x, y)
  local sx, sy, k, depth = project(cam, x, y, gz)
  if not sx or depth > ZFAR then return end
  local fogt = clamp((depth - 140) / 900, 0, 1) ^ 2
  local function col(cc, l)
    l = l or 1
    return floor(mix(cc[1] * l, st.haze[1], fogt)), floor(mix(cc[2] * l, st.haze[2], fogt)), floor(mix(cc[3] * l, st.haze[3], fogt))
  end
  local w, hh, roof = 26 * k, 8 * k, 4.5 * k
  local x0, top = sx - w / 2, sy - hh
  local r, g, b = col(c.wall)
  px.rect(floor(x0), floor(top), floor(w) + 1, floor(hh) + 1, r, g, b, true)
  local r2, g2, b2 = col(c.wall, 0.8)                         -- the shaded side
  px.rect(floor(x0 + w), floor(top + 1 * k), floor(5 * k) + 1, floor(hh - 1 * k) + 1, r2, g2, b2, true)
  local r3, g3, b3 = col(c.roof)
  for yy = 0, floor(roof) do                                 -- the roof
    local q = yy / max(1, roof)
    px.rect(floor(x0 - 1 * k + q * 3 * k), floor(top - roof + yy), floor(w + 2 * k - q * 6 * k + 5 * k * (1 - q)) + 1, 1, r3, g3, b3, true)
  end
  local r4, g4, b4 = col(c.win)
  if k > 0.35 then                                           -- two rows of windows
    for row = 0, 1 do
      for i = 0, 7 do
        px.rect(floor(x0 + (1.5 + i * 3.1) * k), floor(top + (1.5 + row * 3.4) * k), max(1, floor(1.5 * k)), max(1, floor(1.8 * k)), r4, g4, b4, true)
      end
    end
  end
end

local function farther(a, b) return a.d > b.d end

local function draw_things(cam, st, h, extra)
  local w0 = world_of(h)
  local list = w0.sortlist
  if not list then                          -- made once a hole, then only re-ordered
    list = {}
    for _, t in ipairs(world_trees(h)) do list[#list + 1] = {d = 0, t = t} end
    w0.sortlist = list
  end
  local fx, fy = cos(cam.yaw), sin(cam.yaw)
  for _, e in ipairs(list) do
    local rx, ry = e.t[1] - cam.x, e.t[2] - cam.y
    e.d = (rx * fx + ry * fy > 0.4) and (rx * rx + ry * ry) or -1   -- behind the camera: -1
  end
  table.sort(list, farther)
  local w = world_of(h)
  local cupd = (w.cup[1] - cam.x) ^ 2 + (w.cup[2] - cam.y) ^ 2
  local flag_done = false
  for _, e in ipairs(list) do
    if e.d >= 0 then                        -- the ones behind the camera sort last and are skipped
      if not flag_done and e.d < cupd then draw_flag(cam, w.cup[1], w.cup[2]); flag_done = true end
      draw_tree(cam, st, e.t, e.t[3])
    end
  end
  if not flag_done then draw_flag(cam, w.cup[1], w.cup[2]) end
  if extra then extra() end
end

-- the clubhouse stands behind the last green
local function things_with_house(cam, st, h, extra)
  if h.n == HOLES and st.house then
    local w = world_of(h)
    local a, b = w.line[#w.line - 1], w.line[#w.line]
    local dx, dy = b[1] - a[1], b[2] - a[2]
    local dl = sqrt(dx * dx + dy * dy)
    draw_house(cam, st, w.cup[1] + dx / dl * 55, w.cup[2] + dy / dl * 55)
  end
  draw_things(cam, st, h, extra)
end

-- A camera that stands still sees the same ground, trees and sky every frame:
-- they are drawn once, px.save()d, and every later frame px.restore()s them
-- and draws only what moves. Most of a frame's work on the panel was drawing
-- the same picture again (the owner, 2026-09-24: "доводи до 15 кадров").
local bg_key, bg_data = nil, nil
local function background(key, draw_still)
  if bg_key == key and px.restore() then return bg_data end
  bg_data = draw_still()
  px.save()
  bg_key = key
  return bg_data
end

local function render(cam, st, h, extra)
  px.clear(st.haze[1], st.haze[2], st.haze[3])
  draw_sky(cam, st)
  draw_land(cam, st)
  things_with_house(cam, st, h, extra)
end

-- a ball's world position from the plan's fraction and offset
local function ball_world(h, f, off)
  local x, y = along(h, f, off)
  return to_world(h, x, y)
end

-- ---------------------------------------------------------------- the scenes
-- The seconds inside a hole: the flyover with the hole card, the tee shot
-- from behind the player, the rest of the play from above, the last putt.
local FLY_END, TEE_END, PLAY_END = 0.8, 2.3, 4.5
local SWING_S, FLIGHT_S = 0.55, 0.9

local function scene_fly(g, h, st, u)
  local w = world_of(h)
  local L = w.len
  local e = u * u * (3 - 2 * u)
  local cam = {x = mix(-0.25 * L - 30, 0.35 * L, e), y = mix(-10, 5, e), z = mix(0.35 * L + 50, 0.16 * L + 28, e), f = 96}
  local tx, ty = w.cup[1], w.cup[2]
  look_at(cam, mix(0.6 * L, tx, e), mix(0, ty, e), 0, 40)
  TP.fog0, TP.fogr = 260, 1500            -- from high up the haze starts farther
  TP.colw = 2                             -- the one scene drawn whole every frame, and fast
  render(cam, st, h)
  TP.fog0, TP.fogr, TP.colw = 140, 900, 1
  if u < 0.8 then hole_card(g, h) end
end

-- The Old Course's own moment: the players take the ferry across the Siagne
-- to the far holes, and back again.
local function scene_ferry(g, h, st, u)
  px.clear(st.haze[1], st.haze[2], st.haze[3])
  for y = 0, 24 do                                         -- the sky
    local t = y / 24
    px.rect(0, y, W, 1, floor(mix(st.top[1], st.hor[1], t)), floor(mix(st.top[2], st.hor[2], t)), floor(mix(st.top[3], st.hor[3], t)), true)
  end
  for col = 0, W - 1 do                                    -- the Estérel, far
    local hg = 6 + 4 * sin(col * 0.05 + 1) + 2 * sin(col * 0.17)
    px.rect(col, floor(25 - hg), 1, floor(hg) + 1, st.ridge[1], st.ridge[2], st.ridge[3], true)
  end
  px.rect(0, 25, W, 6, 70, 104, 50, true)                  -- the far bank
  for i = 0, 9 do                                          -- its pines
    local x = 6 + i * 13 + (i * 7) % 5
    px.rect(x, 17, 1, 9, 100, 70, 44, true)
    px.rect(x - 4, 15, 9, 2, 44, 84, 40, true); px.rect(x - 3, 14, 7, 1, 70, 110, 55, true)
  end
  for y = 31, 55 do                                        -- the river, lighter far away
    local t = (y - 31) / 24
    local r, g2, b = mix(90, st.deep[1], t), mix(140, st.deep[2], t), mix(170, st.deep[3], t)
    px.rect(0, y, W, 1, floor(r), floor(g2), floor(b), true)
  end
  for k = 0, 40 do                                         -- ripples
    local x = (k * 37 + floor(u * 30) * (k % 3 + 1)) % W
    local y = 33 + (k * 11) % 22
    px.rect(x, y, 3 + k % 3, 1, 150, 190, 215, true)
  end
  px.rect(0, 56, W, 8, 80, 118, 56, true)                  -- the near bank
  -- the ferry: a flat deck on a cable, the two players on it
  local fx = floor(mix(-30, 70, u))
  local fy = 44
  px.line(0, 38, W - 1, 38, 60, 60, 60)                    -- the cable
  px.rect(fx, fy, 36, 4, 120, 90, 60, true)
  px.rect(fx, fy + 4, 36, 1, 60, 45, 30, true)
  px.rect(fx + 2, fy - 3, 32, 1, 200, 200, 200, true)      -- the rail
  for i = 0, 4 do px.rect(fx + 2 + i * 8, fy - 3, 1, 3, 180, 180, 180, true) end
  px.line(fx + 18, fy - 3, fx + 18, 38, 90, 90, 90)
  for pl = 1, 2 do
    local x = fx + 8 + (pl - 1) * 14
    local sh = SHIRT[pl]
    px.rect(x, fy - 7, 3, 4, sh[1], sh[2], sh[3], true)
    px.rect(x, fy - 3, 1, 3, 50, 50, 70, true); px.rect(x + 2, fy - 3, 1, 3, 50, 50, 70, true)
    px.circle(x + 1, fy - 9, 1, SKIN[1], SKIN[2], SKIN[3], true)
    px.rect(x - 1, fy - 11, 4, 1, CAP[pl][1], CAP[pl][2], CAP[pl][3], true)
    px.rect(x + 4, fy - 9, 2, 6, 60, 60, 60, true)           -- the bag
  end
  local s = "ПАРОМ ЧЕРЕЗ " .. st.river
  R(0, H - 9, TW(s, "5x7") + 3, 9, 0, 0, 0)
  T(1, H - 8, s, {255, 215, 90}, "5x7")
  if u > 0.55 then hole_card(g, h) end
end

local function scene_tee(g, h, st, u, ht)
  local w = world_of(h)
  local ev = h.order[1]
  local pl = ev.pl
  local s = ev.s
  local lx, ly = ball_world(h, s.f, s.off)
  if h.scene.kind == "ace" then lx, ly = w.cup[1], w.cup[2] end
  -- down the line: behind the tee, the player on the left of it
  local dirx, diry = lx, ly
  local dl = sqrt(dirx * dirx + diry * diry)
  dirx, diry = dirx / dl, diry / dl
  local cam = {x = -dirx * 5.5 + diry * 1.4, y = -diry * 5.5 - dirx * 1.4, z = 0.6 + 1.6, f = 110}
  look_at(cam, dirx * 160 + diry * 1.4, diry * 160 - dirx * 1.4, 0, 22)
  local st_ = ht - FLY_END
  local swing_u = clamp(st_ / SWING_S, 0, 1)
  local fu = clamp((st_ - SWING_S * 0.62) / FLIGHT_S, 0, 1)
  local apex = (h.par == 3) and 22 or clamp(dl * 0.12, 8, 34)
  background(round_id .. ":" .. h.n .. ":tee", function() render(cam, st, h) end)
  if fu > 0 then
    tracer(cam, 0, 0, lx, ly, apex, fu, pl)
    draw_ball3d(cam, mix(0, lx, fu), mix(0, ly, fu), 4 * apex * fu * (1 - fu), pl, true)
  end
  -- the player and the ball on its peg, in front of everything
  local bx, by = project(cam, 0, 0, ground_at(0, 0) + 0.05)
  if bx then
    golfer_back(bx - 17, by + 1, 34, pl, swing_u, 20)
    if fu <= 0 then P(bx, by - 1, 255, 255, 255); P(bx, by, 200, 180, 140) end
  end
  local what = (h.par == 3) and "УДАР НА ГРИН" or "УДАР С ТИ"
  label(NAMES[pl] .. ": " .. what, pl)
  if fu >= 1 and h.scene.kind ~= "ace" then
    local d = floor(dl) .. " М"
    R(W - TW(d, "5x7") - 4, 10, TW(d, "5x7") + 4, 9, 0, 0, 0)
    T(W - TW(d, "5x7") - 2, 11, d, {255, 230, 120}, "5x7")
  end
end

-- the rest of the hole from above: every shot between the first tee shot and
-- the last putt, one after the other, with their tracers
local function play_state(h, ht)
  local pos = {{f = 0, off = 0}, {f = 0, off = 0}}
  local first = h.order[1]
  pos[first.pl] = {f = first.s.f, off = first.s.off}
  local n = #h.order - 1
  local flying, holed, msg = nil, {false, false}, nil
  if n < 2 then return pos, flying, holed, msg end
  local sl = (PLAY_END - TEE_END - 0.1) / (n - 1)
  for k = 2, n do
    local ev = h.order[k]
    local t0 = TEE_END + (k - 2) * sl
    if ht < t0 then break end
    local u = min(1, (ht - t0) / (sl * 0.8))
    local s = ev.s
    if u < 1 then flying = {pl = ev.pl, from = pos[ev.pl], to = s, u = u} end
    pos[ev.pl] = {f = s.f, off = s.off}
    if u >= 1 and s.kind == "water" then msg = {pl = ev.pl, text = "В ВОДЕ", until_t = t0 + sl * 3} end
    if u >= 1 and ev.i == #h.p[ev.pl].shots then
      holed[ev.pl] = true
      local d = h.p[ev.pl].diff
      msg = {pl = ev.pl, text = WORD[d] or ("+" .. d), until_t = t0 + sl * 3}
    end
  end
  return pos, flying, holed, msg
end

-- The hole as a plan in the top right corner, both balls on it: where each
-- player is, all the time (the owner, 2026-09-24: "нет целостной картины").
local MAP_X, MAP_Y, MAP_W, MAP_H = W - 40, 9, 39, 18
local function minimap(h, pos, flying, holed)
  local sx, sy = MAP_W / 128, MAP_H / 48
  local function at(x, y) return MAP_X + x * sx, MAP_Y + (y - 8) * sy end
  R(MAP_X - 1, MAP_Y - 1, MAP_W + 2, MAP_H + 2, 10, 24, 12)
  for i = 1, #h.pts - 1 do                 -- the line of play
    local ax, ay = at(h.pts[i][1], h.pts[i][2])
    local bx, by = at(h.pts[i + 1][1], h.pts[i + 1][2])
    px.line(floor(ax), floor(ay), floor(bx), floor(by), 70, 150, 60)
  end
  for i = 1, #h.water, 3 do                -- water, sampled
    local w = h.water[i]
    local x, y = at(w[1], w[2]); P(x, y, 50, 110, 210)
  end
  local gx, gy = at(h.green[1], h.green[2])
  R(gx - 1, gy - 1, 3, 3, 120, 220, 100)
  P(gx, gy - 2, 240, 40, 40)                -- the flag
  for pl = 1, 2 do
    if not holed[pl] then
      local f, off = pos[pl].f, pos[pl].off
      if flying and flying.pl == pl then
        local a, b = flying.from, flying.to
        f = (a.f or 0) + ((b.f or 0) - (a.f or 0)) * flying.u
        off = (a.off or 0) + ((b.off or 0) - (a.off or 0)) * flying.u
      end
      local x, y = along(h, f, off)
      x, y = at(x, y)
      local c = COL[pl]
      R(x - 1, y - 1, 3, 3, c[1], c[2], c[3])
      P(x, y, 255, 255, 255)
    end
  end
end

local function scene_play(g, h, st, ht)
  local w = world_of(h)
  local L = w.len
  local u = 0.5                            -- a still camera: its picture is drawn once
  local cam = {f = 96}
  local mx, my = to_world(h, along(h, 0.6, 0))
  if h.n % 2 == 1 then                    -- from behind, high, as the clubs' plans look
    cam.x, cam.y, cam.z = -0.06 * L + u * 0.08 * L, -0.05 * L, 0.22 * L + 30
  else                                    -- from the side, over the left of the hole
    cam.x, cam.y, cam.z = 0.34 * L + u * 0.1 * L, -0.36 * L - 24, 0.22 * L + 26
  end
  look_at(cam, mx, my, 0, 34)
  local pos, flying, holed, msg = play_state(h, ht)
  TP.fog0, TP.fogr = 260, 1500            -- seen from above: the hole clear to the green
  background(round_id .. ":" .. h.n .. ":play", function() render(cam, st, h) end)
  do
    for pl = 1, 2 do
      if not holed[pl] and not (flying and flying.pl == pl) then
        local x, y = ball_world(h, pos[pl].f, pos[pl].off)
        draw_ball3d(cam, x, y, 0, pl, true)
      end
    end
    if flying then
      local a, b = flying.from, flying.to
      local ax, ay = ball_world(h, a.f or 0, a.off or 0)
      local bx, by = ball_world(h, b.f or 0, b.off or 0)
      local d = sqrt((bx - ax) ^ 2 + (by - ay) ^ 2)
      local putt = b.kind == "putt"
      local apex = putt and 0 or clamp(d * 0.13, 2, 30)
      tracer(cam, ax, ay, bx, by, apex, flying.u, flying.pl, putt)
      local q = flying.u
      draw_ball3d(cam, mix(ax, bx, q), mix(ay, by, q), putt and 0 or 4 * apex * q * (1 - q), flying.pl, true)
    end
  end
  TP.fog0, TP.fogr = 140, 900
  minimap(h, pos, flying, holed)
  if msg and ht < msg.until_t then label(NAMES[msg.pl] .. ": " .. msg.text, msg.pl) end
end

local function scene_putt(g, h, st, ht)
  local w = world_of(h)
  local ev = h.final
  local pl = ev.pl
  local u = (ht - PLAY_END) / (HOLE_S - PLAY_END)
  local win = (h.p[1].strokes < h.p[2].strokes) and 1 or (h.p[2].strokes < h.p[1].strokes) and 2 or 0
  local cx, cy = w.cup[1], w.cup[2]
  local bx, by = ball_world(h, ev.from, (h.p[pl].shots[ev.i - 1] or {off = 0}).off or 0)
  if ev.from <= 0 then bx, by = ball_world(h, 0.97, 1.5) end
  local dx, dy = cx - bx, cy - by
  local dl = sqrt(dx * dx + dy * dy)
  if dl < 1.5 then dx, dy, dl = 1, 0.3, 1.04 end
  dx, dy = dx / dl, dy / dl
  local dist = max(1.5, min(dl, 14, w.green[3] * 0.85))   -- a putt starts on the green
  bx, by = cx - dx * dist, cy - dy * dist
  local roll = clamp(u / 0.55, 0, 1)
  local after = clamp((u - 0.55) / 0.45, 0, 1)
  local q = 1 - (1 - roll) * (1 - roll)
  local cam = {f = 110}
  local reverse = false                   -- from behind the hole the player was never in it
  local low = (h.n % 2 == 0)              -- even holes: lower and closer, the green at eye level
  if reverse then                         -- from behind the hole, the ball coming at us
    cam.x, cam.y = cx + dx * 2.6, cy + dy * 2.6
    cam.z = ground_at(cx, cy) + 0.45
    look_at(cam, bx, by, ground_at(bx, by), 30)
  else                                    -- behind the ball, low, the flag ahead
    local back, side, up = low and 3.6 or 4.6, low and 0.6 or 1.0, low and 0.6 or 1.05
    cam.x, cam.y = bx - dx * back + dy * side, by - dy * back - dx * side
    cam.z = ground_at(bx, by) + up
    look_at(cam, cx, cy, ground_at(cx, cy), 30)
    cam.hor = 45 - (cam.z - ground_at(bx, by)) * cam.f / back  -- the ball above the caption
    cam.yaw = cam.yaw - (low and 0.1 or 0.32)                  -- the hole right of centre, the player left
  end
  local hands = background(round_id .. ":" .. h.n .. ":putt", function()
    local hs
    render(cam, st, h, function() if not reverse then hs = draw_crowd(cam, cx, cy, dx, dy, 0) end end)
    return hs
  end)
  claps(hands, (after > 0) and ((win > 0) and after or after * 0.4) or 0)
  if roll < 1 then
    tracer(cam, bx, by, cx, cy, 0, q, pl, true)
    draw_ball3d(cam, mix(bx, cx, q), mix(by, cy, q), 0, pl, false)
  end
  if not reverse then                     -- the player over the putt: a short pendulum
    local sx, sy = project(cam, bx, by, ground_at(bx, by))
    if sx then
      local a = (u < 0.12) and -0.45 * sin(u / 0.12 * 3.1416) or 0.3 * min(1, (u - 0.12) / 0.1)
      golfer_back(sx - (low and 28 or 24), sy + 1, low and 40 or 34, pl, nil, 13, a)
    end
  end
  if after > 0 then
    local s, c
    if win > 0 then
      s, c = "БРАВО, " .. NAMES[win] .. "!", COL[win]
      for k = 0, 22 do                                   -- confetti
        local x = (k * 29 + floor(after * 40) * 3) % W
        local y = 10 + (k * 17 + floor(after * 60)) % 36
        local cc = ({{255, 80, 80}, {255, 220, 60}, {80, 200, 255}, {255, 255, 255}})[k % 4 + 1]
        P(x, y, cc[1], cc[2], cc[3])
      end
    else
      s, c = "ЛУНКА ПОПОЛАМ", {255, 215, 90}
    end
    local tw = TW(s, "5x7")
    R((W - tw) // 2 - 2, 44, tw + 4, 18, 0, 0, 0)
    T((W - tw) // 2, 45, s, c, "5x7")
    local d = win > 0 and h.p[win].diff or h.p[1].diff
    local wd = (win > 0 and h.p[win].strokes or h.p[1].strokes) .. " - " .. (WORD[d] or ("+" .. d))
    T((W - TW(wd, "5x7")) // 2, 54, wd, {230, 230, 230}, "5x7")
  else
    label(NAMES[pl] .. ": ПАТТ", pl)
  end
end

local function scene_ace(g, h, st, ht)
  local w = world_of(h)
  local u = (ht - TEE_END) / (HOLE_S - TEE_END)
  local cx, cy = w.cup[1], w.cup[2]
  local cam = {x = cx - 9, y = cy + 4, z = ground_at(cx, cy) + 2.2, f = 100}
  look_at(cam, cx, cy, ground_at(cx, cy), 42)
  local hands = background(round_id .. ":" .. h.n .. ":ace", function()
    local hs
    render(cam, st, h, function() hs = draw_crowd(cam, cx, cy, 0.9, -0.4, 0) end)
    return hs
  end)
  claps(hands, u)
  for b = 0, 5 do                                        -- fireworks
    local v = (u * 1.6 - b * 0.15) % 1
    local bx_, by_ = 14 + b * 20, 8 + (b * 7) % 12
    local c = ({{255, 90, 60}, {255, 220, 60}, {90, 200, 255}, {140, 255, 120}, {255, 120, 255}, {255, 255, 255}})[b + 1]
    for k = 0, 11 do
      local ang = k * 0.5236
      P(bx_ + cos(ang) * v * 12, by_ + sin(ang) * v * 8,
        floor(c[1] * (1 - v * 0.6)), floor(c[2] * (1 - v * 0.6)), floor(c[3] * (1 - v * 0.6)))
    end
  end
  local s = "HOLE IN ONE!"
  if (u * 4) % 1 < 0.75 then
    R((W - TW(s, "5x7")) // 2 - 2, 26, TW(s, "5x7") + 4, 9, 0, 0, 0)
    T((W - TW(s, "5x7")) // 2, 27, s, {255, 215, 60}, "5x7")
  end
  label(NAMES[h.scene.pl] .. " - ЛУНКА " .. h.n, h.scene.pl)
end

-- ---------------------------------------------------------------- screens
local function panorama(g, h, st, t, radius)
  local w = world_of(h)
  local cx, cy = w.cup[1], w.cup[2]
  local a = t * 0.08 + 2.4
  local cam = {x = cx + cos(a) * radius, y = cy + sin(a) * radius, z = 14 + radius * 0.25, f = 96}
  look_at(cam, cx, cy, 0, 44)
  render(cam, st, h)
end

local function draw_intro(g, t, have_ground)
  local st = STYLE[g.course.id]
  local h = g.holes[1]
  if have_ground then background(round_id .. ":intro", function() panorama(g, h, st, 0, 70) end)
  else                                     -- until the first hole is made: the evening sky
    for y = 0, H - 1, 4 do
      local k = y / H
      px.rect(0, y, W, 4, floor(mix(st.top[1], 10, k)), floor(mix(st.top[2], 30, k)), floor(mix(st.top[3], 20, k)), true)
    end
  end
  R(0, 0, W, 9, 0, 0, 0)
  local title = g.course.name .. " - ПАР " .. g.course.par
  T((W - TW(title)) // 2, 1, title, {255, 215, 90})
  local function card(x, pl, right)
    R(x, 12, 58, 34, 0, 0, 0)
    local aw = avatar(right and (x + 58 - 26) or (x + 2), 14, pl)
    local tx = right and (x + 2) or (x + 28)
    T(tx, 16, NAMES[pl], COL[pl])
    T(tx, 26, "HCP " .. g.hcp[pl], {210, 210, 210})
  end
  card(2, 1, false)
  card(W - 60, 2, true)
  if (t * 2) % 1 < 0.7 then
    R(57, 48, 14, 8, 0, 0, 0)
    T((W - TW("VS")) // 2, 49, "VS", {255, 90, 60})
  end
  local s = g.course.sub
  R(0, H - 8, TW(s) + 3, 8, 0, 0, 0)
  T(1, H - 7, s, {230, 230, 230})
end

local function draw_result(g, t)
  local st = STYLE[g.course.id]
  local h = g.holes[HOLES]
  -- the last green and the clubhouse behind it, from the fairway, moving in
  local w = world_of(h)
  local fx, fy = to_world(h, along(h, 0.74, 0))
  local cam = {x = fx, y = fy, z = ground_at(fx, fy) + 12, f = 100}
  local a2, b2 = w.line[#w.line - 1], w.line[#w.line]
  local dx, dy = b2[1] - a2[1], b2[2] - a2[2]
  local dl = sqrt(dx * dx + dy * dy)
  look_at(cam, w.cup[1] + dx / dl * 25, w.cup[2] + dy / dl * 25, 0, 40)
  background(round_id .. ":result", function() render(cam, st, h) end)
  R(0, 0, W, 9, 0, 0, 0)
  local title = "ИТОГ - " .. g.course.name
  T((W - TW(title)) // 2, 1, title, {255, 215, 90})
  for pl = 1, 2 do
    local x = (pl == 1) and 2 or (W - 44)
    R(x, 11, 42, 26, 0, 0, 0)
    local lines = {NAMES[pl], tostring(g.total[pl]), topar_s(g.topar[pl])}
    for i, s in ipairs(lines) do
      T(x + 2, 12 + (i - 1) * 8, s, (i == 1) and COL[pl] or {225, 225, 225})
    end
  end
  local b = "БЕРДИ " .. g.birdies[1] .. " : " .. g.birdies[2]
  R((W - TW(b, "5x7")) // 2 - 2, 38, TW(b, "5x7") + 4, 9, 0, 0, 0)
  T((W - TW(b, "5x7")) // 2, 39, b, {225, 225, 225}, "5x7")
  local win
  if g.total[1] < g.total[2] then win = "ПОБЕДИЛ " .. NAMES[1] .. "!"
  elseif g.total[2] < g.total[1] then win = "ПОБЕДИЛ " .. NAMES[2] .. "!"
  else win = "НИЧЬЯ!" end
  local c = (g.total[1] < g.total[2]) and COL[1] or (g.total[2] < g.total[1]) and COL[2] or {255, 215, 90}
  if (t * 2) % 1 < 0.8 then
    R((W - TW(win, "5x7")) // 2 - 2, 49, TW(win, "5x7") + 4, 9, 0, 0, 0)
    T((W - TW(win, "5x7")) // 2, 50, win, c, "5x7")
  end
end

-- ---------------------------------------------------------------- draw
-- The grid of the next hole is made while this one plays, a slice every frame,
-- as big as the time left needs. The panel does not always run at 15 fps (9 to
-- 13 was measured), so the slice is sized from the frames actually coming:
-- the cells still to make, over the time until the hole starts, at the frame
-- time measured. Sized for 15 fps it fell behind at 9, and the page showed a
-- plain field in its place (the owner, 2026-09-24: "пустой экран").
local jobs, grids = {}, {}
local last_t, frame_dt = nil, 1 / 12

local function cells_left(n)
  local gr = grids[n]
  if gr and gr.done then return 0 end
  if not gr then return nil end
  return (gr.ny - gr.j) * gr.nx
end

local by_now_on_screen = 0                 -- the hole on screen, set by draw()
local function work(t)
  local j = jobs[1]
  if not j then return end
  for _, jj in ipairs(jobs) do             -- every queued grid exists, so its size is known
    if not grids[jj.n] then grids[jj.n] = grid_new(jj.h, jj.st) end
  end
  -- the most a frame must do for every queued hole to be ready when it starts
  -- A frame that works harder is a slower frame, and a slower frame leaves
  -- fewer frames: pushing without a ceiling spiralled the panel down to 6 fps.
  -- So the hole on screen, if it is ever late, may take up to 1500 cells a
  -- frame, and the one to come no more than 700.
  local need, acc = 150, 0
  for _, jj in ipairs(jobs) do
    acc = acc + (cells_left(jj.n) or 0)
    local by = INTRO + (jj.n - 1) * HOLE_S          -- when hole n comes on screen
    local frames = (by - t) / frame_dt - 2
    need = max(need, (frames >= 1) and acc / frames or 1500)
  end
  local cap = (by_now_on_screen and j.n <= by_now_on_screen) and 1500 or 700
  if grid_step(grids[j.n], min(cap, floor(need) + 1)) then table.remove(jobs, 1) end
end

local function ready(n) return grids[n] and grids[n].done end

-- a plain field for a frame whose ground is not made yet (it should not be)
local function fallback(st)
  px.rect(0, 0, W, 26, st.hor[1], st.hor[2], st.hor[3], true)
  px.rect(0, 26, W, H - 26, st.rough[1], st.rough[2], st.rough[3], true)
end

function draw()
  frame_no = frame_no + 1
  local n = px.now()
  -- the round of this two-minute period: periods start on even minutes
  local id = ((n.year % 100) * 400 + n.yday) * 720 + (n.hour * 60 + n.min) // 2
  if id ~= round_id then
    round, round_id = make_round(id), id
    jobs, grids = {}, {}
  end
  local g = round
  local st = STYLE[g.course.id]
  local t = px.t() * PERIOD
  local hn = (t < INTRO) and 0 or min(HOLES, floor((t - INTRO) / HOLE_S) + 1)
  -- The hole on screen (the first during the introduction) and the next one
  -- are always made or queued, the one on screen first - also when the page is
  -- opened in the middle of a round. A hole gone by loses its job and grid.
  while jobs[1] and jobs[1].n < max(1, hn) do table.remove(jobs, 1) end
  for k in pairs(grids) do if k < hn then grids[k] = nil end end
  for n = max(1, hn), min(HOLES, max(1, hn) + 1) do
    local queued = false
    for _, j in ipairs(jobs) do if j.n == n then queued = true end end
    if not queued and not (grids[n] and grids[n].done) then
      if grids[n] then grids[n] = nil end   -- half made and not queued: start again
      jobs[#jobs + 1] = {n = n, h = g.holes[n], st = st}
    end
  end
  table.sort(jobs, function(a, b) return a.n < b.n end)
  -- the frame time, from the clock the round runs on
  if last_t then
    local dt = t - last_t
    if dt > 0 and dt < 1 then frame_dt = frame_dt * 0.85 + dt * 0.15 end
  end
  last_t = t
  by_now_on_screen = hn
  work(t)

  if t < INTRO then
    grid = grids[1]
    draw_intro(g, t, ready(1))
    return
  elseif t >= RESULT_AT then
    grid = grids[HOLES]
    if ready(HOLES) then draw_result(g, t - RESULT_AT) else fallback(st) end
    return
  end
  local ht = (t - INTRO) - (hn - 1) * HOLE_S
  local h = g.holes[hn]
  grid = grids[hn]
  if not ready(hn) then fallback(st)
  elseif ht < FLY_END and st.ferry and st.ferry[h.n] then scene_ferry(g, h, st, ht / FLY_END)
  elseif ht < FLY_END then scene_fly(g, h, st, ht / FLY_END)
  elseif ht < TEE_END then scene_tee(g, h, st, ht - 0, ht)
  elseif h.scene.kind == "ace" then scene_ace(g, h, st, ht)
  elseif ht < PLAY_END then scene_play(g, h, st, ht)
  else scene_putt(g, h, st, ht) end
  -- the score so far: holes finished, and this one once a ball is in
  local upto = {0, 0}
  for k = 1, hn - 1 do
    upto[1] = upto[1] + g.holes[k].p[1].diff
    upto[2] = upto[2] + g.holes[k].p[2].diff
  end
  if ht >= HOLE_S - 0.8 then for pl = 1, 2 do upto[pl] = upto[pl] + h.p[pl].diff end end
  draw_score(g, upto, hn, h)
  draw_clock()
end
