-- world_clock.lua - a dotted world map where daylight is lit and night is dim.
--
-- 128x64 divides exactly into a 64x32 grid of dots on a 2 px pitch: one lit
-- pixel, one dark gap. Land dots on the day side are bright, night-side dots
-- dim, and civil twilight (sun between 0 and -6 degrees) blends between them,
-- so the terminator draws itself and creeps across the map through the day.
--
-- The time sits in the empty South Pacific, bottom left, which on this
-- projection is the one big patch of open water with nothing to cover.

local W, H = px.size()
local floor, sin, cos, asin, rad, deg, abs, max, min, pi =
  math.floor, math.sin, math.cos, math.asin, math.rad, math.deg, math.abs, math.max, math.min, math.pi

-- ---------------------------------------------------------------- the map
-- BEGIN WORLD MASK - generated by tools/luasim/gen_world.py, do not edit
local MASK = {
  "...........#.#####..#########.............##...#####....#.......",
  "...###...###########..######........#....#..################....",
  "#####################.#######.....##############################",
  ".####################..##...#....###############################",
  "..##############..###..........#.##.##########################..",
  "...#....##############........##.########################..##...",
  ".........#############.........##########################.......",
  "..........###########.#........##########################.......",
  "..........##########..........##########################.#......",
  "..........#########...........####.####################.#.......",
  "...........#######............#####...################.##.......",
  "...........#######............########################..........",
  "............###..............#########################..........",
  ".............##.#.##.........##############.########............",
  "..............###............#############...##.####.#..........",
  "................#..#.........############....##..###............",
  ".................#####.......############.....#..#...##.........",
  "..................#####.......#..########........##.#...........",
  ".................#######.........#######.........#######........",
  ".................#########........#####...........#..#.###......",
  "..................########........#####............#.....##.....",
  "..................#######.........#######..............#.#......",
  "...................######.........#####.#............#####......",
  "...................######.........#######...........#######.....",
  "...................#####..........####..............########....",
  "...................####............###..............########....",
  "...................####............##...............##..###.....",
  "...................###...................................##....#",
  "..................###.....................................#...#.",
  "..................##............................................",
  "..................##............................................",
  "...................#............................................",
}
local MASK_TOP, MASK_BOTTOM = 78.0, -58.0
-- END WORLD MASK

local COLS, ROWS = 64, 32

-- Cities worth a dot. Edit freely; the first one is home and it pulses.
local CITIES = {
  {name = "CANNES",   lat = 43.55, lon =   7.02},
  {name = "MOSCOW",   lat = 55.75, lon =  37.62},
  {name = "NEW YORK", lat = 40.71, lon = -74.00},
  {name = "SF",       lat = 37.77, lon = -122.42},
  {name = "TOKYO",    lat = 35.68, lon = 139.69},
}

local function cell_of(lat, lon)
  local c = floor((lon + 180) / 360 * COLS)
  local r = floor((MASK_TOP - lat) / (MASK_TOP - MASK_BOTTOM) * ROWS)
  return c, r
end

-- ---------------------------------------------------------------- the sun
-- Declination by the usual cosine approximation, and the subsolar longitude
-- straight from UTC. Neither is ephemeris-grade - the equation of time can
-- move the line by up to four degrees - but a dot here is 5.6 degrees wide,
-- so the error is smaller than one dot.
local function sun(n)
  local decl = rad(-23.44) * cos(2 * pi * ((n.yday or 255) + 10) / 365)
  local utcmin = (n.hour * 60 + n.min - (n.utc or 0) * 60) % 1440
  local sublon = rad(-15 * (utcmin / 60 - 12))
  return decl, sublon
end

-- ---------------------------------------------------------------- the time
-- A bold 6x11 face with 2 px strokes: solid digits against a dotted map is
-- the whole look. Narrow enough that HH:MM fits the 32 px of open ocean.
local DIG = {
  ["0"]={".####.","######","##..##","##..##","##..##","##..##","##..##","##..##","##..##","######",".####."},
  ["1"]={"..##..",".###..","####..","..##..","..##..","..##..","..##..","..##..","..##..","######","######"},
  ["2"]={".####.","######","##..##","....##","...###","..###.",".###..","###...","##....","######","######"},
  ["3"]={".####.","######","##..##","....##","..###.","..####","....##","....##","##..##","######",".####."},
  ["4"]={"...###","..####",".##.##","##..##","##..##","######","######","....##","....##","....##","....##"},
  ["5"]={"######","######","##....","##....","#####.","######","....##","....##","##..##","######",".####."},
  ["6"]={".####.","######","##....","##....","#####.","######","##..##","##..##","##..##","######",".####."},
  ["7"]={"######","######","....##","....##","...##.","...##.","..##..","..##..","..##..","..##..","..##.."},
  ["8"]={".####.","######","##..##","##..##",".####.",".####.","##..##","##..##","##..##","######",".####."},
  ["9"]={".####.","######","##..##","##..##","##..##","######",".#####","....##","....##","######",".####."},
  [":"]={"..","..","..","##","##","..","..","##","##","..",".."},
}

local function big(x, y, s, r, g, b)
  for i = 1, #s do
    local gl = DIG[s:sub(i, i)]
    if gl then
      for row = 1, #gl do
        local line = gl[row]
        for col = 1, #line do
          if line:sub(col, col) == "#" then px.pixel(x + col - 1, y + row - 1, r, g, b) end
        end
      end
      x = x + #gl[1] + 1
    end
  end
end

-- ---------------------------------------------------------------- draw
local DAY   = {225, 228, 232}
local NIGHT = { 52,  56,  64}

function draw()
  local n = px.now()
  local decl, sublon = sun(n)
  local sd, cd = sin(decl), cos(decl)

  px.clear(0, 0, 0)

  for r = 0, ROWS - 1 do
    local row = MASK[r + 1]
    if row then
      local lat = rad(MASK_TOP - (r + 0.5) * (MASK_TOP - MASK_BOTTOM) / ROWS)
      local sl, cl = sin(lat), cos(lat)
      for c = 0, COLS - 1 do
        if row:sub(c + 1, c + 1) == "#" then
          local lon = rad(-180 + (c + 0.5) * 360 / COLS)
          local el = deg(asin(sl * sd + cl * cd * cos(lon - sublon)))
          -- 0 at the end of civil twilight, 1 once the sun is up
          local k = max(0, min(1, (el + 6) / 6))
          px.pixel(c * 2, r * 2,
                   floor(NIGHT[1] + (DAY[1] - NIGHT[1]) * k),
                   floor(NIGHT[2] + (DAY[2] - NIGHT[2]) * k),
                   floor(NIGHT[3] + (DAY[3] - NIGHT[3]) * k))
        end
      end
    end
  end

  -- Cities are 2x2: the dot and its gap, which reads as a bigger dot on the
  -- same grid rather than as something drawn on top of it.
  for i, city in ipairs(CITIES) do
    local c, r = cell_of(city.lat, city.lon)
    local a = 1.0
    if i == 1 then a = 0.65 + 0.35 * abs(sin(pi * (n.sec + px.t() * 60))) end  -- home breathes
    px.rect(c * 2, r * 2, 2, 2, floor(255 * a), floor(140 * a), floor(40 * a), true)
  end

  big(1, 50, string.format("%02d:%02d", n.hour, n.min), 255, 255, 255)
end
