#pragma once
// GENERATED by tools/luasim/gen_tz.py from tzdata 2026c - do not edit.
//
// IANA zone name -> POSIX TZ string, for the world clock's cities: 489 zones
// under Africa, America, Antarctica, Arctic, Asia,
// Atlantic, Australia, Europe, Indian, Pacific.
// Names in strcmp order for a binary search; each distinct string stored once.
// 8058 + 1301 bytes of text, 1956 of index.
//
// Source: the IANA tz database, public domain; each string is its zone's TZif
// footer, checked against the zone itself from 2026-09-01 to 2028-09-01 UTC.
//
// Approximate: no footer matches these zones in that window, so each has the
// fixed offset it keeps longest there.
//   Africa/Casablanca        <+00>0     footer '<+00>0'; also +1 h for 19 d
//   Africa/El_Aaiun          <+00>0     footer '<+00>0'; also +1 h for 19 d

#include <stdint.h>

#define TZDB_VERSION "2026c"
#define TZDB_COUNT 489

static const char kTzPosix[] =
  "<+00>0\0"
  "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3\0"
  "<+0330>-3:30\0"
  "<+03>-3\0"
  "<+0430>-4:30\0"
  "<+04>-4\0"
  "<+0530>-5:30\0"
  "<+0545>-5:45\0"
  "<+05>-5\0"
  "<+0630>-6:30\0"
  "<+06>-6\0"
  "<+07>-7\0"
  "<+0845>-8:45\0"
  "<+08>-8\0"
  "<+09>-9\0"
  "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0\0"
  "<+10>-10\0"
  "<+11>-11\0"
  "<+11>-11<+12>,M10.1.0,M4.1.0/3\0"
  "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45\0"
  "<+12>-12\0"
  "<+13>-13\0"
  "<+14>-14\0"
  "<-01>1\0"
  "<-01>1<+00>,M3.5.0/0,M10.5.0/1\0"
  "<-02>2\0"
  "<-02>2<-01>,M3.5.0/-1,M10.5.0/0\0"
  "<-03>3\0"
  "<-03>3<-02>,M3.2.0,M11.1.0\0"
  "<-04>4\0"
  "<-04>4<-03>,M9.1.6/24,M4.1.6/24\0"
  "<-05>5\0"
  "<-06>6\0"
  "<-06>6<-05>,M9.1.6/22,M4.1.6/22\0"
  "<-08>8\0"
  "<-0930>9:30\0"
  "<-09>9\0"
  "<-10>10\0"
  "<-11>11\0"
  "ACST-9:30\0"
  "ACST-9:30ACDT,M10.1.0,M4.1.0/3\0"
  "AEST-10\0"
  "AEST-10AEDT,M10.1.0,M4.1.0/3\0"
  "AKST9AKDT,M3.2.0,M11.1.0\0"
  "AST4\0"
  "AST4ADT,M3.2.0,M11.1.0\0"
  "AWST-8\0"
  "CAT-2\0"
  "CET-1\0"
  "CET-1CEST,M3.5.0,M10.5.0/3\0"
  "CST-8\0"
  "CST5CDT,M3.2.0/0,M11.1.0/1\0"
  "CST6\0"
  "CST6CDT,M3.2.0,M11.1.0\0"
  "ChST-10\0"
  "EAT-3\0"
  "EET-2\0"
  "EET-2EEST,M3.4.4/50,M10.4.4/50\0"
  "EET-2EEST,M3.5.0/0,M10.5.0/0\0"
  "EET-2EEST,M3.5.0/3,M10.5.0/4\0"
  "EET-2EEST,M4.5.5/0,M10.5.4/24\0"
  "EST5\0"
  "EST5EDT,M3.2.0,M11.1.0\0"
  "GMT0\0"
  "GMT0BST,M3.5.0/1,M10.5.0\0"
  "GMT0IST,M3.5.0/1,M10.5.0\0"
  "HKT-8\0"
  "HST10\0"
  "HST10HDT,M3.2.0,M11.1.0\0"
  "IST-2IDT,M3.4.4/26,M10.5.0\0"
  "IST-5:30\0"
  "JST-9\0"
  "KST-9\0"
  "MSK-3\0"
  "MST7\0"
  "MST7MDT,M3.2.0,M11.1.0\0"
  "NST3:30NDT,M3.2.0,M11.1.0\0"
  "NZST-12NZDT,M9.5.0,M4.1.0/3\0"
  "PKT-5\0"
  "PST-8\0"
  "PST8PDT,M3.2.0,M11.1.0\0"
  "SAST-2\0"
  "SST11\0"
  "WAT-1\0"
  "WET0WEST,M3.5.0/1,M10.5.0\0"
  "WIB-7\0"
  "WIT-9\0"
  "WITA-8\0"
;

static const char kTzNames[] =
  "Africa/Abidjan\0"
  "Africa/Accra\0"
  "Africa/Addis_Ababa\0"
  "Africa/Algiers\0"
  "Africa/Asmara\0"
  "Africa/Asmera\0"
  "Africa/Bamako\0"
  "Africa/Bangui\0"
  "Africa/Banjul\0"
  "Africa/Bissau\0"
  "Africa/Blantyre\0"
  "Africa/Brazzaville\0"
  "Africa/Bujumbura\0"
  "Africa/Cairo\0"
  "Africa/Casablanca\0"
  "Africa/Ceuta\0"
  "Africa/Conakry\0"
  "Africa/Dakar\0"
  "Africa/Dar_es_Salaam\0"
  "Africa/Djibouti\0"
  "Africa/Douala\0"
  "Africa/El_Aaiun\0"
  "Africa/Freetown\0"
  "Africa/Gaborone\0"
  "Africa/Harare\0"
  "Africa/Johannesburg\0"
  "Africa/Juba\0"
  "Africa/Kampala\0"
  "Africa/Khartoum\0"
  "Africa/Kigali\0"
  "Africa/Kinshasa\0"
  "Africa/Lagos\0"
  "Africa/Libreville\0"
  "Africa/Lome\0"
  "Africa/Luanda\0"
  "Africa/Lubumbashi\0"
  "Africa/Lusaka\0"
  "Africa/Malabo\0"
  "Africa/Maputo\0"
  "Africa/Maseru\0"
  "Africa/Mbabane\0"
  "Africa/Mogadishu\0"
  "Africa/Monrovia\0"
  "Africa/Nairobi\0"
  "Africa/Ndjamena\0"
  "Africa/Niamey\0"
  "Africa/Nouakchott\0"
  "Africa/Ouagadougou\0"
  "Africa/Porto-Novo\0"
  "Africa/Sao_Tome\0"
  "Africa/Timbuktu\0"
  "Africa/Tripoli\0"
  "Africa/Tunis\0"
  "Africa/Windhoek\0"
  "America/Adak\0"
  "America/Anchorage\0"
  "America/Anguilla\0"
  "America/Antigua\0"
  "America/Araguaina\0"
  "America/Argentina/Buenos_Aires\0"
  "America/Argentina/Catamarca\0"
  "America/Argentina/ComodRivadavia\0"
  "America/Argentina/Cordoba\0"
  "America/Argentina/Jujuy\0"
  "America/Argentina/La_Rioja\0"
  "America/Argentina/Mendoza\0"
  "America/Argentina/Rio_Gallegos\0"
  "America/Argentina/Salta\0"
  "America/Argentina/San_Juan\0"
  "America/Argentina/San_Luis\0"
  "America/Argentina/Tucuman\0"
  "America/Argentina/Ushuaia\0"
  "America/Aruba\0"
  "America/Asuncion\0"
  "America/Atikokan\0"
  "America/Atka\0"
  "America/Bahia\0"
  "America/Bahia_Banderas\0"
  "America/Barbados\0"
  "America/Belem\0"
  "America/Belize\0"
  "America/Blanc-Sablon\0"
  "America/Boa_Vista\0"
  "America/Bogota\0"
  "America/Boise\0"
  "America/Buenos_Aires\0"
  "America/Cambridge_Bay\0"
  "America/Campo_Grande\0"
  "America/Cancun\0"
  "America/Caracas\0"
  "America/Catamarca\0"
  "America/Cayenne\0"
  "America/Cayman\0"
  "America/Chicago\0"
  "America/Chihuahua\0"
  "America/Ciudad_Juarez\0"
  "America/Coral_Harbour\0"
  "America/Cordoba\0"
  "America/Costa_Rica\0"
  "America/Coyhaique\0"
  "America/Creston\0"
  "America/Cuiaba\0"
  "America/Curacao\0"
  "America/Danmarkshavn\0"
  "America/Dawson\0"
  "America/Dawson_Creek\0"
  "America/Denver\0"
  "America/Detroit\0"
  "America/Dominica\0"
  "America/Edmonton\0"
  "America/Eirunepe\0"
  "America/El_Salvador\0"
  "America/Ensenada\0"
  "America/Fort_Nelson\0"
  "America/Fort_Wayne\0"
  "America/Fortaleza\0"
  "America/Glace_Bay\0"
  "America/Godthab\0"
  "America/Goose_Bay\0"
  "America/Grand_Turk\0"
  "America/Grenada\0"
  "America/Guadeloupe\0"
  "America/Guatemala\0"
  "America/Guayaquil\0"
  "America/Guyana\0"
  "America/Halifax\0"
  "America/Havana\0"
  "America/Hermosillo\0"
  "America/Indiana/Indianapolis\0"
  "America/Indiana/Knox\0"
  "America/Indiana/Marengo\0"
  "America/Indiana/Petersburg\0"
  "America/Indiana/Tell_City\0"
  "America/Indiana/Vevay\0"
  "America/Indiana/Vincennes\0"
  "America/Indiana/Winamac\0"
  "America/Indianapolis\0"
  "America/Inuvik\0"
  "America/Iqaluit\0"
  "America/Jamaica\0"
  "America/Jujuy\0"
  "America/Juneau\0"
  "America/Kentucky/Louisville\0"
  "America/Kentucky/Monticello\0"
  "America/Knox_IN\0"
  "America/Kralendijk\0"
  "America/La_Paz\0"
  "America/Lima\0"
  "America/Los_Angeles\0"
  "America/Louisville\0"
  "America/Lower_Princes\0"
  "America/Maceio\0"
  "America/Managua\0"
  "America/Manaus\0"
  "America/Marigot\0"
  "America/Martinique\0"
  "America/Matamoros\0"
  "America/Mazatlan\0"
  "America/Mendoza\0"
  "America/Menominee\0"
  "America/Merida\0"
  "America/Metlakatla\0"
  "America/Mexico_City\0"
  "America/Miquelon\0"
  "America/Moncton\0"
  "America/Monterrey\0"
  "America/Montevideo\0"
  "America/Montreal\0"
  "America/Montserrat\0"
  "America/Nassau\0"
  "America/New_York\0"
  "America/Nipigon\0"
  "America/Nome\0"
  "America/Noronha\0"
  "America/North_Dakota/Beulah\0"
  "America/North_Dakota/Center\0"
  "America/North_Dakota/New_Salem\0"
  "America/Nuuk\0"
  "America/Ojinaga\0"
  "America/Panama\0"
  "America/Pangnirtung\0"
  "America/Paramaribo\0"
  "America/Phoenix\0"
  "America/Port-au-Prince\0"
  "America/Port_of_Spain\0"
  "America/Porto_Acre\0"
  "America/Porto_Velho\0"
  "America/Puerto_Rico\0"
  "America/Punta_Arenas\0"
  "America/Rainy_River\0"
  "America/Rankin_Inlet\0"
  "America/Recife\0"
  "America/Regina\0"
  "America/Resolute\0"
  "America/Rio_Branco\0"
  "America/Rosario\0"
  "America/Santa_Isabel\0"
  "America/Santarem\0"
  "America/Santiago\0"
  "America/Santo_Domingo\0"
  "America/Sao_Paulo\0"
  "America/Scoresbysund\0"
  "America/Shiprock\0"
  "America/Sitka\0"
  "America/St_Barthelemy\0"
  "America/St_Johns\0"
  "America/St_Kitts\0"
  "America/St_Lucia\0"
  "America/St_Thomas\0"
  "America/St_Vincent\0"
  "America/Swift_Current\0"
  "America/Tegucigalpa\0"
  "America/Thule\0"
  "America/Thunder_Bay\0"
  "America/Tijuana\0"
  "America/Toronto\0"
  "America/Tortola\0"
  "America/Vancouver\0"
  "America/Virgin\0"
  "America/Whitehorse\0"
  "America/Winnipeg\0"
  "America/Yakutat\0"
  "America/Yellowknife\0"
  "Antarctica/Casey\0"
  "Antarctica/Davis\0"
  "Antarctica/DumontDUrville\0"
  "Antarctica/Macquarie\0"
  "Antarctica/Mawson\0"
  "Antarctica/McMurdo\0"
  "Antarctica/Palmer\0"
  "Antarctica/Rothera\0"
  "Antarctica/South_Pole\0"
  "Antarctica/Syowa\0"
  "Antarctica/Troll\0"
  "Antarctica/Vostok\0"
  "Arctic/Longyearbyen\0"
  "Asia/Aden\0"
  "Asia/Almaty\0"
  "Asia/Amman\0"
  "Asia/Anadyr\0"
  "Asia/Aqtau\0"
  "Asia/Aqtobe\0"
  "Asia/Ashgabat\0"
  "Asia/Ashkhabad\0"
  "Asia/Atyrau\0"
  "Asia/Baghdad\0"
  "Asia/Bahrain\0"
  "Asia/Baku\0"
  "Asia/Bangkok\0"
  "Asia/Barnaul\0"
  "Asia/Beirut\0"
  "Asia/Bishkek\0"
  "Asia/Brunei\0"
  "Asia/Calcutta\0"
  "Asia/Chita\0"
  "Asia/Choibalsan\0"
  "Asia/Chongqing\0"
  "Asia/Chungking\0"
  "Asia/Colombo\0"
  "Asia/Dacca\0"
  "Asia/Damascus\0"
  "Asia/Dhaka\0"
  "Asia/Dili\0"
  "Asia/Dubai\0"
  "Asia/Dushanbe\0"
  "Asia/Famagusta\0"
  "Asia/Gaza\0"
  "Asia/Harbin\0"
  "Asia/Hebron\0"
  "Asia/Ho_Chi_Minh\0"
  "Asia/Hong_Kong\0"
  "Asia/Hovd\0"
  "Asia/Irkutsk\0"
  "Asia/Istanbul\0"
  "Asia/Jakarta\0"
  "Asia/Jayapura\0"
  "Asia/Jerusalem\0"
  "Asia/Kabul\0"
  "Asia/Kamchatka\0"
  "Asia/Karachi\0"
  "Asia/Kashgar\0"
  "Asia/Kathmandu\0"
  "Asia/Katmandu\0"
  "Asia/Khandyga\0"
  "Asia/Kolkata\0"
  "Asia/Krasnoyarsk\0"
  "Asia/Kuala_Lumpur\0"
  "Asia/Kuching\0"
  "Asia/Kuwait\0"
  "Asia/Macao\0"
  "Asia/Macau\0"
  "Asia/Magadan\0"
  "Asia/Makassar\0"
  "Asia/Manila\0"
  "Asia/Muscat\0"
  "Asia/Nicosia\0"
  "Asia/Novokuznetsk\0"
  "Asia/Novosibirsk\0"
  "Asia/Omsk\0"
  "Asia/Oral\0"
  "Asia/Phnom_Penh\0"
  "Asia/Pontianak\0"
  "Asia/Pyongyang\0"
  "Asia/Qatar\0"
  "Asia/Qostanay\0"
  "Asia/Qyzylorda\0"
  "Asia/Rangoon\0"
  "Asia/Riyadh\0"
  "Asia/Saigon\0"
  "Asia/Sakhalin\0"
  "Asia/Samarkand\0"
  "Asia/Seoul\0"
  "Asia/Shanghai\0"
  "Asia/Singapore\0"
  "Asia/Srednekolymsk\0"
  "Asia/Taipei\0"
  "Asia/Tashkent\0"
  "Asia/Tbilisi\0"
  "Asia/Tehran\0"
  "Asia/Tel_Aviv\0"
  "Asia/Thimbu\0"
  "Asia/Thimphu\0"
  "Asia/Tokyo\0"
  "Asia/Tomsk\0"
  "Asia/Ujung_Pandang\0"
  "Asia/Ulaanbaatar\0"
  "Asia/Ulan_Bator\0"
  "Asia/Urumqi\0"
  "Asia/Ust-Nera\0"
  "Asia/Vientiane\0"
  "Asia/Vladivostok\0"
  "Asia/Yakutsk\0"
  "Asia/Yangon\0"
  "Asia/Yekaterinburg\0"
  "Asia/Yerevan\0"
  "Atlantic/Azores\0"
  "Atlantic/Bermuda\0"
  "Atlantic/Canary\0"
  "Atlantic/Cape_Verde\0"
  "Atlantic/Faeroe\0"
  "Atlantic/Faroe\0"
  "Atlantic/Jan_Mayen\0"
  "Atlantic/Madeira\0"
  "Atlantic/Reykjavik\0"
  "Atlantic/South_Georgia\0"
  "Atlantic/St_Helena\0"
  "Atlantic/Stanley\0"
  "Australia/ACT\0"
  "Australia/Adelaide\0"
  "Australia/Brisbane\0"
  "Australia/Broken_Hill\0"
  "Australia/Canberra\0"
  "Australia/Currie\0"
  "Australia/Darwin\0"
  "Australia/Eucla\0"
  "Australia/Hobart\0"
  "Australia/LHI\0"
  "Australia/Lindeman\0"
  "Australia/Lord_Howe\0"
  "Australia/Melbourne\0"
  "Australia/NSW\0"
  "Australia/North\0"
  "Australia/Perth\0"
  "Australia/Queensland\0"
  "Australia/South\0"
  "Australia/Sydney\0"
  "Australia/Tasmania\0"
  "Australia/Victoria\0"
  "Australia/West\0"
  "Australia/Yancowinna\0"
  "Europe/Amsterdam\0"
  "Europe/Andorra\0"
  "Europe/Astrakhan\0"
  "Europe/Athens\0"
  "Europe/Belfast\0"
  "Europe/Belgrade\0"
  "Europe/Berlin\0"
  "Europe/Bratislava\0"
  "Europe/Brussels\0"
  "Europe/Bucharest\0"
  "Europe/Budapest\0"
  "Europe/Busingen\0"
  "Europe/Chisinau\0"
  "Europe/Copenhagen\0"
  "Europe/Dublin\0"
  "Europe/Gibraltar\0"
  "Europe/Guernsey\0"
  "Europe/Helsinki\0"
  "Europe/Isle_of_Man\0"
  "Europe/Istanbul\0"
  "Europe/Jersey\0"
  "Europe/Kaliningrad\0"
  "Europe/Kiev\0"
  "Europe/Kirov\0"
  "Europe/Kyiv\0"
  "Europe/Lisbon\0"
  "Europe/Ljubljana\0"
  "Europe/London\0"
  "Europe/Luxembourg\0"
  "Europe/Madrid\0"
  "Europe/Malta\0"
  "Europe/Mariehamn\0"
  "Europe/Minsk\0"
  "Europe/Monaco\0"
  "Europe/Moscow\0"
  "Europe/Nicosia\0"
  "Europe/Oslo\0"
  "Europe/Paris\0"
  "Europe/Podgorica\0"
  "Europe/Prague\0"
  "Europe/Riga\0"
  "Europe/Rome\0"
  "Europe/Samara\0"
  "Europe/San_Marino\0"
  "Europe/Sarajevo\0"
  "Europe/Saratov\0"
  "Europe/Simferopol\0"
  "Europe/Skopje\0"
  "Europe/Sofia\0"
  "Europe/Stockholm\0"
  "Europe/Tallinn\0"
  "Europe/Tirane\0"
  "Europe/Tiraspol\0"
  "Europe/Ulyanovsk\0"
  "Europe/Uzhgorod\0"
  "Europe/Vaduz\0"
  "Europe/Vatican\0"
  "Europe/Vienna\0"
  "Europe/Vilnius\0"
  "Europe/Volgograd\0"
  "Europe/Warsaw\0"
  "Europe/Zagreb\0"
  "Europe/Zaporozhye\0"
  "Europe/Zurich\0"
  "Indian/Antananarivo\0"
  "Indian/Chagos\0"
  "Indian/Christmas\0"
  "Indian/Cocos\0"
  "Indian/Comoro\0"
  "Indian/Kerguelen\0"
  "Indian/Mahe\0"
  "Indian/Maldives\0"
  "Indian/Mauritius\0"
  "Indian/Mayotte\0"
  "Indian/Reunion\0"
  "Pacific/Apia\0"
  "Pacific/Auckland\0"
  "Pacific/Bougainville\0"
  "Pacific/Chatham\0"
  "Pacific/Chuuk\0"
  "Pacific/Easter\0"
  "Pacific/Efate\0"
  "Pacific/Enderbury\0"
  "Pacific/Fakaofo\0"
  "Pacific/Fiji\0"
  "Pacific/Funafuti\0"
  "Pacific/Galapagos\0"
  "Pacific/Gambier\0"
  "Pacific/Guadalcanal\0"
  "Pacific/Guam\0"
  "Pacific/Honolulu\0"
  "Pacific/Johnston\0"
  "Pacific/Kanton\0"
  "Pacific/Kiritimati\0"
  "Pacific/Kosrae\0"
  "Pacific/Kwajalein\0"
  "Pacific/Majuro\0"
  "Pacific/Marquesas\0"
  "Pacific/Midway\0"
  "Pacific/Nauru\0"
  "Pacific/Niue\0"
  "Pacific/Norfolk\0"
  "Pacific/Noumea\0"
  "Pacific/Pago_Pago\0"
  "Pacific/Palau\0"
  "Pacific/Pitcairn\0"
  "Pacific/Pohnpei\0"
  "Pacific/Ponape\0"
  "Pacific/Port_Moresby\0"
  "Pacific/Rarotonga\0"
  "Pacific/Saipan\0"
  "Pacific/Samoa\0"
  "Pacific/Tahiti\0"
  "Pacific/Tarawa\0"
  "Pacific/Tongatapu\0"
  "Pacific/Truk\0"
  "Pacific/Wake\0"
  "Pacific/Wallis\0"
  "Pacific/Yap\0"
;

// {name, posix}: byte offsets into the two blobs above.
static const uint16_t kTzIndex[TZDB_COUNT][2] = {
  {0, 975},
  {15, 975},
  {28, 816},
  {47, 714},
  {62, 816},
  {76, 816},
  {90, 975},
  {104, 1250},
  {118, 975},
  {132, 975},
  {146, 708},
  {162, 1250},
  {181, 708},
  {198, 917},
  {211, 0},
  {229, 720},
  {242, 975},
  {257, 975},
  {270, 816},
  {291, 816},
  {307, 1250},
  {321, 0},
  {337, 975},
  {353, 708},
  {369, 708},
  {383, 1237},
  {403, 708},
  {415, 816},
  {430, 708},
  {446, 708},
  {460, 1250},
  {476, 1250},
  {489, 1250},
  {507, 975},
  {519, 1250},
  {533, 708},
  {551, 708},
  {565, 1250},
  {579, 708},
  {593, 1237},
  {607, 1237},
  {622, 816},
  {639, 975},
  {655, 816},
  {670, 1250},
  {686, 1250},
  {700, 975},
  {718, 975},
  {737, 1250},
  {755, 975},
  {771, 975},
  {787, 822},
  {802, 714},
  {815, 708},
  {831, 1042},
  {844, 648},
  {862, 673},
  {879, 673},
  {895, 409},
  {913, 409},
  {944, 409},
  {972, 409},
  {1005, 409},
  {1031, 409},
  {1055, 409},
  {1082, 409},
  {1108, 409},
  {1139, 409},
  {1163, 409},
  {1190, 409},
  {1217, 409},
  {1243, 409},
  {1269, 673},
  {1283, 409},
  {1300, 947},
  {1317, 1042},
  {1330, 409},
  {1344, 780},
  {1367, 673},
  {1384, 409},
  {1398, 780},
  {1413, 673},
  {1434, 443},
  {1452, 482},
  {1467, 1125},
  {1481, 409},
  {1502, 1125},
  {1524, 443},
  {1545, 947},
  {1560, 443},
  {1576, 409},
  {1594, 409},
  {1610, 947},
  {1625, 785},
  {1641, 780},
  {1659, 1125},
  {1681, 947},
  {1703, 409},
  {1719, 780},
  {1738, 409},
  {1756, 1120},
  {1772, 443},
  {1787, 673},
  {1803, 975},
  {1824, 1120},
  {1839, 1120},
  {1860, 1125},
  {1875, 952},
  {1891, 673},
  {1908, 780},
  {1925, 482},
  {1942, 780},
  {1962, 1214},
  {1979, 1120},
  {1999, 952},
  {2018, 409},
  {2036, 678},
  {2054, 377},
  {2070, 678},
  {2088, 952},
  {2107, 673},
  {2123, 673},
  {2142, 780},
  {2160, 482},
  {2178, 443},
  {2193, 678},
  {2209, 753},
  {2224, 1120},
  {2243, 952},
  {2272, 785},
  {2293, 952},
  {2317, 952},
  {2344, 785},
  {2370, 952},
  {2392, 952},
  {2418, 952},
  {2442, 952},
  {2463, 1125},
  {2478, 952},
  {2494, 947},
  {2510, 409},
  {2524, 648},
  {2539, 952},
  {2567, 952},
  {2595, 785},
  {2611, 673},
  {2630, 443},
  {2645, 482},
  {2658, 1214},
  {2678, 952},
  {2697, 673},
  {2719, 409},
  {2734, 780},
  {2750, 443},
  {2765, 673},
  {2781, 673},
  {2800, 785},
  {2818, 1120},
  {2835, 409},
  {2851, 785},
  {2869, 780},
  {2884, 648},
  {2903, 780},
  {2923, 416},
  {2940, 678},
  {2956, 780},
  {2974, 409},
  {2993, 952},
  {3010, 673},
  {3029, 952},
  {3044, 952},
  {3061, 952},
  {3077, 648},
  {3090, 370},
  {3106, 785},
  {3134, 785},
  {3162, 785},
  {3193, 377},
  {3206, 785},
  {3222, 947},
  {3237, 952},
  {3257, 409},
  {3276, 1120},
  {3292, 952},
  {3315, 673},
  {3337, 482},
  {3356, 443},
  {3376, 673},
  {3396, 409},
  {3417, 785},
  {3437, 785},
  {3458, 409},
  {3473, 780},
  {3488, 785},
  {3505, 482},
  {3524, 409},
  {3540, 1214},
  {3561, 409},
  {3578, 450},
  {3595, 673},
  {3617, 409},
  {3635, 377},
  {3656, 1125},
  {3673, 648},
  {3687, 673},
  {3709, 1148},
  {3726, 673},
  {3743, 673},
  {3760, 673},
  {3778, 673},
  {3797, 780},
  {3819, 780},
  {3839, 678},
  {3853, 952},
  {3873, 1214},
  {3889, 952},
  {3905, 673},
  {3921, 1120},
  {3939, 673},
  {3954, 1120},
  {3973, 785},
  {3990, 648},
  {4006, 780},
  {4026, 158},
  {4043, 137},
  {4060, 211},
  {4086, 619},
  {4107, 108},
  {4125, 1174},
  {4144, 409},
  {4162, 409},
  {4181, 1174},
  {4203, 53},
  {4220, 7},
  {4237, 108},
  {4255, 720},
  {4275, 53},
  {4285, 108},
  {4297, 53},
  {4308, 305},
  {4320, 108},
  {4331, 108},
  {4343, 108},
  {4357, 108},
  {4372, 108},
  {4384, 53},
  {4397, 53},
  {4410, 74},
  {4420, 137},
  {4433, 137},
  {4446, 859},
  {4458, 129},
  {4471, 158},
  {4483, 1093},
  {4497, 166},
  {4508, 158},
  {4524, 747},
  {4539, 747},
  {4554, 82},
  {4567, 129},
  {4578, 53},
  {4592, 129},
  {4603, 166},
  {4613, 74},
  {4624, 108},
  {4638, 888},
  {4653, 828},
  {4663, 747},
  {4675, 828},
  {4687, 137},
  {4704, 1030},
  {4719, 137},
  {4729, 158},
  {4742, 53},
  {4756, 1282},
  {4769, 1288},
  {4783, 1066},
  {4798, 61},
  {4809, 305},
  {4824, 1202},
  {4837, 129},
  {4850, 95},
  {4865, 95},
  {4879, 166},
  {4893, 1093},
  {4906, 137},
  {4923, 158},
  {4941, 158},
  {4954, 53},
  {4966, 747},
  {4977, 747},
  {4988, 220},
  {5001, 1294},
  {5015, 1208},
  {5027, 74},
  {5039, 888},
  {5052, 137},
  {5070, 137},
  {5087, 129},
  {5097, 108},
  {5107, 137},
  {5123, 1282},
  {5138, 1108},
  {5153, 53},
  {5164, 108},
  {5178, 108},
  {5193, 116},
  {5206, 53},
  {5218, 137},
  {5230, 220},
  {5244, 108},
  {5259, 1108},
  {5270, 747},
  {5284, 158},
  {5299, 220},
  {5318, 747},
  {5330, 108},
  {5344, 74},
  {5357, 40},
  {5369, 1066},
  {5383, 129},
  {5395, 129},
  {5408, 1102},
  {5419, 137},
  {5430, 1294},
  {5449, 158},
  {5466, 158},
  {5482, 129},
  {5494, 211},
  {5508, 137},
  {5523, 211},
  {5540, 166},
  {5553, 116},
  {5565, 108},
  {5584, 74},
  {5597, 339},
  {5613, 678},
  {5630, 1256},
  {5646, 332},
  {5666, 1256},
  {5682, 1256},
  {5697, 720},
  {5716, 1256},
  {5733, 975},
  {5752, 370},
  {5775, 975},
  {5794, 409},
  {5811, 619},
  {5825, 580},
  {5844, 611},
  {5863, 580},
  {5885, 619},
  {5904, 619},
  {5921, 570},
  {5938, 145},
  {5954, 619},
  {5971, 174},
  {5985, 611},
  {6004, 174},
  {6024, 619},
  {6044, 619},
  {6058, 570},
  {6074, 701},
  {6090, 611},
  {6111, 580},
  {6127, 619},
  {6144, 619},
  {6163, 619},
  {6182, 701},
  {6197, 580},
  {6218, 720},
  {6235, 720},
  {6250, 74},
  {6267, 888},
  {6281, 980},
  {6296, 720},
  {6312, 720},
  {6326, 720},
  {6344, 720},
  {6360, 888},
  {6377, 720},
  {6393, 720},
  {6409, 888},
  {6425, 720},
  {6443, 1005},
  {6457, 720},
  {6474, 980},
  {6490, 888},
  {6506, 980},
  {6525, 53},
  {6541, 980},
  {6555, 822},
  {6574, 888},
  {6586, 1114},
  {6599, 888},
  {6611, 1256},
  {6625, 720},
  {6642, 980},
  {6656, 720},
  {6674, 720},
  {6688, 720},
  {6701, 888},
  {6718, 53},
  {6731, 720},
  {6745, 1114},
  {6759, 888},
  {6774, 720},
  {6786, 720},
  {6799, 720},
  {6816, 720},
  {6830, 888},
  {6842, 720},
  {6854, 74},
  {6868, 720},
  {6886, 720},
  {6902, 74},
  {6917, 1114},
  {6935, 720},
  {6949, 888},
  {6962, 720},
  {6979, 888},
  {6994, 720},
  {7008, 888},
  {7024, 74},
  {7041, 888},
  {7057, 720},
  {7070, 720},
  {7085, 720},
  {7099, 888},
  {7114, 1114},
  {7131, 720},
  {7145, 720},
  {7159, 888},
  {7177, 720},
  {7191, 816},
  {7211, 129},
  {7225, 137},
  {7242, 116},
  {7255, 816},
  {7269, 108},
  {7286, 74},
  {7298, 108},
  {7314, 74},
  {7331, 816},
  {7346, 74},
  {7361, 314},
  {7374, 1174},
  {7391, 220},
  {7412, 260},
  {7428, 211},
  {7442, 496},
  {7457, 220},
  {7471, 314},
  {7489, 314},
  {7505, 305},
  {7518, 305},
  {7535, 489},
  {7553, 547},
  {7569, 220},
  {7589, 808},
  {7602, 1036},
  {7619, 1036},
  {7636, 314},
  {7651, 323},
  {7670, 220},
  {7685, 305},
  {7703, 305},
  {7718, 535},
  {7736, 1244},
  {7751, 305},
  {7765, 562},
  {7778, 229},
  {7794, 220},
  {7809, 1244},
  {7827, 166},
  {7841, 528},
  {7858, 220},
  {7874, 220},
  {7889, 211},
  {7910, 554},
  {7928, 808},
  {7943, 1244},
  {7957, 554},
  {7972, 305},
  {7987, 314},
  {8005, 211},
  {8018, 305},
  {8031, 305},
  {8046, 211},
};
