#pragma once
// GENERATED by tools/luasim/gen_world.py - do not edit.
//
// Land mask for the world clock: Natural Earth 1:110m, public domain, sampled
// onto 64x32 dots. A dot is land if 2 of 9 points in its cell are.
// The Lua prototype in tools/luasim carries the same data from the same run.

#include <stdint.h>

#define WORLD_COLS 64
#define WORLD_ROWS 32
static const float WORLD_TOP = 78.0f, WORLD_BOTTOM = -58.0f;

// Bit c, counted from the least significant end, set = land at column c.
static const uint64_t kWorldMask[WORLD_ROWS] = {
  0x010F8C001FF3E800ULL,
  0x0FFFF2100FCFFE38ULL,
  0xFFFFFFFC1FDFFFFFULL,
  0xFFFFFFFE119FFFFEULL,
  0x3FFFFFF6801CFFFCULL,
  0x19FFFFFEC03FFF08ULL,
  0x01FFFFFF803FFE00ULL,
  0x01FFFFFF805FFC00ULL,
  0x02FFFFFFC00FFC00ULL,
  0x017FFFFBC007FC00ULL,
  0x01BFFFC7C003F800ULL,
  0x003FFFFFC003F800ULL,
  0x003FFFFFE0007000ULL,
  0x000FF7FFE00D6000ULL,
  0x002F63FFE001C000ULL,
  0x000E61FFE0090000ULL,
  0x006241FFE03E0000ULL,
  0x001601FE407C0000ULL,
  0x00FE00FE00FE0000ULL,
  0x03A4007C03FE0000ULL,
  0x0608007C03FC0000ULL,
  0x028001FC01FC0000ULL,
  0x03E0017C01F80000ULL,
  0x07F001FC01F80000ULL,
  0x0FF0003C00F80000ULL,
  0x0FF0003800780000ULL,
  0x0730001800780000ULL,
  0x8600000000380000ULL,
  0x44000000001C0000ULL,
  0x00000000000C0000ULL,
  0x00000000000C0000ULL,
  0x0000000000080000ULL,
};

struct WorldCity { const char *name; float lat, lon; };

// The first city is home, and it breathes.
static const WorldCity kWorldCities[] = {
  {"CANNES", 43.55f, 7.02f},
  {"MOSCOW", 55.75f, 37.62f},
  {"NEW YORK", 40.71f, -74.0f},
  {"LONDON", 51.51f, -0.13f},
  {"DUBAI", 25.2f, 55.27f},
  {"ALMATY", 43.24f, 76.89f},
};
#define WORLD_CITY_COUNT (sizeof(kWorldCities) / sizeof(kWorldCities[0]))
