#pragma once
// GENERATED by tools/luasim/gen_effects.py from tools/luasim/scripts/*.lua - do not edit.
//
// The Lua effects the panel carries, in the order the knob walks them. Edit a
// script and rerun the generator; the pre-commit hook refuses a stale copy.
// Not embedded:
//   cyrillic_test.lua: a test card for Latin and Cyrillic text, held to parity by fx_parity
//   demo.lua: a test card for the px.* API, not something to hang on a wall
//   sysfont_test.lua: a test card for px.text's fonts (5x7, pico), held to parity by fx_parity
//   world_clock.lua: already a native page drawing the same picture (src/worldclock, WORLDCLOCK_ENABLED); a second copy would show twice in the rotation
//   sent over the air instead, marked @upload-only: aquarium.lua, cannes.lua, football_clock.lua, la_gioconda.lua, minecraft.lua, room_radar.lua, snake_clock.lua, snooker_clock.lua, starship.lua, tetris_clock.lua

#include <stdint.h>

#define LUA_EFFECT_COUNT 0

// The sources are only compiled where the table is wanted (lua_effects.cpp);
// everyone else gets the count.
#if defined(LUA_EFFECTS_TABLE)

struct LuaEffectScript {
  const char *id;     // chunk name in error messages
  const char *name;   // shown in the banner
  const char *src;
  uint32_t    len;
};


static const LuaEffectScript kLuaEffectScripts[LUA_EFFECT_COUNT ? LUA_EFFECT_COUNT : 1] = {
  {"", "", "", 0},   // none compiled in: never read
};

#endif  // LUA_EFFECTS_TABLE
