#pragma once

// Picopixel with one glyph corrected. Shared by every page that draws
// small text: the flight board and the yacht radar.
//
// WHY. Picopixel's stock 'U' is 'V' with one extra #.# row: both end in a
// centred pixel, so at 2 mm pitch across a room ZURICH reads ZVRICH and
// EDINBURGH reads EDINBVRGH. That is the same failure that took TomThumb out
// of the running (its M and N differ by one pixel), and live Nice data hits it
// on roughly a quarter of destination rows.
//
// FIX. Give 'U' a flat bottom, which is the form Org_01 uses at 5 px wide:
//
//     stock      corrected
//     # . #      # . #
//     # . #      # . #
//     # . #      # . #
//     # . #      # . #
//     . # .      # # #
//
// Two bits set in the bitmap; the glyph table is the stock one, reused as-is,
// so metrics (w 3, advance 4) are untouched and layout maths does not move.
// Verified by decoding the shipped header with drawChar's own bit order and
// confirming every other glyph is byte-for-byte identical.
//
// Source font: Adafruit GFX Library, Fonts/Picopixel.h - Picopixel by
// Sebastian Weber. BSD licence, same as the rest of Adafruit GFX.

#include <Adafruit_GFX.h>
#include <Fonts/Picopixel.h>   // for PicopixelGlyphs, reused unchanged

const uint8_t PicopixelFBBitmaps[] PROGMEM = {
    0xE8,    0xB4,    0x57,    0xD5,    0xF5,    0x00,    0x4E,    0x3E,    0x80,    0xA5,    0x4A,    0x4A,
    0x5A,    0x50,    0xC0,    0x6A,    0x40,    0x95,    0x80,    0xAA,    0x80,    0x5D,    0x00,    0x60,
    0xE0,    0x80,    0x25,    0x48,    0x56,    0xD4,    0x75,    0x40,    0xC5,    0x4E,    0xC5,    0x1C,
    0x97,    0x92,    0xF3,    0x1C,    0x53,    0x54,    0xE5,    0x48,    0x55,    0x54,    0x55,    0x94,
    0xA0,    0x46,    0x64,    0xE3,    0x80,    0x98,    0xC5,    0x04,    0x56,    0xC6,    0x57,    0xDA,
    0xD7,    0x5C,    0x72,    0x46,    0xD6,    0xDC,    0xF3,    0xCE,    0xF3,    0x48,    0x72,    0xD4,
    0xB7,    0xDA,    0xF8,    0x24,    0xD4,    0xBB,    0x5A,    0x92,    0x4E,    0x8E,    0xEB,    0x58,
    0x80,    0x9D,    0xB9,    0x90,    0x56,    0xD4,    0xD7,    0x48,    0x56,    0xD4,    0x40,    0xD7,
    0x5A,    0x71,    0x1C,    0xE9,    0x24,    0xB6,    0xDE,    0xB6,    0xA4,    0x8C,    0x6B,    0x55,
    0x00,    0xB5,    0x5A,    0xB5,    0x24,    0xE5,    0x4E,    0xEA,    0xC0,    0x91,    0x12,    0xD5,
    0xC0,    0x54,    0xF0,    0x90,    0xC7,    0xF0,    0x93,    0x5E,    0x71,    0x80,    0x25,    0xDE,
    0x5E,    0x30,    0x6E,    0x80,    0x77,    0x9C,    0x93,    0x5A,    0xB8,    0x45,    0x60,    0x92,
    0xEA,    0xAA,    0x40,    0xD5,    0x6A,    0xD6,    0x80,    0x55,    0x00,    0xD7,    0x40,    0x75,
    0x90,    0xE8,    0x71,    0xE0,    0xBA,    0x40,    0xB5,    0x80,    0xB5,    0x00,    0x8D,    0x54,
    0xAA,    0x80,    0xAC,    0xE0,    0xE5,    0x70,    0x6A,    0x26,    0xFC,    0xC8,    0xAC,    0x5A};

const GFXfont PicopixelFB PROGMEM = {(uint8_t *)PicopixelFBBitmaps,
                                     (GFXglyph *)PicopixelGlyphs, 0x20, 0x7E, 7};

// ---- BEGIN GENERATED by tools/fonts/mkcyr.py - do not edit by hand ----
// Cyrillic, U+0400..U+045F: 184 bitmap bytes, 96 glyphs.
// Source: tools/fonts/mkcyr.py. Drawn through src/fonts/pxfb_text.h only.
const uint8_t PicopixelCyrBitmaps[] PROGMEM = {
    0xFF, 0xFE, 0xBF, 0x4E, 0x57, 0xDA, 0xF3, 0x5C, 0xD7, 0x5C, 0xF2, 0x48,
    0x65, 0x5F, 0x90, 0xF3, 0xCE, 0xAD, 0x5D, 0x5A, 0x80, 0xC5, 0x1C, 0x9B,
    0xD9, 0x90, 0x24, 0xEB, 0x98, 0x80, 0xBB, 0x5A, 0x75, 0x55, 0xD0, 0x8E,
    0xEB, 0x58, 0x80, 0xB7, 0xDA, 0x56, 0xD4, 0xF6, 0xDA, 0xD7, 0x48, 0x72,
    0x46, 0xE9, 0x24, 0xB5, 0x9C, 0x23, 0xAA, 0xE2, 0x00, 0xB5, 0x5A, 0xAA,
    0xAF, 0x10, 0xB7, 0x92, 0xAD, 0x6B, 0x5F, 0x80, 0xAA, 0xAA, 0xBF, 0x04,
    0xC4, 0x75, 0x70, 0x8C, 0x7B, 0x5E, 0x80, 0x93, 0xDE, 0xC5, 0x9C, 0x95,
    0x7B, 0x59, 0x00, 0x75, 0xDA, 0xC7, 0xF0, 0x73, 0xD4, 0xFA, 0xE0, 0xF2,
    0x40, 0x76, 0xFA, 0x5E, 0x30, 0xB6, 0x6B, 0xE8, 0xE0, 0xBF, 0xD0, 0xAA,
    0xFA, 0xB7, 0x50, 0x76, 0xD0, 0xBE, 0xD0, 0xBE, 0xD0, 0x55, 0x00, 0xF6,
    0xD0, 0xD7, 0x40, 0x71, 0x80, 0xE9, 0x20, 0xAC, 0xE0, 0x4A, 0xD4, 0x80,
    0xAA, 0x80, 0xB6, 0xF2, 0xB5, 0x90, 0xBF, 0xF0, 0xAE, 0xEF, 0x10, 0xC6,
    0x56, 0x9D, 0xBD, 0x9A, 0xE0, 0xCC, 0xE0, 0xAD, 0xDA, 0x75, 0xD0, 0xAA,
    0xE6, 0x9A, 0x6A, 0x40, 0x2B, 0xC8, 0x7A, 0x30, 0x71, 0xE0, 0xB8, 0xA3,
    0x2E, 0x45, 0x60, 0x6A, 0xBB, 0xAE, 0xBB, 0x9A, 0x6A, 0x32, 0xEA, 0xA8,
    0x55, 0x00, 0xB6, 0xF4,
};

const GFXglyph PicopixelCyrGlyphs[] PROGMEM = {
    {0, 3, 5, 4, 0, -4},  // U+0400 missing
    {2, 3, 5, 4, 0, -4},  // U+0401 Ё
    {0, 3, 5, 4, 0, -4},  // U+0402 missing
    {0, 3, 5, 4, 0, -4},  // U+0403 missing
    {0, 3, 5, 4, 0, -4},  // U+0404 missing
    {0, 3, 5, 4, 0, -4},  // U+0405 missing
    {0, 3, 5, 4, 0, -4},  // U+0406 missing
    {0, 3, 5, 4, 0, -4},  // U+0407 missing
    {0, 3, 5, 4, 0, -4},  // U+0408 missing
    {0, 3, 5, 4, 0, -4},  // U+0409 missing
    {0, 3, 5, 4, 0, -4},  // U+040A missing
    {0, 3, 5, 4, 0, -4},  // U+040B missing
    {0, 3, 5, 4, 0, -4},  // U+040C missing
    {0, 3, 5, 4, 0, -4},  // U+040D missing
    {0, 3, 5, 4, 0, -4},  // U+040E missing
    {0, 3, 5, 4, 0, -4},  // U+040F missing
    {4, 3, 5, 4, 0, -4},  // U+0410 А
    {6, 3, 5, 4, 0, -4},  // U+0411 Б
    {8, 3, 5, 4, 0, -4},  // U+0412 В
    {10, 3, 5, 4, 0, -4},  // U+0413 Г
    {12, 4, 5, 5, 0, -4},  // U+0414 Д
    {15, 3, 5, 4, 0, -4},  // U+0415 Е
    {17, 5, 5, 6, 0, -4},  // U+0416 Ж
    {21, 3, 5, 4, 0, -4},  // U+0417 З
    {23, 4, 5, 5, 0, -4},  // U+0418 И
    {26, 5, 5, 6, 0, -4},  // U+0419 Й
    {30, 3, 5, 4, 0, -4},  // U+041A К
    {32, 4, 5, 5, 0, -4},  // U+041B Л
    {35, 5, 5, 6, 0, -4},  // U+041C М
    {39, 3, 5, 4, 0, -4},  // U+041D Н
    {41, 3, 5, 4, 0, -4},  // U+041E О
    {43, 3, 5, 4, 0, -4},  // U+041F П
    {45, 3, 5, 4, 0, -4},  // U+0420 Р
    {47, 3, 5, 4, 0, -4},  // U+0421 С
    {49, 3, 5, 4, 0, -4},  // U+0422 Т
    {51, 3, 5, 4, 0, -4},  // U+0423 У
    {53, 5, 5, 6, 0, -4},  // U+0424 Ф
    {57, 3, 5, 4, 0, -4},  // U+0425 Х
    {59, 4, 5, 5, 0, -4},  // U+0426 Ц
    {62, 3, 5, 4, 0, -4},  // U+0427 Ч
    {64, 5, 5, 6, 0, -4},  // U+0428 Ш
    {68, 6, 5, 7, 0, -4},  // U+0429 Щ
    {72, 4, 5, 5, 0, -4},  // U+042A Ъ
    {75, 5, 5, 6, 0, -4},  // U+042B Ы
    {79, 3, 5, 4, 0, -4},  // U+042C Ь
    {81, 3, 5, 4, 0, -4},  // U+042D Э
    {83, 5, 5, 6, 0, -4},  // U+042E Ю
    {87, 3, 5, 4, 0, -4},  // U+042F Я
    {89, 3, 4, 4, 0, -3},  // U+0430 а
    {91, 3, 5, 4, 0, -4},  // U+0431 б
    {93, 3, 4, 4, 0, -3},  // U+0432 в
    {95, 3, 4, 4, 0, -3},  // U+0433 г
    {97, 3, 5, 4, 0, -3},  // U+0434 д
    {99, 3, 4, 4, 0, -3},  // U+0435 е
    {101, 4, 4, 5, 0, -3},  // U+0436 ж
    {103, 3, 4, 4, 0, -3},  // U+0437 з
    {105, 3, 4, 4, 0, -3},  // U+0438 и
    {107, 3, 5, 4, 0, -4},  // U+0439 й
    {109, 3, 4, 4, 0, -3},  // U+043A к
    {111, 3, 4, 4, 0, -3},  // U+043B л
    {113, 3, 4, 4, 0, -3},  // U+043C м
    {115, 3, 4, 4, 0, -3},  // U+043D н
    {117, 3, 3, 4, 0, -2},  // U+043E о
    {119, 3, 4, 4, 0, -3},  // U+043F п
    {121, 3, 4, 4, 0, -2},  // U+0440 р
    {123, 3, 3, 4, 0, -2},  // U+0441 с
    {125, 3, 4, 4, 0, -3},  // U+0442 т
    {127, 3, 4, 4, 0, -2},  // U+0443 у
    {129, 3, 6, 4, 0, -4},  // U+0444 ф
    {132, 3, 3, 4, 0, -2},  // U+0445 х
    {134, 3, 5, 4, 0, -3},  // U+0446 ц
    {136, 3, 4, 4, 0, -3},  // U+0447 ч
    {138, 3, 4, 4, 0, -3},  // U+0448 ш
    {140, 4, 5, 5, 0, -3},  // U+0449 щ
    {143, 4, 4, 5, 0, -3},  // U+044A ъ
    {145, 4, 4, 5, 0, -3},  // U+044B ы
    {147, 3, 4, 4, 0, -3},  // U+044C ь
    {149, 3, 4, 4, 0, -3},  // U+044D э
    {151, 4, 4, 5, 0, -3},  // U+044E ю
    {153, 3, 4, 4, 0, -3},  // U+044F я
    {0, 3, 5, 4, 0, -4},  // U+0450 missing
    {155, 3, 5, 4, 0, -4},  // U+0451 ё
    {157, 3, 6, 4, 0, -4},  // U+0452 ђ
    {160, 3, 5, 4, 0, -4},  // U+0453 ѓ
    {162, 3, 4, 4, 0, -3},  // U+0454 є
    {164, 3, 4, 4, 0, -3},  // U+0455 ѕ
    {166, 1, 5, 2, 0, -4},  // U+0456 і
    {167, 3, 5, 4, 0, -4},  // U+0457 ї
    {169, 2, 6, 3, 0, -4},  // U+0458 ј
    {171, 4, 4, 5, 0, -3},  // U+0459 љ
    {173, 4, 4, 5, 0, -3},  // U+045A њ
    {175, 3, 5, 4, 0, -4},  // U+045B ћ
    {177, 3, 5, 4, 0, -4},  // U+045C ќ
    {0, 3, 5, 4, 0, -4},  // U+045D missing
    {179, 3, 6, 4, 0, -4},  // U+045E ў
    {182, 3, 5, 4, 0, -3},  // U+045F џ
};

const GFXfont PicopixelCyr PROGMEM = {(uint8_t *)PicopixelCyrBitmaps,
                                      (GFXglyph *)PicopixelCyrGlyphs, 0x0400, 0x045F, 7};

// Drawn for any code point the panel has no glyph for.
const GFXglyph PicopixelMissingGlyph PROGMEM = {0, 3, 5, 4, 0, -4};
// ---- END GENERATED ----
