#pragma once

// Picopixel with one glyph corrected. Shared by every page that draws
// small text: the flight board and the yacht radar.
//
// WHY. Picopixel's stock 'U' is 'V' with one extra #.# row: both end in a
// centred pixel, so at 2 mm pitch across a room ZURICH reads ZVRICH and
// EDINBURGH reads EDINBVRGH. That is the same failure that took TomThumb out
// of the running (its M and N differ by one pixel), and live Nice data hits it
// on roughly a quarter of destination rows.
//
// FIX. Give 'U' a flat bottom, which is the form Org_01 uses at 5 px wide:
//
//     stock      corrected
//     # . #      # . #
//     # . #      # . #
//     # . #      # . #
//     # . #      # . #
//     . # .      # # #
//
// Two bits set in the bitmap; the glyph table is the stock one, reused as-is,
// so metrics (w 3, advance 4) are untouched and layout maths does not move.
// Verified by decoding the shipped header with drawChar's own bit order and
// confirming every other glyph is byte-for-byte identical.
//
// Source font: Adafruit GFX Library, Fonts/Picopixel.h - Picopixel by
// Sebastian Weber. BSD licence, same as the rest of Adafruit GFX.

#include <Adafruit_GFX.h>
#include <Fonts/Picopixel.h>   // for PicopixelGlyphs, reused unchanged

const uint8_t PicopixelFBBitmaps[] PROGMEM = {
    0xE8,    0xB4,    0x57,    0xD5,    0xF5,    0x00,    0x4E,    0x3E,    0x80,    0xA5,    0x4A,    0x4A,
    0x5A,    0x50,    0xC0,    0x6A,    0x40,    0x95,    0x80,    0xAA,    0x80,    0x5D,    0x00,    0x60,
    0xE0,    0x80,    0x25,    0x48,    0x56,    0xD4,    0x75,    0x40,    0xC5,    0x4E,    0xC5,    0x1C,
    0x97,    0x92,    0xF3,    0x1C,    0x53,    0x54,    0xE5,    0x48,    0x55,    0x54,    0x55,    0x94,
    0xA0,    0x46,    0x64,    0xE3,    0x80,    0x98,    0xC5,    0x04,    0x56,    0xC6,    0x57,    0xDA,
    0xD7,    0x5C,    0x72,    0x46,    0xD6,    0xDC,    0xF3,    0xCE,    0xF3,    0x48,    0x72,    0xD4,
    0xB7,    0xDA,    0xF8,    0x24,    0xD4,    0xBB,    0x5A,    0x92,    0x4E,    0x8E,    0xEB,    0x58,
    0x80,    0x9D,    0xB9,    0x90,    0x56,    0xD4,    0xD7,    0x48,    0x56,    0xD4,    0x40,    0xD7,
    0x5A,    0x71,    0x1C,    0xE9,    0x24,    0xB6,    0xDE,    0xB6,    0xA4,    0x8C,    0x6B,    0x55,
    0x00,    0xB5,    0x5A,    0xB5,    0x24,    0xE5,    0x4E,    0xEA,    0xC0,    0x91,    0x12,    0xD5,
    0xC0,    0x54,    0xF0,    0x90,    0xC7,    0xF0,    0x93,    0x5E,    0x71,    0x80,    0x25,    0xDE,
    0x5E,    0x30,    0x6E,    0x80,    0x77,    0x9C,    0x93,    0x5A,    0xB8,    0x45,    0x60,    0x92,
    0xEA,    0xAA,    0x40,    0xD5,    0x6A,    0xD6,    0x80,    0x55,    0x00,    0xD7,    0x40,    0x75,
    0x90,    0xE8,    0x71,    0xE0,    0xBA,    0x40,    0xB5,    0x80,    0xB5,    0x00,    0x8D,    0x54,
    0xAA,    0x80,    0xAC,    0xE0,    0xE5,    0x70,    0x6A,    0x26,    0xFC,    0xC8,    0xAC,    0x5A};

const GFXfont PicopixelFB PROGMEM = {(uint8_t *)PicopixelFBBitmaps,
                                     (GFXglyph *)PicopixelGlyphs, 0x20, 0x7E, 7};

// ---- BEGIN GENERATED by tools/fonts/mkcyr.py - do not edit by hand ----
// Cyrillic, U+0400..U+045F: 88 bitmap bytes, 96 glyphs.
// Source: tools/fonts/mkcyr.py. Drawn through src/fonts/pxfb_text.h only.
const uint8_t PicopixelCyrBitmaps[] PROGMEM = {
    0xFF, 0xFE, 0xBF, 0x4E, 0x57, 0xDA, 0xF3, 0x5C, 0xD7, 0x5C, 0xF2, 0x48,
    0x65, 0x5F, 0x90, 0xF3, 0xCE, 0xAD, 0x5D, 0x5A, 0x80, 0xC5, 0x1C, 0x9B,
    0xD9, 0x90, 0x69, 0xBD, 0x90, 0xBB, 0x5A, 0x75, 0x55, 0xD0, 0x8E, 0xEB,
    0x58, 0x80, 0xB7, 0xDA, 0x56, 0xD4, 0xF6, 0xDA, 0xD7, 0x48, 0x72, 0x46,
    0xE9, 0x24, 0xB5, 0x9C, 0x23, 0xAA, 0xE2, 0x00, 0xB5, 0x5A, 0xAA, 0xAF,
    0x10, 0xB7, 0x92, 0xAD, 0x6B, 0x5F, 0x80, 0xAA, 0xAA, 0xBF, 0x04, 0xC4,
    0x75, 0x70, 0x8C, 0x7B, 0x5E, 0x80, 0x93, 0xDE, 0xC5, 0x9C, 0x95, 0x7B,
    0x59, 0x00, 0x75, 0xDA,
};

const GFXglyph PicopixelCyrGlyphs[] PROGMEM = {
    {0, 3, 5, 4, 0, -4},  // U+0400 missing
    {2, 3, 5, 4, 0, -4},  // U+0401 Ё
    {0, 3, 5, 4, 0, -4},  // U+0402 missing
    {0, 3, 5, 4, 0, -4},  // U+0403 missing
    {0, 3, 5, 4, 0, -4},  // U+0404 missing
    {0, 3, 5, 4, 0, -4},  // U+0405 missing
    {0, 3, 5, 4, 0, -4},  // U+0406 missing
    {0, 3, 5, 4, 0, -4},  // U+0407 missing
    {0, 3, 5, 4, 0, -4},  // U+0408 missing
    {0, 3, 5, 4, 0, -4},  // U+0409 missing
    {0, 3, 5, 4, 0, -4},  // U+040A missing
    {0, 3, 5, 4, 0, -4},  // U+040B missing
    {0, 3, 5, 4, 0, -4},  // U+040C missing
    {0, 3, 5, 4, 0, -4},  // U+040D missing
    {0, 3, 5, 4, 0, -4},  // U+040E missing
    {0, 3, 5, 4, 0, -4},  // U+040F missing
    {4, 3, 5, 4, 0, -4},  // U+0410 А
    {6, 3, 5, 4, 0, -4},  // U+0411 Б
    {8, 3, 5, 4, 0, -4},  // U+0412 В
    {10, 3, 5, 4, 0, -4},  // U+0413 Г
    {12, 4, 5, 5, 0, -4},  // U+0414 Д
    {15, 3, 5, 4, 0, -4},  // U+0415 Е
    {17, 5, 5, 6, 0, -4},  // U+0416 Ж
    {21, 3, 5, 4, 0, -4},  // U+0417 З
    {23, 4, 5, 5, 0, -4},  // U+0418 И
    {26, 4, 5, 5, 0, -4},  // U+0419 Й
    {29, 3, 5, 4, 0, -4},  // U+041A К
    {31, 4, 5, 5, 0, -4},  // U+041B Л
    {34, 5, 5, 6, 0, -4},  // U+041C М
    {38, 3, 5, 4, 0, -4},  // U+041D Н
    {40, 3, 5, 4, 0, -4},  // U+041E О
    {42, 3, 5, 4, 0, -4},  // U+041F П
    {44, 3, 5, 4, 0, -4},  // U+0420 Р
    {46, 3, 5, 4, 0, -4},  // U+0421 С
    {48, 3, 5, 4, 0, -4},  // U+0422 Т
    {50, 3, 5, 4, 0, -4},  // U+0423 У
    {52, 5, 5, 6, 0, -4},  // U+0424 Ф
    {56, 3, 5, 4, 0, -4},  // U+0425 Х
    {58, 4, 5, 5, 0, -4},  // U+0426 Ц
    {61, 3, 5, 4, 0, -4},  // U+0427 Ч
    {63, 5, 5, 6, 0, -4},  // U+0428 Ш
    {67, 6, 5, 7, 0, -4},  // U+0429 Щ
    {71, 4, 5, 5, 0, -4},  // U+042A Ъ
    {74, 5, 5, 6, 0, -4},  // U+042B Ы
    {78, 3, 5, 4, 0, -4},  // U+042C Ь
    {80, 3, 5, 4, 0, -4},  // U+042D Э
    {82, 5, 5, 6, 0, -4},  // U+042E Ю
    {86, 3, 5, 4, 0, -4},  // U+042F Я
    {4, 3, 5, 4, 0, -4},  // U+0430 а
    {6, 3, 5, 4, 0, -4},  // U+0431 б
    {8, 3, 5, 4, 0, -4},  // U+0432 в
    {10, 3, 5, 4, 0, -4},  // U+0433 г
    {12, 4, 5, 5, 0, -4},  // U+0434 д
    {15, 3, 5, 4, 0, -4},  // U+0435 е
    {17, 5, 5, 6, 0, -4},  // U+0436 ж
    {21, 3, 5, 4, 0, -4},  // U+0437 з
    {23, 4, 5, 5, 0, -4},  // U+0438 и
    {26, 4, 5, 5, 0, -4},  // U+0439 й
    {29, 3, 5, 4, 0, -4},  // U+043A к
    {31, 4, 5, 5, 0, -4},  // U+043B л
    {34, 5, 5, 6, 0, -4},  // U+043C м
    {38, 3, 5, 4, 0, -4},  // U+043D н
    {40, 3, 5, 4, 0, -4},  // U+043E о
    {42, 3, 5, 4, 0, -4},  // U+043F п
    {44, 3, 5, 4, 0, -4},  // U+0440 р
    {46, 3, 5, 4, 0, -4},  // U+0441 с
    {48, 3, 5, 4, 0, -4},  // U+0442 т
    {50, 3, 5, 4, 0, -4},  // U+0443 у
    {52, 5, 5, 6, 0, -4},  // U+0444 ф
    {56, 3, 5, 4, 0, -4},  // U+0445 х
    {58, 4, 5, 5, 0, -4},  // U+0446 ц
    {61, 3, 5, 4, 0, -4},  // U+0447 ч
    {63, 5, 5, 6, 0, -4},  // U+0448 ш
    {67, 6, 5, 7, 0, -4},  // U+0449 щ
    {71, 4, 5, 5, 0, -4},  // U+044A ъ
    {74, 5, 5, 6, 0, -4},  // U+044B ы
    {78, 3, 5, 4, 0, -4},  // U+044C ь
    {80, 3, 5, 4, 0, -4},  // U+044D э
    {82, 5, 5, 6, 0, -4},  // U+044E ю
    {86, 3, 5, 4, 0, -4},  // U+044F я
    {0, 3, 5, 4, 0, -4},  // U+0450 missing
    {2, 3, 5, 4, 0, -4},  // U+0451 ё
    {0, 3, 5, 4, 0, -4},  // U+0452 missing
    {0, 3, 5, 4, 0, -4},  // U+0453 missing
    {0, 3, 5, 4, 0, -4},  // U+0454 missing
    {0, 3, 5, 4, 0, -4},  // U+0455 missing
    {0, 3, 5, 4, 0, -4},  // U+0456 missing
    {0, 3, 5, 4, 0, -4},  // U+0457 missing
    {0, 3, 5, 4, 0, -4},  // U+0458 missing
    {0, 3, 5, 4, 0, -4},  // U+0459 missing
    {0, 3, 5, 4, 0, -4},  // U+045A missing
    {0, 3, 5, 4, 0, -4},  // U+045B missing
    {0, 3, 5, 4, 0, -4},  // U+045C missing
    {0, 3, 5, 4, 0, -4},  // U+045D missing
    {0, 3, 5, 4, 0, -4},  // U+045E missing
    {0, 3, 5, 4, 0, -4},  // U+045F missing
};

const GFXfont PicopixelCyr PROGMEM = {(uint8_t *)PicopixelCyrBitmaps,
                                      (GFXglyph *)PicopixelCyrGlyphs, 0x0400, 0x045F, 7};

// Drawn for any code point the panel has no glyph for.
const GFXglyph PicopixelMissingGlyph PROGMEM = {0, 3, 5, 4, 0, -4};
// ---- END GENERATED ----
