#pragma once
// GENERATED by tools/yr_coastline_gen.py - do not edit.
//
// Bay of Cannes coastline, 125 points in 9 segments, already
// projected into the 64x64 radar panel: centre (31,32), outer ring 31 px
// = 1900 DAC = 6.33 km. Row 0 is the top of the framebuffer, so y is
// flipped relative to the north-up DAC space it came from.
//
// Origin: NickoScope32 fx34_yacht_radar.cpp, itself derived from
// gregoiredavid/france-geojson and clipped to the radar frame.

#include <stdint.h>

#define YR_COAST_SEGS   9
#define YR_COAST_POINTS 125

// high bit = closed loop, low 15 bits = point count
static const uint16_t kYrCoastSeg[YR_COAST_SEGS] = {
  0x0023, 0x801A, 0x800C, 0x0008, 0x0022, 0x0004, 0x0002, 0x0002, 0x0002
};

static const int8_t kYrCoastXY[YR_COAST_POINTS * 2] = {
  // #0  35 pts
   51,  7,  51,  8,  49,  8,  48,  8,  46, 10,  45, 11,  45, 11,  44, 13,
   44, 14,  44, 15,  43, 14,  43, 13,  43, 13,  42, 12,  43, 11,  42, 10,
   42,  9,  40,  7,  38,  7,  36,  6,  36,  7,  36,  6,  34,  6,  34,  7,
   34,  8,  32,  7,  31,  7,  27,  7,  24,  7,  23,  8,  22,  8,  18,  9,
   15, 11,  13, 12,  11, 13,
  // #1  26 pts  closed
   56, 26,  55, 26,  53, 25,  53, 25,  51, 25,  49, 25,  48, 25,  46, 25,
   43, 24,  42, 22,  42, 21,  43, 22,  44, 22,  45, 22,  46, 21,  46, 20,
   48, 21,  50, 22,  51, 23,  52, 22,  53, 23,  54, 23,  55, 23,  57, 24,
   57, 25,  56, 25,
  // #2  12 pts  closed
   48, 31,  48, 31,  46, 30,  45, 30,  44, 30,  44, 29,  45, 29,  48, 28,
   49, 29,  51, 29,  51, 30,  49, 30,
  // #3  8 pts
    9, 17,   9, 18,   9, 19,   8, 19,   7, 21,   6, 22,   6, 23,   6, 24,
  // #4  34 pts
    4, 27,   4, 28,   5, 29,   6, 29,   6, 30,   8, 30,   9, 30,  10, 30,
   11, 31,  11, 32,  12, 33,  11, 34,  11, 34,  12, 35,  11, 36,  10, 36,
    9, 37,   9, 38,   8, 38,   8, 40,   9, 40,   9, 42,   8, 42,   8, 43,
    6, 42,   6, 42,   5, 42,   4, 42,   2, 42,   2, 43,   2, 44,   3, 44,
    1, 44,   0, 44,
  // #5  4 pts
   55,  1,  54,  2,  54,  4,  53,  5,
  // #6  2 pts
    6, 24,   4, 27,
  // #7  2 pts
   51,  7,  53,  5,
  // #8  2 pts
   11, 13,   9, 17,
};
