#pragma once
// GENERATED by tools/yr_coastline_gen.py - do not edit.
//
// Bay of Cannes coastline, 125 points in 9 segments, in the DAC
// space fx34 clipped them to: north-up, outer ring 1900 DAC = 6.33 km.
//
// Deliberately NOT pre-rounded to panel pixels. The renderer projects and
// anti-aliases at draw time, so the sub-pixel position of every point survives
// into the brightness of the pixels it lights - which is the only resolution a
// 64 px map has left to spend.
//
// Origin: NickoScope32 fx34_yacht_radar.cpp, itself derived from
// gregoiredavid/france-geojson and clipped to the radar frame.

#include <stdint.h>

#define YR_COAST_SEGS   9
#define YR_COAST_POINTS 125

// high bit = closed loop, low 15 bits = point count
static const uint16_t kYrCoastSeg[YR_COAST_SEGS] = {
  0x0023, 0x801A, 0x800C, 0x0008, 0x0022, 0x0004, 0x0002, 0x0002, 0x0002
};

static const int16_t kYrCoastXY[YR_COAST_POINTS * 2] = {
  // #0  35 pts
   1234, 1502,  1203, 1473,  1120, 1454,  1051, 1455,   932, 1334,   870, 1306,
    850, 1276,   817, 1142,   827, 1101,   793, 1059,   750, 1096,   764, 1138,
    737, 1183,   677, 1213,   710, 1311,   659, 1375,   667, 1431,   523, 1523,
    452, 1551,   332, 1565,   289, 1517,   280, 1595,   188, 1586,   193, 1513,
    173, 1478,    89, 1508,   -24, 1524,  -273, 1532,  -430, 1517,  -493, 1492,
   -556, 1490,  -803, 1418, -1009, 1308, -1114, 1229, -1208, 1141,
  // #1  26 pts  closed
   1505,  356,  1493,  394,  1360,  430,  1338,  409,  1255,  420,  1074,  429,
   1044,  412,   931,  423,   745,  484,   644,  602,   659,  683,   721,  639,
    780,  618,   845,  636,   902,  688,   945,  705,  1050,  693,  1169,  601,
   1231,  582,  1271,  590,  1358,  566,  1419,  571,  1472,  522,  1596,  480,
   1569,  430,  1527,  431,
  // #2  12 pts  closed
   1037,   50,  1022,   76,   939,   96,   855,   98,   777,  127,   778,  184,
    834,  201,  1024,  215,  1131,  199,  1222,  161,  1199,  125,  1105,  112,
  // #3  8 pts
  -1377,  935, -1326,  880, -1331,  823, -1431,  775, -1487,  675, -1534,  619,
  -1540,  542, -1560,  485,
  // #4  34 pts
  -1630,  322, -1627,  216, -1577,  188, -1536,  188, -1513,  135, -1411,   97,
  -1319,   92, -1273,  108, -1222,   74, -1217,  -15, -1162,  -73, -1206, -109,
  -1212, -149, -1182, -202, -1224, -228, -1302, -219, -1340, -279, -1351, -367,
  -1385, -395, -1403, -480, -1371, -518, -1364, -586, -1423, -612, -1433, -669,
  -1506, -606, -1528, -623, -1603, -613, -1654, -626, -1751, -623, -1790, -647,
  -1780, -734, -1726, -766, -1863, -731, -1900, -729,
  // #5  4 pts
   1474, 1900,  1425, 1819,  1385, 1727,  1323, 1670,
  // #6  2 pts
  -1560,  485, -1630,  322,
  // #7  2 pts
   1234, 1502,  1323, 1670,
  // #8  2 pts
  -1208, 1141, -1377,  935,
};
