#!/usr/bin/env python3
"""Write the land mask and the city list into the Lua prototype AND the firmware.

One source for both, so the simulator and the panel cannot come to disagree
about where the land is or which cities get a dot. Edit CITIES here and rerun.
A city's zone is its IANA name; the POSIX string written next to it comes
from src/worldclock/tzdb.h (gen_tz.py), the table the portal's search uses.


Source: Natural Earth 1:110m land, public domain. Each of the 64x32 dots
covers a 5.6 x 4.25 degree cell; it is land if at least 2 of 9 sample points
inside the cell are. Sampling only the centre loses Italy, Japan and the UK,
and sampling any-of-9 bloats every coastline - 2 of 9 is where the continents
stay recognisable at this size.

  python3 gen_world.py           regenerate both
  python3 gen_world.py --check   offline: do the two copies and CITIES agree?
"""
import json, pathlib, re, sys, urllib.request

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from gen_tz import load as tz_table
SRC  = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
CACHE = pathlib.Path("/tmp/ne_110m_land.geojson")
SCRIPT = HERE / "scripts/world_clock.lua"
HEADER = HERE.parent.parent / "src/worldclock/worldmap.h"

# Built in, and never deletable from the portal. Which one is home is decided
# at run time (src/worldclock/README.md); the prototype takes the first.
CITIES = [
    ("CANNES",   43.55,   7.02, "Europe/Paris"),
    ("MOSCOW",   55.75,  37.62, "Europe/Moscow"),
    ("NEW YORK", 40.71, -74.00, "America/New_York"),
    ("LONDON",   51.51,  -0.13, "Europe/London"),
    ("DUBAI",    25.20,  55.27, "Asia/Dubai"),
    ("ALMATY",   43.24,  76.89, "Asia/Almaty"),
]
TZ = tz_table()
missing = [z for *_, z in CITIES if z not in TZ]
if missing:
    sys.exit(f"gen_world: not in tzdb.h: {', '.join(missing)}")
COLS, ROWS, TOP, BOT, THRESH = 64, 32, 78.0, -58.0, 2

if "--check" in sys.argv:
    # No network and no regeneration: the pre-commit hook only needs to know
    # that the Lua script, the firmware header and CITIES above still agree.
    lua, hdr = SCRIPT.read_text(), HEADER.read_text()
    rows  = re.findall(r'^\s*"([.#]{%d})",' % COLS, lua, re.M)
    words = [int(h, 16) for h in re.findall(r"0x([0-9A-F]{16})ULL", hdr)]
    want  = [sum(1 << c for c, ch in enumerate(s) if ch == "#") for s in rows]
    lua_c = [(n, float(a), float(b), z) for n, a, b, z in
             re.findall(r'name = "([^"]+)", lat = ([-\d.]+), lon = ([-\d.]+), tz = "([^"]+)"', lua)]
    hdr_c = [(n, float(a), float(b), i, z) for n, a, b, i, z in
             re.findall(r'\{"([^"]+)", ([-\d.]+)f, ([-\d.]+)f, "([^"]+)", "([^"]+)"\}', hdr)]
    problems = []
    if len(rows) != ROWS or want != words: problems.append("land mask differs between Lua and header")
    if lua_c != [(n, a, b, TZ[z]) for n, a, b, z in CITIES]: problems.append("cities in world_clock.lua differ from CITIES")
    if hdr_c != [(n, a, b, z, TZ[z]) for n, a, b, z in CITIES]: problems.append("cities in worldmap.h differ from CITIES")
    for p in problems: print("gen_world --check:", p)
    if not problems: print(f"gen_world --check: {ROWS} rows and {len(CITIES)} cities agree")
    sys.exit(1 if problems else 0)

if not CACHE.exists():
    urllib.request.urlretrieve(SRC, CACHE)
d = json.loads(CACHE.read_text())
rings = [f["geometry"]["coordinates"][0] for f in d["features"]]
boxes = [(min(p[0] for p in r), max(p[0] for p in r), min(p[1] for p in r), max(p[1] for p in r)) for r in rings]

def land(lon, lat):
    for ring, (x0, x1, y0, y1) in zip(rings, boxes):
        if not (x0 <= lon <= x1 and y0 <= lat <= y1):
            continue
        inside, j = False, len(ring) - 1
        for i in range(len(ring)):
            xi, yi = ring[i]; xj, yj = ring[j]
            if (yi > lat) != (yj > lat) and lon < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
        if inside:
            return True
    return False

dl, dp = 360 / COLS, (TOP - BOT) / ROWS
rows = []
for r in range(ROWS):
    s = ""
    for c in range(COLS):
        n = sum(land(-180 + (c + (a + .5) / 3) * dl, TOP - (r + (b + .5) / 3) * dp)
                for a in range(3) for b in range(3))
        s += "#" if n >= THRESH else "."
    rows.append(s)

block = ("-- BEGIN WORLD MASK - generated by tools/luasim/gen_world.py, do not edit\n"
         "local MASK = {\n" + "".join(f'  "{s}",\n' for s in rows) + "}\n"
         f"local MASK_TOP, MASK_BOTTOM = {TOP}, {BOT}\n"
         "-- Cities worth a dot, each with its zone as a POSIX TZ string.\n"
         "local CITIES = {\n" +
         "".join(f'  {{name = "{n}", lat = {la}, lon = {lo}, tz = "{TZ[z]}"}},\n' for n, la, lo, z in CITIES) +
         "}\n"
         "-- END WORLD MASK")
text = SCRIPT.read_text()
text = re.sub(r"-- BEGIN WORLD MASK.*?-- END WORLD MASK", lambda m: block, text, flags=re.S)
SCRIPT.write_text(text)
print(f"{SCRIPT.name}: {COLS}x{ROWS} mask, {sum(s.count('#') for s in rows)} land dots")

# Firmware header: one uint64 per row, bit c set (from the least significant
# end) means land at column c. 32 rows x 8 bytes - 256 bytes of flash.
words = []
for s in rows:
    v = 0
    for c, ch in enumerate(s):
        if ch == "#": v |= 1 << c
    words.append(v)
HEADER.parent.mkdir(parents=True, exist_ok=True)
HEADER.write_text(f"""#pragma once
// GENERATED by tools/luasim/gen_world.py - do not edit.
//
// Land mask for the world clock: Natural Earth 1:110m, public domain, sampled
// onto {COLS}x{ROWS} dots. A dot is land if 2 of 9 points in its cell are.
// The Lua prototype in tools/luasim carries the same data from the same run.

#include <stdint.h>

#define WORLD_COLS {COLS}
#define WORLD_ROWS {ROWS}
static const float WORLD_TOP = {TOP}f, WORLD_BOTTOM = {BOT}f;

// Bit c, counted from the least significant end, set = land at column c.
static const uint64_t kWorldMask[WORLD_ROWS] = {{
""" + "".join(f"  0x{w:016X}ULL,\n" for w in words) + """};

struct WorldCity { const char *name; float lat, lon; const char *iana, *posix; };

// Built in; which one is home is decided at run time (worldclock.cpp).
static const WorldCity kWorldCities[] = {
""" + "".join(f'  {{"{n}", {la}f, {lo}f, "{z}", "{TZ[z]}"}},\n' for n, la, lo, z in CITIES) + """};
#define WORLD_CITY_COUNT (sizeof(kWorldCities) / sizeof(kWorldCities[0]))
""")
print(f"{HEADER.name}: {len(words)} rows, {len(CITIES)} cities")
