#!/usr/bin/env python3
"""Embed the Lua effects in the firmware, from the scripts luasim runs.

One source: tools/luasim/scripts/*.lua. This writes src/lua/lua_effects_scripts.h,
which the firmware compiles in, so what is judged on the desk is what runs on
the panel. The pre-commit hook runs --check, which needs no network and no
build, and refuses a commit where the header and the scripts disagree.

  python3 tools/luasim/gen_effects.py           # regenerate
  python3 tools/luasim/gen_effects.py --check   # exit 1 if the header is stale

Every script becomes an effect unless SKIP says why not, or the script marks
itself @upload-only. The order is the
file names' order, which is the order the knob and the carousel walk.
"""
import pathlib, sys

ROOT    = pathlib.Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "tools/luasim/scripts"
OUT     = ROOT / "src/lua/lua_effects_scripts.h"

SKIP = {
    "demo.lua":        "a test card for the px.* API, not something to hang on a wall",
    "cyrillic_test.lua": "a test card for Latin and Cyrillic text, held to parity by fx_parity",
    "sysfont_test.lua": "a test card for px.text's fonts (5x7, pico), held to parity by fx_parity",
    "world_clock.lua": "already a native page drawing the same picture (src/worldclock, "
                       "WORLDCLOCK_ENABLED); a second copy would show twice in the rotation",
}

# Since scripts can be uploaded to a running panel (src/lua/lua_store.h), this
# directory holds two kinds of thing: what ships inside the image, and what is
# only ever sent over the air. A script says which it is, in itself, rather than
# in a list here that would have to be kept in step with it:
#
#     -- @upload-only
#
# anywhere in its first ten lines. Without it the pre-commit hook would demand
# a regenerated header for every experiment that happened to be left in the
# directory, which is how a hook stops being read.
UPLOAD_ONLY = "@upload-only"


def upload_only(path):
    with open(path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            if i >= 10:
                break
            if UPLOAD_ONLY in line:
                return True
    return False


def c_string(src):
    """The source as C string literal lines, one per script line."""
    lines = []
    for line in src.splitlines(keepends=True):
        out = []
        for ch in line.encode("utf-8"):
            c = chr(ch)
            if c == "\\":
                out.append("\\\\")
            elif c == '"':
                out.append('\\"')
            elif c == "?":
                out.append("\\?")                # no trigraphs, ever
            elif c == "\n":
                out.append("\\n")
            elif 0x20 <= ch < 0x7F:
                out.append(c)
            else:
                out.append(f"\\{ch:03o}")        # always three digits: cannot run on
        lines.append('  "' + "".join(out) + '"')
    return "\n".join(lines) if lines else '  ""'


def generate():
    scripts = [p for p in sorted(SCRIPTS.glob("*.lua"))
               if p.name not in SKIP and not upload_only(p)]
    if not scripts:
        raise SystemExit("gen_effects: no scripts to embed")
    body = []
    table = []
    for p in scripts:
        ident = p.stem
        if not ident.replace("_", "").isalnum():
            raise SystemExit(f"gen_effects: {p.name}: file name must be letters, digits and _")
        name = ident.replace("_", " ").upper()
        body.append(f"// {p.name}\nstatic const char kLuaFxSrc_{ident}[] =\n{c_string(p.read_text())};\n")
        table.append(f'  {{"{ident}", "{name}", kLuaFxSrc_{ident}, sizeof(kLuaFxSrc_{ident}) - 1}},')
    skipped = "\n".join(f"//   {k}: {v}" for k, v in sorted(SKIP.items()))
    over_air = sorted(p.name for p in SCRIPTS.glob("*.lua") if upload_only(p))
    if over_air:
        skipped += ("\n//   sent over the air instead, marked @upload-only: "
                    + ", ".join(over_air))
    return f"""#pragma once
// GENERATED by tools/luasim/gen_effects.py from tools/luasim/scripts/*.lua - do not edit.
//
// The Lua effects the panel carries, in the order the knob walks them. Edit a
// script and rerun the generator; the pre-commit hook refuses a stale copy.
// Not embedded:
{skipped}

#include <stdint.h>

#define LUA_EFFECT_COUNT {len(scripts)}

// The sources are only compiled where the table is wanted (lua_effects.cpp);
// everyone else gets the count.
#if defined(LUA_EFFECTS_TABLE)

struct LuaEffectScript {{
  const char *id;     // chunk name in error messages
  const char *name;   // shown in the banner
  const char *src;
  uint32_t    len;
}};

{chr(10).join(body)}
static const LuaEffectScript kLuaEffectScripts[LUA_EFFECT_COUNT] = {{
{chr(10).join(table)}
}};

#endif  // LUA_EFFECTS_TABLE
"""


def main():
    text = generate()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("gen_effects: src/lua/lua_effects_scripts.h does not match tools/luasim/scripts/")
            sys.exit(1)
        return
    OUT.write_text(text)
    print(f"{OUT.relative_to(ROOT)}: {text.count('kLuaFxSrc_') // 3} effects, {len(text)} bytes")


main()
