#!/usr/bin/env python3
"""Generate font_picopixel.inc for the simulator from the firmware's own font.

Same source, so the simulator cannot draw text the panel would draw differently.
"""
import pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
SRC  = ROOT / "src/fonts/picopixel_fb.h"
OUT  = pathlib.Path(__file__).resolve().parent / "font_picopixel.inc"

t = SRC.read_text()
bm = re.sub(r"//.*", "", re.search(r"PicopixelFBBitmaps\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", t, re.S).group(1))
BM = [int(x, 16) for x in re.findall(r"0[xX]([0-9a-fA-F]{2})", bm)]

# The glyph table is the stock one, so read it from the vendor font header.
import glob
cand = glob.glob(str(ROOT / ".pio/libdeps/*/Adafruit GFX Library/Fonts/Picopixel.h"))
if not cand:
    raise SystemExit("gen_font: build once so Adafruit GFX is downloaded")
gt = re.sub(r"//.*", "", re.search(r"PicopixelGlyphs\[\]\s*PROGMEM\s*=\s*\{(.*?)\};",
                                   pathlib.Path(cand[0]).read_text(), re.S).group(1))
G = [tuple(int(v) for v in m) for m in re.findall(
    r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}", gt)]

# Cyrillic and the missing-glyph box: the block tools/fonts/mkcyr.py wrote
# into the same header.
def arr(name):
    m = re.search(name + r"\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", t, re.S)
    if not m:
        raise SystemExit(f"gen_font: {name} not in picopixel_fb.h - run tools/fonts/mkcyr.py")
    return re.sub(r"//.*", "", m.group(1))
CBM = [int(x, 16) for x in re.findall(r"0[xX]([0-9a-fA-F]{2})", arr("PicopixelCyrBitmaps"))]
TUP = r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}"
CG  = [tuple(int(v) for v in m) for m in re.findall(TUP, arr("PicopixelCyrGlyphs"))]
cf  = re.search(r"PicopixelCyrGlyphs, 0x([0-9A-Fa-f]{4}), 0x([0-9A-Fa-f]{4})", t)
mg  = re.search(r"PicopixelMissingGlyph\s*PROGMEM\s*=\s*" + TUP, t)
if not cf or not mg:
    raise SystemExit("gen_font: the Cyrillic block in picopixel_fb.h is incomplete - run tools/fonts/mkcyr.py")
CFIRST, CLAST = int(cf.group(1), 16), int(cf.group(2), 16)
MISS = tuple(int(v) for v in mg.groups())
assert len(CG) == CLAST - CFIRST + 1

rows = "\n".join("  " + " ".join(f"0x{b:02X}," for b in BM[i:i+12]) for i in range(0, len(BM), 12))
crows = "\n".join("  " + " ".join(f"0x{b:02X}," for b in CBM[i:i+12]) for i in range(0, len(CBM), 12))
cgly = "\n".join(f"  {{{o:4d},{w:2d},{h:2d},{a:2d},{xo:3d},{yo:3d}}},  // U+{CFIRST+i:04X}"
                  for i, (o, w, h, a, xo, yo) in enumerate(CG))
gly  = "\n".join(f"  {{{o:4d},{w:2d},{h:2d},{a:2d},{xo:3d},{yo:3d}}},  // 0x{0x20+i:02X}"
                 for i, (o, w, h, a, xo, yo) in enumerate(G))

TEXT = (f"""// GENERATED by tools/luasim/gen_font.py from src/fonts/picopixel_fb.h.
// The simulator draws text with exactly the font the panel draws with,
// including the corrected U.
#define PICO_YADV 7
typedef struct {{ short off; unsigned char w, h, adv; signed char xo, yo; }} PicoGlyph;
static const unsigned char kPicoBitmap[] = {{
{rows}
}};
static const PicoGlyph kPicoGlyphs[] = {{
{gly}
}};
#define PICO_CYR_FIRST 0x{CFIRST:04X}
#define PICO_CYR_LAST  0x{CLAST:04X}
static const unsigned char kPicoCyrBitmap[] = {{
{crows}
}};
static const PicoGlyph kPicoCyrGlyphs[] = {{
{cgly}
}};
static const PicoGlyph kPicoMissing = {{{MISS[0]},{MISS[1]},{MISS[2]},{MISS[3]},{MISS[4]},{MISS[5]}}};
""")
if "--check" in sys.argv:
    if not OUT.exists() or OUT.read_text() != TEXT:
        sys.exit("gen_font: font_picopixel.inc is stale - run python3 tools/luasim/gen_font.py")
    print("gen_font: font_picopixel.inc up to date")
    sys.exit(0)
OUT.write_text(TEXT)
print(f"font_picopixel.inc: {len(BM)} bitmap bytes, {len(G)} glyphs; Cyrillic {len(CBM)} bytes, {len(CG)} glyphs")
