#!/usr/bin/env python3
"""Write the land mask into scripts/world_clock.lua.

Source: Natural Earth 1:110m land, public domain. Each of the 64x32 dots
covers a 5.6 x 4.25 degree cell; it is land if at least 2 of 9 sample points
inside the cell are. Sampling only the centre loses Italy, Japan and the UK,
and sampling any-of-9 bloats every coastline - 2 of 9 is where the continents
stay recognisable at this size.

  python3 gen_world.py
"""
import json, pathlib, re, urllib.request

HERE = pathlib.Path(__file__).resolve().parent
SRC  = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
CACHE = pathlib.Path("/tmp/ne_110m_land.geojson")
SCRIPT = HERE / "scripts/world_clock.lua"
COLS, ROWS, TOP, BOT, THRESH = 64, 32, 78.0, -58.0, 2

if not CACHE.exists():
    urllib.request.urlretrieve(SRC, CACHE)
d = json.loads(CACHE.read_text())
rings = [f["geometry"]["coordinates"][0] for f in d["features"]]
boxes = [(min(p[0] for p in r), max(p[0] for p in r), min(p[1] for p in r), max(p[1] for p in r)) for r in rings]

def land(lon, lat):
    for ring, (x0, x1, y0, y1) in zip(rings, boxes):
        if not (x0 <= lon <= x1 and y0 <= lat <= y1):
            continue
        inside, j = False, len(ring) - 1
        for i in range(len(ring)):
            xi, yi = ring[i]; xj, yj = ring[j]
            if (yi > lat) != (yj > lat) and lon < (xj - xi) * (lat - yi) / (yj - yi) + xi:
                inside = not inside
            j = i
        if inside:
            return True
    return False

dl, dp = 360 / COLS, (TOP - BOT) / ROWS
rows = []
for r in range(ROWS):
    s = ""
    for c in range(COLS):
        n = sum(land(-180 + (c + (a + .5) / 3) * dl, TOP - (r + (b + .5) / 3) * dp)
                for a in range(3) for b in range(3))
        s += "#" if n >= THRESH else "."
    rows.append(s)

block = ("-- BEGIN WORLD MASK - generated by tools/luasim/gen_world.py, do not edit\n"
         "local MASK = {\n" + "".join(f'  "{s}",\n' for s in rows) + "}\n"
         f"local MASK_TOP, MASK_BOTTOM = {TOP}, {BOT}\n"
         "-- END WORLD MASK")
text = SCRIPT.read_text()
text = re.sub(r"-- BEGIN WORLD MASK.*?-- END WORLD MASK", lambda m: block, text, flags=re.S)
SCRIPT.write_text(text)
print(f"{SCRIPT.name}: {COLS}x{ROWS} mask, {sum(s.count('#') for s in rows)} land dots")
