#!/usr/bin/env python3
"""Generate font_picopixel.inc for the simulator from the firmware's own font.

Same source, so the simulator cannot draw text the panel would draw differently.
"""
import pathlib, re
ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
SRC  = ROOT / "src/fonts/picopixel_fb.h"
OUT  = pathlib.Path(__file__).resolve().parent / "font_picopixel.inc"

t = SRC.read_text()
bm = re.sub(r"//.*", "", re.search(r"PicopixelFBBitmaps\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", t, re.S).group(1))
BM = [int(x, 16) for x in re.findall(r"0[xX]([0-9a-fA-F]{2})", bm)]

# The glyph table is the stock one, so read it from the vendor font header.
import glob
cand = glob.glob(str(ROOT / ".pio/libdeps/*/Adafruit GFX Library/Fonts/Picopixel.h"))
if not cand:
    raise SystemExit("gen_font: build once so Adafruit GFX is downloaded")
gt = re.sub(r"//.*", "", re.search(r"PicopixelGlyphs\[\]\s*PROGMEM\s*=\s*\{(.*?)\};",
                                   pathlib.Path(cand[0]).read_text(), re.S).group(1))
G = [tuple(int(v) for v in m) for m in re.findall(
    r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}", gt)]

rows = "\n".join("  " + " ".join(f"0x{b:02X}," for b in BM[i:i+12]) for i in range(0, len(BM), 12))
gly  = "\n".join(f"  {{{o:4d},{w:2d},{h:2d},{a:2d},{xo:3d},{yo:3d}}},  // 0x{0x20+i:02X}"
                 for i, (o, w, h, a, xo, yo) in enumerate(G))

OUT.write_text(f"""// GENERATED by tools/luasim/gen_font.py from src/fonts/picopixel_fb.h.
// The simulator draws text with exactly the font the panel draws with,
// including the corrected U.
#define PICO_YADV 7
typedef struct {{ short off; unsigned char w, h, adv; signed char xo, yo; }} PicoGlyph;
static const unsigned char kPicoBitmap[] = {{
{rows}
}};
static const PicoGlyph kPicoGlyphs[] = {{
{gly}
}};
""")
print(f"font_picopixel.inc: {len(BM)} bitmap bytes, {len(G)} glyphs")
