#!/usr/bin/env python3
"""A photograph into a Lua effect that draws it.

Not ASCII art - the picture itself, at the panel's own 128x64. Three things make
it fit and make it cheap:

**A palette, as large as will fit.** 8,192 pixels as full RGB would be 49,152
characters of source against the panel's limit, so the picture is quantised - but to
256 colours, not to the sixteen the firmware's own animation format allows.
Two base64 characters an index, Floyd-Steinberg on the way in. At 128x64 that is
photographic: the eye runs out before the palette does.

**And no run-length coding**, which was tried and thrown away. Dithering is what
keeps a face from banding at this size, and dithering is exactly what destroys
runs: 8,192 pixels came out as 7,232 runs, so the length byte was pure overhead
and the file went over the limit. Two characters a pixel, flat, is smaller than
three characters a run - 19 KB against 25 - and it is also simpler.

**Drawn once.** This firmware does not clear the canvas between frames, so the
photograph is painted on the first frame and never again. After that the effect
costs one text call a second for the clock, or nothing at all without it.

    python3 tools/luasim/photo_to_lua.py photo.jpg --name red_hat
    python3 tools/luasim/photo_to_lua.py photo.jpg --name red_hat \\
        --crop 0.05,0.32,0.95,0.74 --clock br
"""

import argparse
import pathlib
import sys

from PIL import Image, ImageEnhance

W, H = 128, 64
# base64url, so a run index and a length are one character each and the Lua
# string needs no escaping.
ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


def enc2(v):
    """An index as two base64 characters: 0..4095, of which 256 are used."""
    return ALPHA[v >> 6] + ALPHA[v & 63]


def encode_rows(idx, cols):
    """Each row as two base64 characters a pixel."""
    rows = []
    for y in range(H):
        rows.append("".join(enc2(idx[y * W + x]) for x in range(W)))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--name", required=True)
    ap.add_argument("--crop", default="", help="l,t,r,b as fractions")
    ap.add_argument("--colors", type=int, default=256,
                    help="2..256. 256 is photographic at this size and still fits")
    ap.add_argument("--contrast", type=float, default=1.0)
    ap.add_argument("--saturation", type=float, default=1.0)
    ap.add_argument("--brightness", type=float, default=1.0)
    ap.add_argument("--sharpen", type=float, default=0.0,
                    help="unsharp after the downscale. A face at 128x64 has lost "
                         "every edge it had; a little back is worth a lot")
    ap.add_argument("--clock", default="br", choices=["br", "bl", "tr", "tl", "none"],
                    help="where the time goes, or none")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    if not 2 <= args.colors <= 256:
        sys.exit("--colors must be 2..256")

    im = Image.open(args.image).convert("RGB")
    if args.crop:
        l, t, r, b = (float(v) for v in args.crop.split(","))
        iw, ih = im.size
        im = im.crop((int(l * iw), int(t * ih), int(r * iw), int(b * ih)))
    if args.brightness != 1.0:
        im = ImageEnhance.Brightness(im).enhance(args.brightness)
    if args.contrast != 1.0:
        im = ImageEnhance.Contrast(im).enhance(args.contrast)
    if args.saturation != 1.0:
        im = ImageEnhance.Color(im).enhance(args.saturation)

    im = im.resize((W, H), Image.LANCZOS)
    if args.sharpen > 0:
        from PIL import ImageFilter
        im = im.filter(ImageFilter.UnsharpMask(radius=1,
                                               percent=int(args.sharpen * 100),
                                               threshold=0))
    # Dithered: at 64 colours a photograph's skin tones band badly without it,
    # and on a 2 mm pitch the dither is invisible from across a room.
    q = im.quantize(colors=args.colors, method=Image.MEDIANCUT, dither=Image.FLOYDSTEINBERG)
    pal = q.getpalette()[: args.colors * 3]
    idx = list(q.getdata())

    rows = encode_rows(idx, args.colors)
    palette = "".join(f"{v:02X}" for v in pal)
    total = sum(len(r) for r in rows)

    body = [
        "-- @upload-only",
        f"-- {args.name.upper()} - a photograph, drawn once.",
        "--",
        "-- Generated by tools/luasim/photo_to_lua.py. The picture is quantised to",
        f"-- {args.colors} colours with Floyd-Steinberg and written two base64",
        "-- characters a pixel. It is painted on the first frame and never again,",
        "-- because this firmware does not clear the canvas between frames - so",
        "-- after that the effect costs one text call a second, or nothing at all",
        "-- if the clock is off.",
        "--",
        "-- The first frame is 8,192 calls into C and takes something like 170 ms of",
        "-- the 500 ms a draw is allowed. That is the whole cost of the effect.",
        "",
        "PERIOD = 60.0",
        "FPS = 2",
        "",
        f'local PAL = "{palette}"',
        "local ROWS = {",
    ]
    for r in rows:
        body.append(f'  "{r}",')
    body += [
        "}",
        "",
        "-- The palette, unpacked once at load rather than parsed per pixel.",
        "local R, G, B = {}, {}, {}",
        f"for i = 0, {args.colors - 1} do",
        "  local h = i * 6",
        "  R[i] = tonumber(PAL:sub(h + 1, h + 2), 16)",
        "  G[i] = tonumber(PAL:sub(h + 3, h + 4), 16)",
        "  B[i] = tonumber(PAL:sub(h + 5, h + 6), 16)",
        "end",
        "",
        'local A = "' + ALPHA + '"',
        "local VAL = {}",
        "for i = 1, #A do VAL[A:sub(i, i)] = i - 1 end",
        "",
        "local painted = false",
        "",
        "local function paint()",
        "  for y = 1, #ROWS do",
        "    local row = ROWS[y]",
        "    local yy = y - 1",
        "    for x = 0, 127 do",
        "      local i = x * 2 + 1",
        "      local c = VAL[row:sub(i, i)] * 64 + VAL[row:sub(i + 1, i + 1)]",
        "      px.pixel(x, yy, R[c], G[c], B[c])",
        "    end",
        "  end",
        "end",
        "",
        "function draw()",
        "  if not painted then",
        "    paint()",
        "    painted = true",
        "  end",
    ]
    if args.clock != "none":
        pos = {"br": ("W - w - 2", "H - 8"), "bl": ("2", "H - 8"),
               "tr": ("W - w - 2", "1"), "tl": ("2", "1")}[args.clock]
        body += [
            "",
            "  -- The time, over the photograph rather than beside it. A filled box",
            "  -- behind it was tried and looks like a sticker; four offset copies in",
            "  -- black are a proper outline and let the picture through.",
            "  local t = px.now()",
            '  local s = string.format("%02d:%02d", t.hour, t.min)',
            "  local W, H = px.size()",
            "  local w = px.width(s)",
            f"  local tx, ty = {pos[0]}, {pos[1]}",
            "  px.text(tx - 1, ty, s, 0, 0, 0)",
            "  px.text(tx + 1, ty, s, 0, 0, 0)",
            "  px.text(tx, ty - 1, s, 0, 0, 0)",
            "  px.text(tx, ty + 1, s, 0, 0, 0)",
            "  px.text(tx, ty, s, 245, 245, 250)",
        ]
    body += ["end", ""]

    out = pathlib.Path(args.out) if args.out else \
        pathlib.Path(__file__).resolve().parent / "scripts" / f"{args.name}.lua"
    out.write_text("\n".join(body))
    # The limit comes from the firmware header through validate.py, never from a
    # number typed here. This line said "% of 24576" until the cap was raised to
    # 50 KB and then quietly reported nonsense - a tool that measures against a
    # remembered constant measures nothing.
    cap = 0
    try:
        sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
        import validate as V  # noqa: PLC0415
        v = V.check(out)
        cap = (v or {}).get("maxBytes", 0)
    except Exception:  # noqa: BLE001
        pass
    size = out.stat().st_size
    pct = f", {100 * size // cap}% of the panel's {cap // 1024} KB limit" if cap else ""
    print(f"{out}  {size} B  ({args.colors} colours, 8192 pixels{pct})")


if __name__ == "__main__":
    main()
