#!/usr/bin/env python3
"""Drive scripts/room_radar.lua from a RECORDED presence session, not fake_targets().

Preview tooling. It renders what the panel would have shown during a session the
sensor actually recorded, so the scale and the mirroring can be chosen before any
firmware is written.

    python3 tools/luasim/presence_feed.py --frames <session.json> \\
            --from 700 --to 790 --out gifs/presence

The recording stays wherever it lives - it is a log of where people were in a
room. This tool reads it, writes the generated Lua and the raw frames into the
output directory, and NOTHING from it is ever written into the repository. Point
--out at an ignored directory (gifs/ is one).

The session file is {start_utc, seconds, frames: [[sec, [[x,y,speed]|null, ...3],
people, moving, still, lux], ...]}: x and y in mm, speed in mm/s, about one
update a second per target, an absent target being null or a 0/0 pair.

The seam
--------
room_radar.lua invents its people in fake_targets(s) / count_targets(s) and reads
its trail straight out of the scripted paths. This replaces exactly those three
reads with a lookup into the recording and changes nothing else about the
drawing, except the scale under test (--range) and the mirror (--mirror), which
is the whole point of the exercise.

A sample is held until the next one arrives. That is what a Home Assistant state
does between updates, so a second missing from the recording is a HELD sample,
not an absent target - the difference matters, and inventing an absence here
would show a disappearance the sensor never reported.

Units: fake_targets() hands the scene a speed in cm/s (it is millimetres of
travel per 0.1 s), and the scene's "is this person moving" test is
`t.speed > 12`, i.e. 12 cm/s. Home Assistant reports mm/s, SIGNED - negative is
approaching. So the faithful seam is abs(mm/s) / 10. --speed raw passes Home
Assistant's number through untouched instead, which is what a binding written
without checking the units would do; it is there to be looked at, not used.
"""
import argparse, json, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
SCENE = HERE / "scripts/room_radar.lua"
W, H = 128, 64
FRAME = W * H * 3


# --------------------------------------------------------------- the recording
def load_window(path, lo, hi, mirror, speed_mode, stop_at):
    """[(t, [slot1, slot2, slot3])], t in seconds from the window's start."""
    doc = json.loads(pathlib.Path(path).read_text())
    rows = []
    for rec in doc["frames"]:
        sec, targets = rec[0], rec[1]
        if sec < lo or sec >= hi:
            continue
        t = sec - lo
        if stop_at is not None and t > stop_at:
            continue
        slots = []
        for tg in targets:
            if not tg or (tg[0] == 0 and tg[1] == 0):      # null, and 0/0, are absent
                slots.append(None)
                continue
            x, y, speed = int(tg[0]), int(tg[1]), int(tg[2])
            if mirror:
                x = -x
            speed = speed if speed_mode == "raw" else abs(speed) // 10
            slots.append((x, y, speed))
        rows.append((t, slots))
    if not rows:
        sys.exit(f"presence_feed: no samples in [{lo}, {hi})")
    return rows, doc["start_utc"]


def lua_feed(rows):
    out = ["-- Generated by tools/luasim/presence_feed.py from a recorded session.",
           "-- It is where people were in a room: it does not go into the repository.",
           "FEED_T = {" + ",".join(f"{t:g}" for t, _ in rows) + "}",
           "FEED = {"]
    for _, slots in rows:
        cells = ",".join("false" if s is None else f"{{{s[0]},{s[1]},{s[2]}}}" for s in slots)
        out.append(f"{{{cells}}},")
    out += ["}", f"FEED_N = {len(rows)}", ""]
    return "\n".join(out)


# ------------------------------------------------------------------- the patch
FEED_FUNCS = """
-- ------------------------------------------------------- the recorded feed
-- What the radar actually reported, in place of fake_targets(). FEED_T[i] is
-- when sample i arrived, seconds from the start of the window; FEED[i] holds
-- its three slots, each {x, y, speed} in mm and the scene's cm/s, or false.
--
-- A sample is HELD until the next one arrives: that is what a Home Assistant
-- state does between updates, so a second with no report is a held sample and
-- not a target that vanished. On the panel this is a binding that keeps the
-- last three reports, and the trail below is the short history per slot the
-- scene's own comment asks for.
local FEED, FEED_T, FEED_N = FEED, FEED_T, FEED_N

local function feed_row(s)
  s = s %% STORY
  if s < FEED_T[1] then return nil end
  local lo, hi = 1, FEED_N
  while lo < hi do
    local mid = (lo + hi + 1) // 2
    if FEED_T[mid] <= s then lo = mid else hi = mid - 1 end
  end
  return FEED[lo]
end

local function feed_pos(slot, s)
  local row = feed_row(s)
  local t = row and row[slot]
  if not t then return nil end
  return t[1] / 1000, t[2] / 1000
end

local function fake_targets(s)
  local out = {}
  local row = feed_row(s)
  if not row then return out end
  for i = 1, 3 do
    local t = row[i]
    if t and in_fan(t[1] / 1000, t[2] / 1000) then
      out[#out + 1] = {x = t[1], y = t[2], speed = t[3], slot = i}
    end
  end
  return out
end
"""

COUNT_FUNCS = """local function count_targets(s)
  local n = 0
  local row = feed_row(s)
  if row then
    for i = 1, 3 do
      local t = row[i]
      if t and in_fan(t[1] / 1000, t[2] / 1000) then n = n + 1 end
    end
  end
  return n
end
"""


def sub1(text, pattern, repl, what):
    new, n = re.subn(pattern, repl, text, flags=re.S)
    if n != 1:
        sys.exit(f"presence_feed: room_radar.lua no longer has its {what} ({n} matches)")
    return new


def patch_scene(story, range_m, ppm):
    s = SCENE.read_text()
    rings = int(range_m)
    labels = [2, 4, 6] if rings >= 6 else [2, 4] if rings >= 4 else list(range(1, rings + 1))
    s = sub1(s, r"local STORY  = 24\.0.*?\n", f"local STORY  = {story:g}"
             "            -- seconds of the recorded window; px.t() spans it\n", "STORY line")
    s = sub1(s, r"local PPM    = 10 *", f"local PPM    = {ppm:g}" + " " * 14, "PPM line")
    s = sub1(s, r"local RANGE, HALF = 6\.0, 60", f"local RANGE, HALF = {range_m:g}, 60", "RANGE line")
    s = sub1(s, r"for k = 1, 6 do", f"for k = 1, {rings} do", "ring loop")
    s = sub1(s, r"ipairs\(\{2, 4, 6\}\)", "ipairs({%s})" % ", ".join(map(str, labels)), "range labels")
    # the seam: three reads of the scripted people become three reads of the feed
    s = sub1(s, r"local function fake_targets\(s\).*?\nend\n", FEED_FUNCS % () + "", "fake_targets")
    s = sub1(s, r"local function count_targets\(s\).*?\nend\n", COUNT_FUNCS, "count_targets")
    s = sub1(s, r"local x, y = pos\(person, S - k \* 0\.1\)",
             "local x, y = feed_pos(t.slot, S - k * 0.1)", "trail lookup")
    return s


# ------------------------------------------------------------------ rendering
def render(lua_path, frames, raw_path, start_hhmm):
    r = subprocess.run([str(HERE / "luasim"), str(lua_path), str(frames), str(raw_path),
                        "--start", start_hhmm], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"luasim: {r.stderr.strip()}")
    return pathlib.Path(raw_path).read_bytes()


def frame_image(raw, i, scale):
    from PIL import Image
    img = Image.frombytes("RGB", (W, H), raw[i * FRAME:(i + 1) * FRAME])
    return img.resize((W * scale, H * scale), Image.NEAREST)


def write_gif(raw, out, fps, scale, colors=32):
    n = len(raw) // FRAME
    imgs = [frame_image(raw, i, scale).quantize(colors=colors, dither=0) for i in range(n)]
    imgs[0].save(out, save_all=True, append_images=imgs[1:], duration=int(round(1000 / fps)),
                 loop=0, optimize=True)
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", required=True, help="the recorded session JSON (kept outside the repo)")
    ap.add_argument("--from", dest="lo", type=int, required=True, help="window start, session seconds")
    ap.add_argument("--to", dest="hi", type=int, required=True, help="window end, session seconds")
    ap.add_argument("--range", type=float, default=6.0, help="metres the fan covers")
    ap.add_argument("--ppm", type=float, default=None, help="pixels per metre (default: 60 px / range)")
    ap.add_argument("--mirror", action="store_true", help="flip X, for the room's unknown handedness")
    ap.add_argument("--speed", choices=("cms", "raw"), default="cms")
    ap.add_argument("--stop-at", type=float, default=None, help="seconds in, stop feeding new samples")
    ap.add_argument("--fps", type=float, default=10.0)
    ap.add_argument("--scale", type=int, default=2)
    ap.add_argument("--name", default=None)
    ap.add_argument("--out", required=True)
    ap.add_argument("--no-gif", action="store_true", help="render the frames, write no GIF")
    a = ap.parse_args()

    ppm = a.ppm if a.ppm else 60.0 / a.range
    out = pathlib.Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    name = a.name or f"room_radar_real_{a.range:g}m" + ("_mirror" if a.mirror else "")

    rows, start_utc = load_window(a.frames, a.lo, a.hi, a.mirror, a.speed, a.stop_at)
    story = a.hi - a.lo
    lua = out / f"{name}.lua"
    lua.write_text(lua_feed(rows) + patch_scene(story, a.range, ppm))

    import time
    clock = time.localtime(start_utc + a.lo)
    frames = int(round(story * a.fps))
    raw = render(lua, frames, out / f"{name}.raw", time.strftime("%H:%M", clock))
    print(f"{name}: {len(rows)} samples over {story}s, {frames} frames at {a.fps:g} fps, "
          f"range {a.range:g} m, {ppm:g} px/m{', mirrored' if a.mirror else ''}")
    if not a.no_gif:
        write_gif(raw, out / f"{name}.gif", a.fps, a.scale)
        print(f"  {out / (name + '.gif')}")


if __name__ == "__main__":
    main()
