#!/usr/bin/env python3
"""Would the panel accept this script? Answered here, by the panel's own code.

An upload that is going to be refused should be refused before it is spent, and
with the same sentence the panel would have used - not a guess at it. So this
compiles the real `src/lua/lua_store.cpp` for the host, against the stubs in
`host/store/`, and asks it.

Nothing is duplicated: if the rules on the panel change, this changes with them,
because it is the same file. The binary is cached and rebuilt only when the
source is newer.

    python3 tools/luasim/validate.py scripts/my_effect.lua
    python3 tools/luasim/validate.py --json scripts/my_effect.lua

Exit codes match the rest of the agent tooling: 0 the panel would take it,
2 it would not, 1 the check could not be run.
"""

import argparse
import json
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SRC = ROOT / "src" / "lua" / "lua_store.cpp"
# The header too, and this is not a detail: every limit this tool enforces -
# the size cap, the depth cap - is a #define in the header, not in the .cpp.
# Watching only the .cpp meant raising LUA_USER_SRC_MAX left a cached binary
# happily rejecting scripts by the old number, which is a checker that lies.
HDR = ROOT / "src" / "lua" / "lua_store.h"
RUNNER = HERE / ".validate_runner.cpp"
BIN = HERE / ".validate"

RUNNER_SRC = r'''// Generated by validate.py. The real luaStoreValidate, compiled for the host.
#define LUA_STORE_ENABLED 1
#define LUA_EFFECTS_ENABLED 1
#include "../../src/lua/lua_store.cpp"
#include <cstdio>
#include <vector>

int main(int argc, char **argv) {
  if (argc < 2) { printf("usage: validate <file>\n"); return 1; }
  FILE *f = fopen(argv[1], "rb");
  if (!f) { printf("NOFILE\n"); return 1; }
  std::vector<char> buf;
  int c;
  while ((c = fgetc(f)) != EOF) buf.push_back((char)c);
  fclose(f);
  buf.push_back('\0');
  char err[200] = {0};
  const bool ok = luaStoreValidate(buf.data(), buf.size() - 1, err, sizeof(err));
  printf("%s\n%s\n%u\n%u\n%d\n", ok ? "OK" : "NO", err,
         (unsigned)(buf.size() - 1), (unsigned)LUA_USER_SRC_MAX, LUA_USER_DEPTH_MAX);
  return ok ? 0 : 2;
}
'''


def build():
    newest = max(SRC.stat().st_mtime, HDR.stat().st_mtime,
                 pathlib.Path(__file__).stat().st_mtime)
    if BIN.exists() and BIN.stat().st_mtime > newest:
        return True
    RUNNER.write_text(RUNNER_SRC)
    r = subprocess.run(
        ["c++", "-std=gnu++11", "-O1", "-w",
         "-I", str(HERE / "host" / "store"), "-I", str(ROOT / "src" / "lua"),
         "-o", str(BIN), str(RUNNER)],
        capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-1500:], file=sys.stderr)
        return False
    return True


def check(path):
    """(ok, message, bytes, max_bytes, max_depth) from the panel's own rules."""
    if not build():
        return None
    r = subprocess.run([str(BIN), str(path)], capture_output=True, text=True)
    lines = (r.stdout or "").splitlines()
    if not lines or lines[0] == "NOFILE":
        return None
    return {"ok": lines[0] == "OK",
            "error": lines[1] if len(lines) > 1 and lines[1] else None,
            "bytes": int(lines[2]) if len(lines) > 2 else 0,
            "maxBytes": int(lines[3]) if len(lines) > 3 else 0,
            "maxDepth": int(lines[4]) if len(lines) > 4 else 0}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("script")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    got = check(args.script)
    if got is None:
        print("validate: could not run the panel's own check", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(got, ensure_ascii=False))
    elif got["ok"]:
        print(f"  ok   the panel would take it ({got['bytes']} B of {got['maxBytes']})")
    else:
        print(f"  НЕТ  {got['error']}")
    return 0 if got["ok"] else 2


if __name__ == "__main__":
    sys.exit(main())
