#!/usr/bin/env python3
"""Generate src/control/clock_styles.h from the web UI's own style list.

The set of clock styles is not a range: 4 is a legacy alias of 3, 13 was
retired, and "Custom rotation" (9) sits last rather than in numeric order. The
web page already carries the authoritative list, in the right order, with the
right names - so the knob reads it from there instead of keeping a second copy
that would quietly drift the first time a style is added.

  python3 tools/clock_styles_gen.py
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "src/web/web_pages.h"
OUT  = ROOT / "src/control/clock_styles.h"

def main():
    html = SRC.read_text()
    opts = re.findall(r'<option value="(\d+)"\s*%SEL_CLOCKSTYLE_\d+%>([^<]+)</option>', html)
    if not opts:
        raise SystemExit("clock_styles_gen: no clockStyle options found in web_pages.h")

    ids   = [int(v) for v, _ in opts]
    names = [n.strip() for _, n in opts]
    if len(set(ids)) != len(ids):
        raise SystemExit(f"clock_styles_gen: duplicate ids {ids}")

    # Names are for a 128 px panel in Picopixel, so trim the words the panel has
    # no room for and the reader does not need.
    def short(n):
        for junk in (" Animation", " Clock", " Runner"):
            n = n.replace(junk, "")
        return n.upper()

    rows = "\n".join(
        f'  {{ {i:2d}, {chr(34) + short(n) + chr(34):<18} }},   // {n}'
        for i, n in zip(ids, names))

    OUT.write_text(f'''#pragma once
// GENERATED by tools/clock_styles_gen.py from src/web/web_pages.h - do not edit.
//
// The styles the knob walks, in the order and with the names the web UI uses.
// Not a range: 4 is a legacy alias of 3 and is not offered, 13 was retired, and
// Custom rotation sits last rather than in numeric order.

#include <stdint.h>

struct ClockStyleEntry {{ uint8_t id; const char *name; }};

#define CLOCK_STYLE_COUNT {len(ids)}

static const ClockStyleEntry kClockStyles[CLOCK_STYLE_COUNT] = {{
{rows}
}};
''')
    print(f"src/control/clock_styles.h: {len(ids)} styles — " +
          ", ".join(f"{i}:{short(n)}" for i, n in zip(ids, names)))

main()
