#!/usr/bin/env python3
"""Gzip the portal's style, script and icon into src/web/web_assets.h.

The panel serves the portal from loop() at 70-100 KB/s, and the picture stands
still while it does: on 2026-09-14 /panel.js (99,638 B) held loop() for 987 ms
and /portal.js (44,115 B) for 537 ms. Gzipped they are a quarter of that.

The sources stay where they are, as the raw strings in src/web/web_pages.h,
web_panel_page.h and web_panel_js.h. Host checks read the scripts from there
(tools/media/check_media.py, tools/flightboard/check_portal_js.py,
tools/oscmusic/test_clip_maker.py), and so does every branch that changes the
portal. The firmware compiles only what this writes; nothing is served twice.

  python3 tools/web_assets_gen.py           # regenerate
  python3 tools/web_assets_gen.py --check   # exit 1 if web_assets.h is stale

The gzip carries no file name and mtime 0. A rerun keeps every blob that still
decompresses to its source, so another zlib on another machine neither rewrites
the header nor makes --check call it stale.
"""
import gzip, pathlib, re, sys
from collections import namedtuple

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB  = ROOT / "src/web"
OUT  = WEB / "web_assets.h"

Asset = namedtuple("Asset", "name src var url guard")

ASSETS = [
    Asset("WEB_PORTAL_CSS_GZ", "web_pages.h",      "PORTAL_CSS",  "/portal.css",  None),
    Asset("WEB_PORTAL_JS_GZ",  "web_pages.h",      "PORTAL_JS",   "/portal.js",   None),
    Asset("WEB_FAVICON_GZ",    "web_pages.h",      "FAVICON_SVG", "/favicon.svg", None),
    # Served only where the Panel group is: the 4MB boards carry none of it.
    Asset("WEB_PANEL_CSS_GZ",  "web_panel_page.h", "PANEL_CSS",   "/panel.css",   "CONTROL_ENCODER_ENABLED"),
    Asset("WEB_PANEL_JS_GZ",   "web_panel_js.h",   "PANEL_JS",    "/panel.js",    "CONTROL_ENCODER_ENABLED"),
]


def raw_string(src, var):
    """The bytes of `static const char VAR[] PROGMEM = R"d(...)d";`, as the compiler sees them."""
    text = (WEB / src).read_text(encoding="utf-8")
    m = re.search(r'\b%s\[\]\s*PROGMEM\s*=\s*R"(\w*)\((.*?)\)\1"' % var, text, re.S)
    if not m:
        raise SystemExit(f"web_assets_gen: no raw string {var} in src/web/{src}")
    if "\r" in m[2]:
        raise SystemExit(f"web_assets_gen: {var} in src/web/{src} has CR line endings")
    return m[2].encode("utf-8")


def gunzip(blob):
    try:
        return gzip.decompress(blob)
    except Exception:
        return None


def existing_blobs():
    if not OUT.exists():
        return {}
    return {name: bytes(int(h, 16) for h in re.findall(r"0x([0-9a-f]{2})", body))
            for name, body in re.findall(r"static const uint8_t (\w+)\[\] PROGMEM = \{(.*?)\};",
                                         OUT.read_text(), re.S)}


def compress(name, plain, old):
    prev = old.get(name)
    # Kept only if it is still this content and still carries no name and no mtime.
    if prev and prev[3] == 0 and prev[4:8] == b"\0\0\0\0" and gunzip(prev) == plain:
        return prev
    return gzip.compress(plain, compresslevel=9, mtime=0)


def c_bytes(data, per_line=20):
    return "\n".join("  " + "".join(f"0x{b:02x}," for b in data[i:i + per_line])
                     for i in range(0, len(data), per_line))


def render(blobs):
    out = ["""#pragma once
// GENERATED by tools/web_assets_gen.py from the raw strings in src/web/web_pages.h,
// web_panel_page.h and web_panel_js.h - do not edit.
//
// The portal's static files as gzip, served with Content-Encoding: gzip and no
// uncompressed copy. Edit the raw strings and rerun the generator; the pre-commit
// hook refuses a stale copy.

#include <Arduino.h>
"""]
    guard = None
    for a, plain, gz in blobs:
        if a.guard != guard:
            if guard:
                out.append(f"#endif  // {guard}\n")
            if a.guard:
                out.append(f"#if defined({a.guard})\n")
            guard = a.guard
        out.append(f"// {a.url} - {a.var} in src/web/{a.src}: {len(plain):,} B, gzip {len(gz):,} B\n"
                   f"static const uint8_t {a.name}[] PROGMEM = {{\n{c_bytes(gz)}\n}};\n")
    if guard:
        out.append(f"#endif  // {guard}\n")
    return "\n".join(out)


def main():
    old = existing_blobs()
    blobs = []
    for a in ASSETS:
        plain = raw_string(a.src, a.var)
        blobs.append((a, plain, compress(a.name, plain, old)))
    text = render(blobs)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("web_assets_gen: src/web/web_assets.h does not match the raw strings it is made from")
            sys.exit(1)
        return
    OUT.write_text(text)
    for a, plain, gz in blobs:
        print(f"  {a.url:14s} {len(plain):7,} B -> gzip {len(gz):6,} B ({100 * len(gz) / len(plain):.0f}%)")
    print(f"{OUT.relative_to(ROOT)}: {len(text):,} bytes")


main()
