#!/usr/bin/env python3
"""Bake the Bay of Cannes chart into src/yachtradar/basemap.h.

The map never changes, so nothing about it belongs at runtime: land/sea fill,
relief shading and the shoreline are all resolved here and shipped as one
64x64 RGB565 array. The panel blits it and draws vessels on top.

Inputs, both in the repo:
  src/yachtradar/coastline.h   geometry, generated by yr_coastline_gen.py
  tools/yr_data/terrain.json   measured elevation and depth (see its header)

  python3 tools/yr_basemap_gen.py [--png out.png]
"""
import json, math, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT  = ROOT / "src/yachtradar/basemap.h"
CX, CY, RPX, R_DAC = 31.0, 32.0, 31.0, 1900.0
SS = 8                                     # supersampling for the land mask

# Palettes. Deliberately dim: the map is a backdrop and the vessels must be
# brighter than it. On an LED panel that is also current - a bright 64x64 fill
# is real amperes.
MAPDIM = 0.55
SHOAL, AZURE, DEEP = (46,190,190), (16,92,168), (6,26,64)
LOW, MID, HIGH     = (26,66,38), (74,86,44), (126,74,52)   # Esterel is red porphyry
SHORE, RING        = (235,245,190), (180,220,255)

def mix(a, b, t):
    t = 0.0 if t < 0 else (1.0 if t > 1 else t)
    return [a[i] + (b[i]-a[i])*t for i in range(3)]

def load_coast():
    t = (ROOT / "src/yachtradar/coastline.h").read_text()
    segs = [int(x,16) for x in re.findall(r"0x([0-9A-Fa-f]{4})", t)]
    body = re.sub(r"//.*", "", re.search(r"kYrCoastXY\[[^\]]*\]\s*=\s*\{(.*?)\};", t, re.S).group(1))
    v = [int(x) for x in re.findall(r"-?\d+", body)]
    xy = list(zip(v[0::2], v[1::2]))
    P = lambda p: (CX + p[0]*RPX/R_DAC, CY - p[1]*RPX/R_DAC)
    out, i = [], 0
    for s in segs:
        n = s & 0x7FFF
        out.append((bool(s & 0x8000), [P(p) for p in xy[i:i+n]])); i += n
    return out

def land_mask(seg):
    # The mainland is a chain stitched by the three short "bridge" segments -
    # that is precisely why fx34 carries them. Closing it needs the frame edge:
    # land lies north-west of the shore, so the ring runs from the Theoule end
    # up the left edge, across the top and back to the Vallauris end. Points
    # sit outside the frame so the border contributes no artefacts.
    chain = seg[5][1] + seg[7][1][::-1] + seg[0][1] + seg[8][1] + seg[3][1] + seg[6][1] + seg[4][1]
    mainland = chain + [(-3.0, chain[-1][1]), (-3.0, -3.0), (chain[0][0], -3.0)]
    polys = [mainland, seg[1][1], seg[2][1]]
    N = 64 * SS
    acc = bytearray(N*N)
    for poly in polys:
        pts = [(x*SS, y*SS) for x, y in poly]
        ylo = max(0, int(min(p[1] for p in pts))); yhi = min(N-1, int(max(p[1] for p in pts)))
        for sy in range(ylo, yhi+1):
            yc = sy + 0.5; xs = []
            for (x0,y0),(x1,y1) in zip(pts, pts[1:]+pts[:1]):
                if (y0 <= yc) != (y1 <= yc):
                    xs.append(x0 + (yc-y0)*(x1-x0)/(y1-y0))
            xs.sort()
            for a, b in zip(xs[0::2], xs[1::2]):
                for sx in range(max(0,int(a)), min(N,int(b)+1)): acc[sy*N+sx] = 1
    cov = [[0.0]*64 for _ in range(64)]
    for y in range(64):
        for x in range(64):
            c = 0
            for j in range(SS):
                row = (y*SS+j)*N + x*SS
                c += sum(acc[row:row+SS])
            cov[y][x] = c/(SS*SS)
    return cov

def main():
    seg = load_coast()
    cov = land_mask(seg)
    T = json.loads((ROOT / "tools/yr_data/terrain.json").read_text())
    E = lambda x, y: (T["land"].get(f"{x},{y}") or 0)
    def D(x, y):
        v = T["sea"].get(f"{x},{y}")
        return -50 if v is None else v

    buf = [[[0.0]*3 for _ in range(64)] for _ in range(64)]
    for y in range(64):
        for x in range(64):
            d = -D(x, y)
            w = mix(SHOAL, AZURE, d/60.0) if d <= 60 else mix(AZURE, DEEP, (d-60)/500.0)
            e = E(x, y)
            base = mix(LOW, MID, e/90.0) if e < 90 else mix(MID, HIGH, (e-90)/180.0)
            # Hillshade with the sun in the north-west, straight off the DEM.
            sh = 1.0 + 0.0045*((E(x+1,y)-E(x-1,y))/2.0 + (E(x,y+1)-E(x,y-1))/2.0)
            sh = max(0.55, min(1.6, sh))
            l = [min(255.0, c*sh) for c in base]
            buf[y][x] = [v*MAPDIM for v in mix(w, l, cov[y][x])]

    def blend(x, y, c, a):
        if a <= 0 or not (0 <= x < 64 and 0 <= y < 64): return
        p = buf[y][x]
        for i in range(3): p[i] = min(255.0, p[i]*(1-a) + c[i]*a)
    def wupix(x, y, c, a):
        x0, y0 = math.floor(x), math.floor(y); fx, fy = x-x0, y-y0
        blend(x0,y0,c,a*(1-fx)*(1-fy)); blend(x0+1,y0,c,a*fx*(1-fy))
        blend(x0,y0+1,c,a*(1-fx)*fy);   blend(x0+1,y0+1,c,a*fx*fy)
    def wuline(x0, y0, x1, y1, c, a):
        steep = abs(y1-y0) > abs(x1-x0)
        if steep: x0,y0,x1,y1 = y0,x0,y1,x1
        if x0 > x1: x0,x1,y0,y1 = x1,x0,y1,y0
        dx = x1-x0; n = max(1, int(round(dx))*2)
        for i in range(n+1):
            x = x0 + dx*i/n; y = y0 + (y1-y0)*(i/n)
            wupix(y, x, c, a) if steep else wupix(x, y, c, a)

    for r, al in ((RPX*2/3, .10), (RPX, .14)):
        n = max(48, int(2*math.pi*r*2))
        p = [(CX + r*math.cos(2*math.pi*i/n), CY + r*math.sin(2*math.pi*i/n)) for i in range(n+1)]
        for a, b in zip(p, p[1:]): wuline(a[0], a[1], b[0], b[1], RING, al)
    wuline(CX, 1, CX, 62, RING, .09); wuline(0, CY, 62, CY, RING, .09)
    for closed, pts in seg:
        q = pts + [pts[0]] if closed else pts
        for a, b in zip(q, q[1:]): wuline(a[0], a[1], b[0], b[1], SHORE, .42)

    rgb565 = []
    for y in range(64):
        for x in range(64):
            r, g, b = (int(v) for v in buf[y][x])
            rgb565.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

    rows = []
    for i in range(0, len(rgb565), 12):
        rows.append("  " + " ".join(f"0x{v:04X}," for v in rgb565[i:i+12]))
    OUT.write_text(f'''#pragma once
// GENERATED by tools/yr_basemap_gen.py - do not edit.
//
// The Bay of Cannes, 64x64 in RGB565: sea coloured by measured depth, land by
// measured elevation with a north-west hillshade, shoreline drawn on top.
// None of it changes, so none of it is computed on the panel - the renderer
// blits this and draws vessels over it.
//
// Sea:  {T["source_sea"]}
// Land: {T["source_land"]}
// Measured {T["fetched"]}. Frame: {T["frame"]}.
//
// Held deliberately dim ({MAPDIM:.2f}): the map is a backdrop, the vessels must be
// brighter than it, and a bright 64x64 fill is real current on an LED panel.

#include <stdint.h>

#define YR_MAP_W 64
#define YR_MAP_H 64

static const uint16_t kYrBasemap[YR_MAP_W * YR_MAP_H] = {{
{chr(10).join(rows)}
}};
''')
    print(f"src/yachtradar/basemap.h: 64x64 RGB565, {len(rgb565)*2} bytes")
    if "--png" in sys.argv:
        from PIL import Image
        out = sys.argv[sys.argv.index("--png")+1]
        Image.frombytes("RGB", (64,64),
            bytes(int(v) for row in buf for p in row for v in p)).resize((576,576),
            Image.NEAREST).save(out)
        print("  preview:", out)

main()
