#!/usr/bin/env python3
"""Generate src/yachtradar/coastline.h from the NickoScope32 fx34 source.

The Bay of Cannes coastline is not ours: it was derived for fx34 from
gregoiredavid/france-geojson and clipped to the radar frame. Rather than retype
125 points, this reads them out of the fx34 effect and converts DAC units to
the pixel space of a 64x64 panel.

  python3 tools/yr_coastline_gen.py <path to fx34_yacht_radar.cpp>
"""
import pathlib, re, sys

R_DAC   = 1900.0     # outer ring; the frame the points were clipped to
R_PX    = 31.0       # 64x64 panel, centre at (31, 32)
CX, CY  = 31, 32
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/yachtradar/coastline.h"

def main():
    src = pathlib.Path(sys.argv[1]).read_text()
    seg = re.search(r"fx34_coast_seg_count\[[^\]]*\]\s*=\s*\{(.*?)\};", src, re.S).group(1)
    segs = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", seg)]
    pts = re.sub(r"//.*", "", re.search(r"fx34_coast_xy\[[^\]]*\]\s*=\s*\{(.*?)\};",
                                        src, re.S).group(1))
    v = [int(x) for x in re.findall(r"-?\d+", pts)]
    xy = list(zip(v[0::2], v[1::2]))
    assert len(xy) == sum(s & 0x7FFF for s in segs), "segment table and point count disagree"

    # Kept in DAC, NOT rounded to pixels. Rounding here would throw away the
    # sub-pixel position before the renderer can use it, and on an LED panel
    # sub-pixel position is exactly what brightness encodes: an anti-aliased
    # line at 64 px carries far more shape than a hard one. Projection happens
    # at draw time instead.
    P = list(xy)

    body, i, lines = [], 0, []
    for n, s in enumerate(segs):
        cnt = s & 0x7FFF
        lines.append(f"  // #{n}  {cnt} pts{'  closed' if s & 0x8000 else ''}")
        chunk = P[i:i + cnt]; i += cnt
        for j in range(0, len(chunk), 6):
            lines.append("  " + " ".join(f"{x:5d},{y:5d}," for x, y in chunk[j:j + 6]))

    OUT.write_text(f'''#pragma once
// GENERATED by tools/yr_coastline_gen.py - do not edit.
//
// Bay of Cannes coastline, {len(P)} points in {len(segs)} segments, in the DAC
// space fx34 clipped them to: north-up, outer ring {R_DAC:.0f} DAC = {R_DAC/300:.2f} km.
//
// Deliberately NOT pre-rounded to panel pixels. The renderer projects and
// anti-aliases at draw time, so the sub-pixel position of every point survives
// into the brightness of the pixels it lights - which is the only resolution a
// 64 px map has left to spend.
//
// Origin: NickoScope32 fx34_yacht_radar.cpp, itself derived from
// gregoiredavid/france-geojson and clipped to the radar frame.

#include <stdint.h>

#define YR_COAST_SEGS   {len(segs)}
#define YR_COAST_POINTS {len(P)}

// high bit = closed loop, low 15 bits = point count
static const uint16_t kYrCoastSeg[YR_COAST_SEGS] = {{
  {", ".join(f"0x{s:04X}" for s in segs)}
}};

static const int16_t kYrCoastXY[YR_COAST_POINTS * 2] = {{
{chr(10).join(lines)}
}};
''')
    lo = min(min(x, y) for x, y in P); hi = max(max(x, y) for x, y in P)
    print(f"{OUT.relative_to(OUT.parent.parent.parent)}: {len(P)} pts, {len(segs)} segs, "
          f"DAC range {lo}..{hi}, {len(P)*4} bytes")

main()
